### ISSUE TITLE
RFC: JSON Reporter - More detail / suites?

### ISSUE THREAD

**Issue by tmaiaroto** [mochajs/mocha#1112]
Can suites be added to the JSON output? It's impossible to tell which test belongs to which suite in the current format.

I would expect the output to be more like the doc reporter in this regard. Or the web console reporter. So that it has that hierarchy of suite -> test -> title

Right now the fullTitle isn't particularly useful for much.

Maybe we don't need the full stack trace and all...But certainly the rest of the hierarchy that you see in those other reporters.

Would be awesome.

**Comment by JoshuaKGoldberg** [comment]
This is a 9 year old issue with very little detail on what it's asking for and interaction from only two end users. I'm going to go ahead and close it out. Other issues have since discussed the JSON reporter in more granularity.

If you do want more detail / suites in the JSON reporter, please file a new issue with our new templates describing exactly what you'd want to see.

Thanks all!
