### ISSUE TITLE
Async test fails with timeout instead of assertion error

### ISSUE THREAD

**Issue by gurdiga** [mochajs/mocha#1128]
This test:

``` js
    it('returns the correct value', function(done) {
      var returnValue = 5;

      aPromise.then(function() {
        expect(returnValue).to.equal(42);
        done();
      });

    });
```

This test fails with `timeout of 2000ms exceeded` instead of assertion error. I guess that’s because `expect()` call throws an error, and the `done()` never gets executed, and I’m wondering if there is a better way to test this kind of code.

**Comment by DSheffield** [comment]
I ran into a similar problem, and eventually realized you shouldn't use done when testing asynchronous functions with promises, instead, just return the promise.  So you should be able to do this without the timout, e.g.:
```javascript
it('returns the correct value', function() {
    var returnValue = 5;

    return aPromise.then(function() {
        expect(returnValue).to.equal(42);
    });
});
```

**Comment by stevenvachon** [comment]
I think that this issue still exists. I'm getting a timeout issue that cannot be resolved by returning a promise because my module does not use promises.

**Comment by ScottFreeCode** [comment]
As regards the blog post's recommendations, I don't know about async function error handling, but for plain promises the try-catch recommendation is weird: the original promise attempt with no try-catch was nearly correct, it only needed to use `.catch(done)` instead of using the second parameter to `then` as `done`. (Granted, since Mocha has direct support for promises, you can also just return the promise, but for what it's worth...) The problem in the initial promise example wasn't absence of try-catch, it was that the second handler to `then` is not called with exceptions thrown by the first handler, whereas a following `catch` is; I don't know what the rationale was for promises to be designed that way, but it's how promises are. Additionally, if there had been multiple `then`s for some reason, only a single final `.catch(done)` would be needed, which is a point of superiority over try-catch inside the handlers (on top of the fact that `.catch(done)` is boilerplatey to begin with).

As for your API:
1. Are you sure both events are being called, and in the right order? If they were not, how would your test turn that into a normal failure?
2. What normally happens to exceptions that are thrown from your event handlers? If they don't propagate out the way they do in synchronous code and instead are meant to be listened for on the API (e.g. with `.on("error", function(error) {...})`), then they'll never reach Mocha unless you listen for them and have the listener call `done` with the error (or just use `done` with the listener if the listener is passed the error as its first parameter, e.g. `.on("error", done)`. Presumably that would also only need to be written once per test, rather than once per event handler, like `.catch(done)` in a promise.

**Comment by stevenvachon** [comment]
1. Yes, and I use an `"end"`/`"drain"` event to check if booleans in the other events were set.
2. The timeout happens. I'm trying to find a lean and clean alternative.

**Comment by ScottFreeCode** [comment]
Sorry, I still don't know how your API is supposed to report errors.

**Comment by stevenvachon** [comment]
Yeah, so far I've just been relying on the timeouts for *when* somethings fails, then manually digging to find out *how*. Fortunately, things rarely break, but that's not an excuse for the lack of a better design.

**Comment by lsphillips** [comment]
@stevenvachon: Forgive me in advance, but I don't see an immediate issue with your example. The assertions made in your event handlers should be handled by Mocha via the `uncaughtException` mapping (unless the event emitter implementation is catching listener errors and emitting an `error` event or something, which then is easy to solve).

Now if your implementation under the hood is using Promises, but emits events rather than exposes the Promise, your assertions will indeed be "eaten". The way I get around this problem is to use `unhandledRejection`.

I usually put this in a setup script that is run before my tests:

``` js
process.on('unhandledRejection', function (reason)
{
	throw reason;
});
```

I hope to to see Mocha support this like it does `uncaughtException` as this is a common use case; just because I use Promises doesn't mean I want to return them to the caller. Express middleware is a good example of this; where the solution I see is to have middleware return the promise just to get tests to work. This is a terrible approach in my opinion, as my tests require the implementation to use promises even though the tests are only asserting the provided request and response object.

**Comment by monolithed** [comment]
Having the same issue  with mocha@3.1.2

```js
	it('Convert files into base64', (resolve) => {
		let files = Promise.all(promises);

		return files
			.then(([actual, expected]) => {
				assert.equal(actual, expected, 'Files not are equal');
				resolve();
			})
			.catch(error => resolve);
	});
```

```
   Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by ScottFreeCode** [comment]
The `.catch` is wrong. `error => resolve` is equivalent to `function(error) { return resolve }`, which means `resolve` won't be called and the error is ignored. What you want is to call `resolve` with the error, which would be `error => resolve(error)`. Of course, passing a callback function `X` that simply calls function `Y` with the same arguments that `X` is called with is equivalent to just passing `Y` as the callback, so even `.catch(error => resolve(error))` could be simplified to `.catch(resolve)`. (You would only need to not pass `resolve` directly if you were passing it to `then` and, therefore, needed to avoid passing `then`'s result parameter to `resolve` to prevent it being treated as an error: `then(()=>resolve())` rather than just `.then(resolve)`; but since you are using the `then` callback for the assertions, this doesn't come up.)

(Also, idiomatically, `resolve` here should probably be named something along the lines of `done`, since it handles both success and failure and judges which is which based on whether it was called with an argument or not. Hence the name in Mocha's error message. But that may be a moot point; read on.)

However, in this case you can simplify it even further by just returning the promise and not using the test done parameter at all, since Mocha will wait for the promise to succeed or fail as indicating test success or failure (provided there's no done parameter to the test function; behavior in the event both are used is still being hashed out):
```js
it('Convert files into base64', () => {
    let files = Promise.all(promises);
    return files
        .then(([actual, expected]) => {
            assert.equal(actual, expected, 'Files not are equal');
        })
});
```

**Comment by stevenvachon** [comment]
@lsphillips that works for me. Thanks!! I hope to see mocha support this by default too.

**Comment by mattstabeler** [comment]
Took me a while to work this out! Based on [answers](https://github.com/mochajs/mocha/issues/1128#issuecomment-38035865) [above](https://github.com/mochajs/mocha/issues/1128#issuecomment-133105390), these are the two options:

`npm install --save mocha expect.js q`
`./node_modules/mocha/bin/mocha test.spec.js`

```js
// test.spec.js

var $q = require('q');
var expect = require('expect.js');

describe('tests with done', function(){
    it('returns the correct value from promise', function(done) {
      var returnValue = 5;
      var def = $q.defer();
      def.promise.then((val) => {
        expect(val).to.equal(42);
        done();
      }).catch(done);
      def.resolve(returnValue)
    });
})

describe('tests returning promises', function(){
    it('returns the correct value from promise', function() {
      var returnValue = 5;
      var def = $q.defer();
      def.resolve(returnValue)
      return def.promise.then((val) => {
        expect(val).to.equal(42);
      });
    });
})
```
```shell

tests with done
    1) returns the correct value from promise

  tests returning promises
    2) returns the correct value from promise


  0 passing (15ms)
  2 failing

  1) tests with done returns the correct value from promise:
     Error: expected 5 to equal 42
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.be.Assertion.equal (node_modules/expect.js/index.js:216:10)
      at def.promise.then (tests/test.spec.js:9:24)
      at _fulfilled (node_modules/q/q.js:854:54)
      at self.promiseDispatch.done (node_modules/q/q.js:883:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:816:13)
      at node_modules/q/q.js:570:49
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  2) tests returning promises returns the correct value from promise:
     Error: expected 5 to equal 42
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.be.Assertion.equal (node_modules/expect.js/index.js:216:10)
      at def.promise.then (tests/test.spec.js:22:24)
      at _fulfilled (node_modules/q/q.js:854:54)
      at self.promiseDispatch.done (node_modules/q/q.js:883:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:816:13)
      at node_modules/q/q.js:570:49
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by RuchitaGarde** [comment]
@gurdiga Thanks for the setTimeout() idea! I had a similar problem, but now I can get proper error messages atleast!

**Comment by itumoraes** [comment]
In my scenario I used Nightmare to end2end tests. The solution for me was use `.catch(done)`.  You can call `done(error)` inside other catch callback like the example below.

```js
describe('Clicking in any bad reputation tag', () => {
    it('open the bad reputation modal', (done) => {
      nightmare
        .select('#per-page', '50')
        .waitForAjax()
        .click('[data-reputation="bad"]')
        .evaluate(function() {
          return document.querySelector('.vue-modal .ls-modal-title').innerText
        })
        .then(function(title) {
          title.should.equal('Sua segmentação teve uma avaliação ruim!')
          done()
        })
        .catch((error) => {
          screenshot(nightmare)
          done(error)
        })
    })
  })
```

**Comment by vkarpov15** [comment]
@itumoraes that works, but you can do this instead:

```javascript
describe('Clicking in any bad reputation tag', () => {
    it('open the bad reputation modal', () => {
      return nightmare
        .select('#per-page', '50')
        .waitForAjax()
        .click('[data-reputation="bad"]')
        .evaluate(function() {
          return document.querySelector('.vue-modal .ls-modal-title').innerText
        })
        .then(function(title) {
          title.should.equal('Sua segmentação teve uma avaliação ruim!')
        })
    })
  })
```

You don't need to call `done()` if you return a promise. See my blog post [Using Async/Await with Mocha, Express, and Mongoose](http://thecodebarbarian.com/using-async-await-with-mocha-express-and-mongoose)

**Comment by selvakumar1994** [comment]
i used the below script but i got the same Timeout exceed error.

Myscript :

describe("getBillingDetail", async function (){
this.timeout(55000);
it.only("check given valid Jobname",async function (done){
this.timeout(55000);
var result = await url.getBillingDetail('12254785565647858');
console.log(result);
assert.equal(result,true);
});
});

Error: Timeout of 55000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by Munter** [comment]
Stop spelling the same thing in multiple closed issues. Don't pass a done callback into async functions. Read the documentation on async tests

**Comment by selvakumar1994** [comment]
@Munter  i removed  the done callback,but these error is occur again

**Comment by outsideris** [comment]
It looks like that your promise never resovled.

**Comment by hexmarkrecords** [comment]
> @stevenvachon: Forgive me in advance, but I don't see an immediate issue with your example. The assertions made in your event listeners should be handled by Mocha via the `uncaughtException` mapping (unless the event emitter implementation is catching listener errors and emitting an `error` event or something, which then is still easy to solve).
> 
> Now if your implementation under the hood is using Promises, but emits events rather than exposes the Promise, your assertions will indeed be "eaten". The way I get around this problem is to use `unhandledRejection`.
> 
> I usually put this in a setup script that is run before my tests:
> 
> ```js
> process.on('unhandledRejection', function (reason)
> {
>     throw reason;
> });
> ```
> 
> **Note:** This may need some extra elbow grease to work in browsers.
> 
> I hope to to see Mocha support this like it does `uncaughtException` as this is a common use case; just because I use Promises doesn't mean I want to return them to the caller!

this is a nice solution. thanks

**Comment by enjikaka** [comment]
I just had issues with this as well;

```
it('test', async () => {
      await foreignPromise();
      const result = true;
      console.log(result);
      expect(result).to.equal(true);
      console.log('postexpect');
  });
```

would timeout with `Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves` and print `true, postexpect`. Looks like mocha can't understand this.

Wrapping it in a normal function and returning the async function/promise instead worked:

```
it('test', () => {
   return async () => {
      await foreignPromise();
      const result = true;
      console.log(result);
      expect(result).to.equal(true);
      console.log('postexpect');
  }
});
```

**Comment by ticapix** [comment]
> @stevenvachon: Forgive me in advance, but I don't see an immediate issue with your example. The assertions made in your event listeners should be handled by Mocha via the `uncaughtException` mapping (unless the event emitter implementation is catching listener errors and emitting an `error` event or something, which then is still easy to solve).
> 
> Now if your implementation under the hood is using Promises, but emits events rather than exposes the Promise, your assertions will indeed be "eaten". The way I get around this problem is to use `unhandledRejection`.
> 
> I usually put this in a setup script that is run before my tests:
> 
> ```js
> process.on('unhandledRejection', function (reason)
> {
>     throw reason;
> });
> ```
> 
> **Note:** This may need some extra elbow grease to work in browsers.
> 
> I hope to to see Mocha support this like it does `uncaughtException` as this is a common use case; just because I use Promises doesn't mean I want to return them to the caller!

Perfect for async/await and express !
Thank you
