### ISSUE TITLE
watch needs to be debounced

### ISSUE THREAD

**Issue by simon-lang** [mochajs/mocha#1167]
say you git checkout/merge/stash/bisect or some other operation that changes multiple files at once then mocha -w seems to rerun once per file change (with odd results - see attached image).

It would be great if there was say a 200ms debounce/throttle or something that only caused the tests to rerun once.

![screen shot 2014-03-25 at tuesday 25 march 2014 10 42 33 am](https://f.cloud.github.com/assets/339630/2507231/70a50e1e-b3b6-11e3-8cd8-b4df779255d5.png)

**Comment by zbigg** [comment]
Looks like current mocha:
```
npx mocha -version
6.1.4
```
again suffers from this issue.

Looking at `https://github.com/mochajs/mocha/blob/master/lib/cli/run-helpers.js#L270`, `mocha --watch` doesn't have any _debounce_ machanism builtin.

Should we reopen this issue ?

**Comment by shelbykauth** [comment]
Please reopen this issue.  Sometimes I make rapid changes to many files manually and I save just because that's what you _do_ when you're typing.  It's bad enough when it's limited by how fast I type and save.  When I switch between dev and the current feature, or between my feature and a feature I'm reviewing, or try to rebase, I can't even hit ctrl+c in my mocha-running terminal fast enough to keep my computer from slowing down and making the rebase or the switch take up to 10 seconds because mocha's over there re-running all 200 unit tests I'm looking at.

I'm using mocha version 8.2.1
