### ISSUE TITLE
Mocha --require option only available through cli?

### ISSUE THREAD

**Issue by DylanPiercey** [mochajs/mocha#1479]
Is it possible to access the require option through the programmatic api?

ie:

``` JavaScript
var Mocha = require('mocha');

new Mocha({
    require: ['should']
}).run(...)
```

**Comment by TylorS** [comment]
Any plans to implement this? I'm also working on my own project that uses the programmatic API.

**Comment by gurdiga** [comment]
@TylorS Could you please give a bit of background around your use-case? Maybe this would hint an implementation idea or an acceptable work-around. 🤓

**Comment by TylorS** [comment]
Hi @gurdiga I'd love to share my use-case. I'm working on a project that makes it easy to start new node/npm projects with virtually 0 configuration. Its very much at the proof of concept level of things. It works by using plugins to configure your needs. 

At the moment I only have a mocha plugin with some basic plugins to augment mocha. Each plugin for mocha receives a mocha instance and as a workaround to this issue its passed `require()` from the same scope as the mocha instance. You can see it [here](https://github.com/TylorS/bubbleup-plugin-test-mocha/blob/master/bubbleup-plugin-test-mocha/index.js#L50). I'm not a fan of the require hack, and would love to be able to do something more 'official' like `mocha.register()` if technically feasible.

Please let me know if there is any more information I can provide to make things more clear or how I can help in any way.

Anyways here is a link to it if you're interested https://gihtub.com/TylorS/bubbleup and a basic example of the test functionality which uses mocha, [buba](https://github.com/davidchase/buba) (a babel-register alternative), and istanbul  https://github.com/TylorS/bubbleup-test-example.

**Comment by gurdiga** [comment]
Hey @TylorS, 🙂

It looks like Mocha’s CLI code [is employing the “require hack” too](https://github.com/mochajs/mocha/blob/master/bin/_mocha#L309-L311): I mean it’s just collecting a list of names/paths to later just `require` them. 🤓 

I’ve paused then because I didn’t know what to make of it. 🙃  — Then I’ve re-read the [documentation](http://mochajs.org/#r---require-module-name) for the `--require` option and it says:

> Note that this works well for should as it augments `Object.prototype`, however if you wish to access a module’s exports you will have to require them, for example `var should = require('should')`.

So it seems it was not meant to be part of the Mocha core, and is consequently why it only lives in the CLI code. I guess this means there will be resistance to implementing it as part of the programatic API, but this is only my guess as an outsider.

Now, if `bubbleup-plugin-test-mocha` will need to access the modules’ exports — which is not offered by the Mocha CLI’s implementation — I would probably consider implementing your own mechanism in `bubbleup`. 🤓  And if I think about it, it seems to me that a tool like `bubbleup` is a better home for this kind of functionality than Mocha — a testing tool — is. 🤔

I’m not sure I have helped, but this is all I have. 😊

**Comment by TylorS** [comment]
Thank you @gurdiga for taking the time to investigate this. I simply mean to use it for things like `babel-register` which allow writing tests in ES6+. I'm not sure if that makes any difference.

I feel better about the solution I have come to now after seeing that mocha also uses my "require hack".

Thank you very much for your time :)

**Comment by alessandrofrancesconi** [comment]
Hello, I was looking for this feature too and I came to this discussion. My situation is that I have a main script, call it "runner", that instantiates Mocha programmatically and use addFile() function to add unit test files that are located in different places on the file system.
All of these files use Chai Assertion Library and I would avoid to add require("chai") on every one of them. Also, for many reasons, I have to install Chai locally on every path of the unit test and this is not so convenient.

At the end, the "require" option on Mocha can be the solution. I'm relatively new on NodeJs so maybe @TylorS could explain me his hack... or I'll just wait for someone to let us use require option programmatically.

**Comment by TylorS** [comment]
Hello @alessandrofrancesconi This is only off the top of my head, as I only did this one time. It ended up looking something like this

```js
const Mocha = require('mocha')

const mocha = new Mocha()

require('babel-core/register') // for instance, needs to be done *before* you call addFile

testFiles.forEach(file => {
  mocha.addFile(file)
})

mocha.run()
```

I hope this helps!

**Comment by alessandrofrancesconi** [comment]
Mh, I'm not seeing any improvement. Here is an example:

Main file with Mocha initialization:

```
// initialize Mocha test framework
var Mocha = require("mocha");
var runner = new Mocha(
{
    ui: "bdd"
});

require("chai");     // I put here the modules needed by external files
require("sleep");

// process all test scripts in path
var fsFiles = fs.readdirSync(args.path);
fsFiles.forEach(function(f) 
{
    runner.addFile(path.join(args.path, f));
});

// run mocha
runner.run();
```

And here is an example of file loaded with addFile()

```
describe("Initialization test", function () {
    it("shall initialize without errors", function () {
        chai.expect(0).to.be.below(1, "it works");
    });
});
```

Here, "chai" is not defined

**Comment by TylorS** [comment]
Oh, I don't know how that example would work. I don't think that `--require` works that way at all? (Someone please correct me if I'm wrong). 

In my example this workaround happens to work, because `babel-core/register` mutates the way the following `.js` files are `require()`d. I can't see how you'd be able to add anything globally without doing so yourself.

```diff
-require("chai");
-require("sleep");

global.chai = require('chai');
global.sleep = require('sleep');
```

**Comment by alessandrofrancesconi** [comment]
You're right, now it works 👍

**Comment by TylorS** [comment]
Glad that I could help @alessandrofrancesconi

**Comment by drazisil** [comment]
Question answered and resolved.
