### ISSUE TITLE
Is it possible to access the test instance `done` in the `beforeEach`?

### ISSUE THREAD

**Issue by dickeylth** [mochajs/mocha#1502]
I've read that [Expose current test information to beforeEach #794](https://github.com/mochajs/mocha/issues/794), however when I access `this.currentTest.fn.arguments`, it turned out to be `null`, not `done`, in my code I used [spooky](https://github.com/WaterfallEngineering/SpookyJS) for automatic test, and I need to bind test case `done` with spooky's `run.complete` event. So in order to handy bind the `done` method in every test case, I tried to make the bind in the `beforeEach`, so this is the situation, is it possible to access the test instance `done` in the `beforeEach`?

```
describe('xxx', function() {

		beforeEach(function(done){
			var itDone = this.currentTest.fn.arguments[0];
			// error: this.currentTest.fn.arguments == null
			done();
		});

		it('should open calendar', function (done) {

			var self = this;
			self.ok = true;

		});


		it('should return a 200 OK status', function(done) {

			var self = this;
			self.ok = true;

			//context.spooky.beforeTest(self, done);

			context.spooky.then(function() {

				// casper API
				this.test.assertHttpStatus(200, 'successfully received 200 OK');

			});

			context.spooky.run(function() {
				this.test.done();
			});
		});
	});
```

Thank you!

**Comment by blenderer** [comment]
I'm also experiencing this. I took from this example: https://github.com/mochajs/mocha/wiki/Shared-Behaviours
(works fine)

then I added in a done() callback to the beforeEach.
https://gist.github.com/blenderer/27a4ce8ff6380af8d90a
(fails: this.user is undefined)

**Comment by danielstjules** [comment]
Hi @dickeylth, your example doesn't work as the test function hasn't yet been invoked, so no arguments have been passed or resolved. For example:

``` javascript
$ node
> var example = function(done) { done(); };
undefined
> example.arguments
null
```

You can't access the `done` callback function from a hook since it's not created until the Runner actually invokes/runs the runnable: https://github.com/mochajs/mocha/blob/master/lib/runnable.js#L192

I'm gonna close this since it's been a couple months, and you may have found a better solution to handling spooky tests :)
