### ISSUE TITLE
Ensure done() is being called within tests

### ISSUE THREAD

**Issue by Soviut** [mochajs/mocha#1524]
As was discussed in https://github.com/mochajs/mocha/issues/1503 it would be good to scan each test to make sure the `done()` callback is actually called. An appropriate error should be thrown if the callback is missing.

For background, forgetting to add `done()` results in a somewhat ambiguous timeout error on a test, this would make things more specific and easier to debug.

**Comment by scott2449** [comment]
@dasilvacontin @Soviut don't forget to check for a returned promise in that case as well :+1:

**Comment by dasilvacontin** [comment]
Do people define a `done` callback if a Promise is returned?

**Comment by scott2449** [comment]
no no no I'm just noting a reminder to make sure the pretty error is only throw if no done AND no promise. I can imagine someone submitting a PR who's not a promise person and releasing a bugged version not even realizing it :smile: I know that's something I would do ...

**Comment by dasilvacontin** [comment]
I know, thanks for the heads up! :)

**Comment by JohnnyEstilles** [comment]
While preparing a PR for this issue I realized that I had introduced a breaking change. Specifically the "[should allow updating the timeout](https://github.com/mochajs/mocha/blob/master/test/runnable.js#L282-L297)" test in [test/runnable.js](https://github.com/mochajs/mocha/blob/master/test/runnable.js).

As suggested by @Soviut, my implementation returns an "appropriate error" when the test does not invoke the callback, instead of timing out (see spec below). However, in order not to introduce a breaking change, I enabled the feature ONLY when when timeouts are explicitly disabled (i.e. `mocha --no-timeouts`).

Does this make sense to everyone? If it does, I'll submit my PR. If it doesn't, I'm open to suggestions.

```js
describe('when done() is not invoked', function(){
    it('should return a "not invoked " error', function(done){
        var test = new Runnable('foo', function(done){
            return true; // <-- not calling done()
        });

        test.enableTimeouts(false);

        test.run(function(err){
            err.message.should.equal('done() callback not invoked within test');
            done();
        });
    });
});
```

**Comment by JohnnyEstilles** [comment]
After reading through the [Contributing to Mocha](https://github.com/mochajs/mocha/blob/master/CONTRIBUTING.md) guidelines, I have a feeling my proposed PR will no be accepted. While my implementation would only add a mere 59 LOCs (included test), I've used `esprima` to create an AST of the test function, which in turn I traversed to determine if the callback was invoked within the function.

While `esprima` is not as heavy a dependency as are other Mocha dependencies, such as `jade` and `blob`, I'm sure it will be perceived as bloat, and will like prevent my PR from being loaded. Alternate JavaScript parsers (e.g. `acorn`, `espree`, `parse-js`, etc.) were either larger (not good), or slower (less good).

Given all of this, should I still consider submitting my PR?

**Comment by boneskull** [comment]
@JohnnyEstilles I'd say no thanks (but others may not share my opinion).  We already have a "reminder", so actually enforcing the existence of `done` adds, in my opinion, only a small benefit.

Look at it this way: when you write an API, do you write code that asserts other code that consumes the API is written properly?

This can (and should) be done with a tool designed for this type of thing: [ESLint](http://eslint.org).  I'm sure you can figure something out and publish an ESLint plugin to do it.

Anyone else, feel free to reopen if you disagree

**Comment by boneskull** [comment]
(since @dasilvacontin added `PR-PLEASE` here, I'm sure he'll disagree)

**Comment by JohnnyEstilles** [comment]
@boneskull ... understood. I just figured you guys wanted the feature, since I saw the `PR-PLEASE` tag.

**Comment by JohnnyEstilles** [comment]
@Soviut .. If you're interesting in adding the feature to a personal fork you can get my implementation here: JohnnyEstilles/mocha@e34e13084b1ef5fb20f41ad0689b6df8fd7c175d

**Comment by danielstjules** [comment]
@JohnnyEstilles I like the idea, though I agree with @boneskull that a reminder is both sufficient and more flexible.

About your proposed solution: I don't think parsing the AST is necessary for this, as your use of esprima in https://github.com/JohnnyEstilles/mocha/commit/e34e13084b1ef5fb20f41ad0689b6df8fd7c175d is to check identifiers (nothing JS-specific). The same search could be done without esprima, using Function.prototype.toString() and simple string searches. esprima would only come in handy with parsing the AST for complex edge cases, such as where the callback is aliased, or overwritten. E.g.

``` javascript
it('alias is invoked', function(done) {
  var sneaky = done;
  sneaky();
});

it('alias is not invoked', function(done) {
  someAsyncEvent(function(done) {
    // oops, I overwrote the callback
    done();
  });
});
```

Cases like these don't seem to be handled by your commit, but certainly could be using the AST. But it's probably not worth accommodating given the extra complexity. And again, string searching alone would handle the test case you highlighted in https://github.com/mochajs/mocha/issues/1524#issuecomment-78174107, as well as provide es6 support. Since unfortunately, esprima wouldn't work well for anyone using harmony features. That's where acorn shines, though that's another large dependency. :)

**Comment by JohnnyEstilles** [comment]
@danielstjules, you're absolutely correct. I used AST because I intended to search for more complex edge cases like the ones you suggested (long with several others), but I didn't want to continue work on the PR if there was no interest. I understood this was a long shot, but again, I just wanted to pitch in since I saw the `PR PLEASE` sign on the door. :-) I'm sure there will be other opportunities.

**Comment by boneskull** [comment]
@JohnnyEstilles Sorry about that.  I'll let @dasilvacontin comment

**Comment by boneskull** [comment]
@JohnnyEstilles If you *do* end up writing an ESLint plugin instead (note that ESLint supports lots of Harmony features), it could also likely be used for Jasmine, which would make it doubly useful.

**Comment by JohnnyEstilles** [comment]
@boneskull, no worries. I will likely develop an ESLing plugin. When I do, I'll share it for those who might be interested. :-)
