### ISSUE TITLE
mocha.opts does not support --harmony

### ISSUE THREAD

**Issue by MatthewMueller** [mochajs/mocha#1573]
If you run `mocha --harmony` that works fine, but placing `--harmony` in `mocha.opts` doesn't seem to work.

**Comment by fixe** [comment]
nvm install iojs :-)

**Comment by raine** [comment]
:+1:

**Comment by lloydcotten** [comment]
This is all well and good - but you also broke the ability to use mocha.opts when invoking _mocha directly.  Using _mocha directly is needed when running things like [istanbul](/gotwarlost/istanbul).

Is this intentional?  If so, do you have any more elegant suggestions (besides not using mocha.opts or doing the readFileSync / trim / split / filter bit in our own wrapper script?)

Thanks!
