### ISSUE TITLE
Do not hard code err instanceof Error checks

### ISSUE THREAD

**Issue by brian-mann** [mochajs/mocha#1627]
Specifically this line: https://github.com/mochajs/mocha/blob/master/lib/runner.js#L205

Long story short, `err` may be a valid `Error` instance but in situations such as `iframes` each `window` will have its own `Error` object, and this will therefore always always fail.

I would suggest taking after what lodash does in its `isError` function.

It just ensures its "object like", has a string for message property, and is [object Error]

```javascript
//lodash isError implementation
function isError(value) {
  return (isObjectLike(value) && typeof value.message == 'string' && objToString.call(value) == errorTag) || false;
}
```

**Comment by danielstjules** [comment]
Good idea! We wouldn't be able to use lodash's implementation out of the box because of how pending tests are defined and propagated up to the runner/runnables. https://github.com/mochajs/mocha/blob/master/lib/pending.js If I recall correctly, there's cases where the instance of Pending will have an undefined message. That logic will need to be tweaked a bit.

**Comment by brian-mann** [comment]
Just as another reference, in other parts of Mocha, specifically here: https://github.com/mochajs/mocha/blob/master/lib/runnable.js#L234

Mocha already toStrings() the object as a fallback to the `instanceof` checks.  That's all that's needed IMO.

**Comment by outdooricon** [comment]
See https://github.com/mochajs/mocha/pull/1758 for related PR.

**Comment by outdooricon** [comment]
@brian-mann, does that pr solve what you're looking for? The object toString method that you mentioned doesn't work because it can still return something other than `[object Object]`, as it does for AssertionError. 

@danielstjules I don't think checking for error message is a problem here. Pending doesn't appear to be an instance of Error, so it should continue to work as implemented if a Pending object does indeed reach this.

**Comment by outdooricon** [comment]
@boneskull I think we can remove the pr-please label at this point.

**Comment by danielstjules** [comment]
> so it should continue to work as implemented if a Pending object does indeed reach this.

Good point :) Not sure what I was thinking

**Comment by danielstjules** [comment]
Closed by https://github.com/mochajs/mocha/pull/1758
