### ISSUE TITLE
deepEqual does not descriminate by type

### ISSUE THREAD

**Issue by chrisdew** [mochajs/mocha#1685]
`assert.deepEqual({foo:10}, {foo:'10'});` returns `true`.

**Comment by dasilvacontin** [comment]
Hi! This isn't related to mocha. However:

That's how `assert`'s `deepEqual` works, it uses `==`.

You could use `chai`'s `expect`. It has a `deep` flag, and `equal` uses `===`:

```js
var expect = require('chai').expect
expect({foo:10}).to.deep.equal({foo:'10'}) // AssertionError: expected { foo: 10 } to deeply equal { foo: '10' }
```

docs: http://chaijs.com/api/bdd/#deep-section

**Comment by twada** [comment]
FYI: io.js has introduced a `deepStrictEqual()` method to mirror `deepEqual()` but performs strict equality checks on primitives since io.js 1.2.0.

see also:
- [assert.deepStrictEqual(actual, expected[, message])](https://iojs.org/api/assert.html#assert_assert_deepstrictequal_actual_expected_message)
- [io.js/CHANGELOG.md at master · iojs/io.js](https://github.com/iojs/io.js/blob/master/CHANGELOG.md#2015-02-10-version-120-rvagg)
- [assert: introduce `deepStrictEqual` by vkurchatkin · Pull Request #639 · iojs/io.js](https://github.com/iojs/io.js/pull/639)

**Comment by chrisdew** [comment]
Thanks for all your help.

**Comment by dasilvacontin** [comment]
Awesome, thanks for sharing @twada!

**Comment by Anil-Panghal-Landmark** [comment]
Facing error 'Doc Type is visa | AssertionError: expected undefined to deeply equal 'visa' for following.'
pm.test("Doc Type is visa", function (){
        pm.expect(data.documentTypes[5]).to.have.property('documentType');
        pm.expect(data.documentType).to.eql('visa');
});
pm.test("scanType is basic", function () {
    pm.test(data.documentTypes[5]).to.have.property('scanType'); 
    pm.test(data.documentTypes[5]).to.have.property('supported');
    pm.expect(data.scanType).to.contains('basic');
    pm.expect(data.supported).to.eql('false');
   });
   pm.test("scanType is basic_selfie", function () {
    pm.test(data.documentTypes[5]).to.have.property('scanType'); 
    pm.test(data.documentTypes[5]).to.have.property('supported');
    pm.expect(data.scanType).to.contains('basic_selfie');
    pm.expect(data.supported).to.eql('false');
   });
    pm.test("scanType is enhanced", function () {
    pm.test(data.documentTypes[5]).to.have.property('scanType'); 
    pm.test(data.documentTypes[5]).to.have.property('supported');
    pm.expect(data.scanType).to.contains('enhanced');
    pm.expect(data.supported).to.eql('false');
   });
