### ISSUE TITLE
html reporter link to specific test is broken on some special characters

### ISSUE THREAD

**Issue by amir-arad** [mochajs/mocha#1687]
If the test title contains some special characters (for instance $ or () ) then its link in the HTML report does not work.

IMO the fix should be escaping regex [here](https://github.com/mochajs/mocha/blob/908d8dbe15b5ef5f4a5658f6cc870bf563e80717/lib/reporters/html.js#L192) before calling encodeURIComponent(s)

**Comment by benvinegar** [comment]
I can reproduce the bug.

Digging deeper, the issue is caused because the `grep` query string argument is passed verbatim into the `RegExp` constructor, [here](https://github.com/mochajs/mocha/blob/master/support/tail.js):

```javascript
if (query.grep) mocha.grep(new RegExp(query.grep));
```

Because the grep argument isn't escaped, it produces regex objects like:

```javascript
/test that $.jQuery works/
```
Which of course don't work.

Patch incoming.

**Comment by benvinegar** [comment]
My bad. I had this backwards. `--grep` expects an escaped regex string ... so @amir-arad has it correctly.

**Comment by kevinb7** [comment]
I'm on an 1.21.4 and would like to upgrade.  I tried upgrading to the current 2.2.5 and encountered this issue immediately b/c all of our tests have ```(version 4)``` to indicate the version of the build system.  It makes it hard to investigate individual test failures.

**Comment by dasilvacontin** [comment]
@kevinb7, could you try @benvinegar's patch?
