### ISSUE TITLE
xunit reporter broken

### ISSUE THREAD

**Issue by michaeljs1990** [mochajs/mocha#1820]
```
express deprecated res.sendfile: Use res.sendFile instead test/res.sendFile.js:627:15
express deprecated res.sendfile: Use res.sendFile instead test/res.sendFile.js:643:15
express deprecated res.sendfile: Use res.sendFile instead test/res.sendFile.js:655:15
express deprecated res.sendfile: Use res.sendFile instead test/res.sendFile.js:667:15
express deprecated res.sendfile: Use res.sendFile instead test/res.sendFile.js:680:15
express deprecated res.sendfile: Use res.sendFile instead test/res.sendFile.js:707:17
express deprecated res.vary(): Provide a field name test/res.vary.js:12:13
express deprecated res.vary(): Provide a field name test/res.vary.js:28:13
express deprecated utils.flatten: use array-flatten npm module instead test/utils.js:92:11
<testsuite name="Mocha Tests" tests="678" failures="0" errors="0" skipped="0" timestamp="Wed, 29 Jul 2015 18:58:44 GMT" time="1.859">
<testcase classname="Route .all" name="should add handler" time="0.002"/>
<testcase classname="Route .all" name="should handle VERBS" time="0.005"/>
<testcase classname="Route .all" name="should stack" time="0.001"/>
```

here is a small example when you use the xunit reporter on the express framework. I believe that the deprecated warning should also be part of xunit or removed since it breaks the output.

**Comment by boneskull** [comment]
the only way around this would be to trap all output from your code itself, and restrict the output to that which the reporter emits. For most reporters this is undesirable, but for those intended to be machine-readable, it should probably be done, unless I'm missing something. 

Also, I'm not really sure how to do this safely. Since the tests aren't run in a subprocess or sandbox, it'd be a matter of stubbing and un-stubbing `console`. 

Your other option is to complain to `express` that the warning should be printed to `stderr` instead.

**Comment by michaeljs1990** [comment]
@boneskull sounds good to me I don't want to invest a ton of time in it so I turned of deprecation warning for right now so I can get it integrated with my jenkins server.
