### ISSUE TITLE
update deps

### ISSUE THREAD

**Issue by thepian** [mochajs/mocha#1844]
It seems that several dependencies are outdated

When upgrading outdated on our project mocha blows up because it uses an old commander dependency that causes

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.

**Comment by listepo** [comment]
+1

**Comment by segrey** [comment]
Another dependency that needs to be updates is `support-colors`. As of now, its version is set to `1.2.0`. However, versions `supports-color@0.2.0` or later contain fix for https://github.com/chalk/supports-color/issues/13 that allows to enable ANSI colors using `FORCE_COLOR` environment variable. It's a useful feature for IDE integrations. Unfortunately, now it's impossible to enable ANSI colors forcibly in mocha tests being run in IDE, because the only way to do so is to pass `--color` cli option that is rejected by mocha as:
```
error: unknown option `--color'
```

**Comment by boneskull** [comment]
I'm not sure the best way to do this.  We aren't going to be updating to any package which is incompatible with npm < 1.3.7 before Mocha 3.  I don't know which dependencies, or which dependencies thereof, are going to be incompatible.

**Comment by segrey** [comment]
Make sense. Waiting for Mocha 3 then.

**Comment by myhere** [comment]
+1  `surpports-color`

**Comment by flying-sheep** [comment]
supports-color is very simple. what makes a package incompatible with npm < 1.3.7?

it’s a bit annoying that everything except for mocha supports `FORCE_COLOR`

**Comment by detj** [comment]
`lodash.create@3.1.1` is another one. npm throws the following warning on `npm install`

```
npm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
```

Looks like `lodash.isarray` is a dep of `lodash.keys` which is a dep of `lodash.create`

**Comment by graingert** [comment]
this PR is super out of date now

**Comment by graingert** [comment]
@boneskull ?

**Comment by boneskull** [comment]
@graingert #3024
