### ISSUE TITLE
Observables

### ISSUE THREAD

**Issue by thejameskyle** [mochajs/mocha#1898]
So there's this cool thing called `Observable`s that is (likely) coming to the language soon ([ref 1](https://github.com/zenparsing/es-observable), [ref 2](https://github.com/tc39/ecma262)).

They are similar to promises in a number of ways.
- They both attempt to deal with asynchronous actions in a reasonable manner.
- They both define a standard interface that can be implemented and extended by third parties.

Since Mocha supports returning promises in order to avoid using the `done` callback, it'd be nice if it did the same thing with observables:

``` js
it('should do something with an Observable', () => {
  return Observable.of(1, 2, 3).subscribe(...);
});
```

People are already using these with http://reactivex.io/.

cc @blesh

**Comment by thejameskyle** [comment]
Side note: Gulp is doing the [same thing](https://github.com/gulpjs/gulp/blob/4.0/docs/API.md#return-a-rxjs-observable) with Observables in 4.0.

**Comment by blesh** [comment]
One temporary solution for RxJS Next/5 is to use `forEach` rather than subscribe, as it returns a promise. But it's not ideal.

**Comment by mAAdhaTTah** [comment]
Is this something Mocha would accept a PR on?

**Comment by ScottFreeCode** [comment]
I'm not yet familiar with how observables are implemented under the hood, so I want to check one thing: would this interfere with making generator test functions be failures, if the latter were implemented by checking for `typeof (<result> && <result>.next) === 'function'` on the test return value?

Obviously, handling generators (even as automatic failures*) and handling observables can be two separate enhancements; I just want to make sure that by deciding to add either one we aren't closing off the ability to decide for or against the other.

*(In case the rationale makes this any clearer, I've come part way around on my thinking in this regard since it was last discussed: I'm still not so sure we would want Mocha to assume that the promise-unwrapping generator wrapper behavior is the one that should be default-associated with tests, but I see enough usefulness in such wrappings -- for Selenium especially -- that I think passing the test if somebody forgets the wrapper is unhelpful, _and_ I think checking for the `.next` function on the returned object should be a safe enough way to do it without losing any browser support... but I suppose I should dig up the old issue on that and present my updated thoughts there.)

**Comment by mAAdhaTTah** [comment]
@ScottFreeCode For the PR I opened (#2722) I used `symbol-observable`, as that seems to be the consensus in the community for observable interop. If the return value has that set, we can use that to determine if we should consume the observable. Because it uses a completely different mechanism, it doesn't have any impact on support generators later.
