### ISSUE TITLE
--sort option for mocha.run

### ISSUE THREAD

**Issue by chrisskilton** [mochajs/mocha#1903]
Hi,

It looks like --sort is only picked up in `_mocha`, is there a plan to make these run options available to mocha in the browser? Specifically being able to pass `sort: true` into `mocha.setup` or adding it to the `mocha.options` object would be nice.

**Comment by chrisskilton** [comment]
No response on this. If I've missed something obvious please say!

Locally I added a workaround:

```javascript
if (options.sort) {
    suite.suites = suite.suites.sort(function(a, b) {
      var aTitle = a.title.toLowerCase();
      var bTitle = b.title.toLowerCase();

      if(aTitle > bTitle) return 1;
      if(aTitle < bTitle) return -1;

      return 0;
    });
  }
```

To get the browser tests to run alphabetically. Is there already a way to achieve this that I'm not seeing?

**Comment by albertlockett** [comment]
This worked like a charm! thanks @chrisskilton

**Comment by ScottFreeCode** [comment]
Hmm; the reason `--sort` is not available in the browser is that, if I'm reading the code correctly, it sorts the files rather than the tests themselves -- so, whatever you do to include the files in the browser would have to be sorted, and that's outside of Mocha's control. I don't know that there's actually an option to sort the suites/tests instead of the files, although there is work in progress on adding an option to randomize them (since most tests should not depend on ordering).

**Comment by juergba** [comment]
`--sort` is a command line option for use with Node. There are no plans to add a similar functionality to the browser.
