### ISSUE TITLE
Feature to enhance async flow

### ISSUE THREAD

**Issue by zensh** [mochajs/mocha#1918]
I would like to create a PR to enhance async flow, it will let mocha support all async mode with good back compatibility.

**After PR, mocha support:**
```js
// backward compatibility for old callback style!
it('test1', function(done) {
  // do some test
  done()
})

// backward compatibility for simple sync test!
it('test2', function() {
  // do some test
})

// support generator
it('test3', function*() {
  // do some test
  // yield promise
  // yield thunk
  // yield generator
  // ...
})

// support promise
it('test4', function() {
  // do some test
  return promiseLikeObject
})

// another way with thunk function
it('test5', function() {
  // do some test
  return thunkFunction
})
```

It only need a little changes like as https://github.com/zensh/mocha/commit/b963f6fadef8e3ad4ff603fc74831a30180209d1, and some changes in test cases(some about "sync" asserts).

Would you guys like this PR?

**Comment by danielstjules** [comment]
Hi @zensh, this was already proposed in https://github.com/mochajs/mocha/pull/1575

**Comment by zensh** [comment]
@danielstjules It is a different PR that good at backward compatibility

**Comment by zensh** [comment]
It will support async/await too

**Comment by danielstjules** [comment]
> @danielstjules It is a different PR that good at backward compatibility

The issue wasn't backwards compatibility. The PR I listed was also backwards compatible with the existing API. :) For compatibility with node 0.8 and 0.6 (which don't support harmony GeneratorFunctions), it just would have needed `co` be listed under npm `optionalDependencies`. 

> It will support async/await too

From what I remember, the team wasn't interested in supporting userland solutions to async/await at the time. And since the async/await spec hasn't been finalized and introduced to V8/node, I don't think the project would take on any sort of transpiring to handle the syntax.

If you'd like coroutine support in your specs, I'd suggest checking out https://github.com/blakeembrey/co-mocha :) I use it myself now.
