### ISSUE TITLE
errors are not logged into stderr

### ISSUE THREAD

**Issue by okv** [mochajs/mocha#1921]
test.js:

``` js
describe('describe', function() {
    it('fails', function() {
        throw new Error('boo');
    });
});
```

mocha 2.0.1 `mocha test.js > /dev/null` produces:

```
  1 failing

  1) describe fails:
     Error: boo
      at Context.<anonymous> (/home/okv/tmp/mocha/test.js:4:9)
      at callFn (/home/okv/tmp/mocha/node_modules/mocha/lib/runnable.js:250:21)
      at Test.Runnable.run (/home/okv/tmp/mocha/node_modules/mocha/lib/runnable.js:243:7)
      at Runner.runTest (/home/okv/tmp/mocha/node_modules/mocha/lib/runner.js:373:10)
      at /home/okv/tmp/mocha/node_modules/mocha/lib/runner.js:451:12
      at next (/home/okv/tmp/mocha/node_modules/mocha/lib/runner.js:298:14)
      at /home/okv/tmp/mocha/node_modules/mocha/lib/runner.js:308:7
      at next (/home/okv/tmp/mocha/node_modules/mocha/lib/runner.js:246:23)
      at Object._onImmediate (/home/okv/tmp/mocha/node_modules/mocha/lib/runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:354:15)
```

Which is correct because stdout data redirected to /dev/null and only stderr data appears at console.

latest mocha (2.3.3) for the same command produces nothing.

**Comment by okv** [comment]
This bug still reproducible with latest mocha (4.0.1).
Is anybody  going to fix it?

**Comment by ScottFreeCode** [comment]
The behavior is well known, but while it shouldn't have been introduced originally in a non-major version, two major versions have passed *and* I don't think it's necessarily obvious that it's a bug:

- Using both stdout and stderr would make it impossible for tests to log to one of them and the report to go to the other and have them be redirected to separate places. (For simple debugging purposes this is a lot easier than pulling down a more complex file-based logger.)
- There's a distinction between unexpected errors that might crash the process or otherwise be logged on stderr and test failures that are part of the report.
- If you only want to see certain output in the test report it's always possible to use a custom reporter. (The fact that the behavior can be customized doesn't by itself justify Mocha's default behavior, but the fact that this is specifically about seeing a different report style *and* that the default behavior has advantages of its own makes the possibility of customizing the style relevant.)

**Comment by Bamieh** [comment]
I am going to close this since this can be resolved using a custom reporter if needed. 

Personally I do not see the benefit of changing our default behavior, especially that it might break some CI implementations in subtle unexpected ways.
