### ISSUE TITLE
Custom reporter and event handling 

### ISSUE THREAD

**Issue by axelssonHakan** [mochajs/mocha#1931]
I'm writing my own reporter and on failure taking a screenshot and saving to disc. **But it seems that the event onEnd doesn't wait for my event onFailure to finish**.

The process ends after on end and my screenshots is never saved to disc.
Tried to push my promises in onFailure to an array and in onEnd use Promise.settle but that doesn't work.

Is there any way of running onEnd first after all other events has finished?

**Comment by jaydlawrence** [comment]
+1
I have a similar problem where I am trying to get a reporter to post the results to testrail, but mocha will not wait for callbacks or promises and just **kills the reporter when the tests end**.

**Comment by mekdev** [comment]
@jaydlawrence  Nice to know there are peeps out there looking to do testrail mocha integration. 

Did you guys have any luck with this ?

**Comment by carsonreinke** [comment]
It does not, I believe it is related to [Process event exit](https://nodejs.org/api/process.html#process_event_exit).  I was able to successfully fork and do some additional work.

**Comment by plroebuck** [comment]
I know `Runner#run` will invoke [end game processing](https://github.com/mochajs/mocha/blob/741c4c794c89f9cf7c590e8c220c8c16162c0465/lib/runner.js#L867-L871). But the reporter's `onEnd` handler should have been registered to run prior to the runner's handler.
After your reporter registers your `end` handler, where does it show up positionally?
```js
runner.listeners('end').forEach(function(func) {
  console.log(func.toString());
});
```
It _can_ be forced to the front using this method instead of `Emitter#on`
```js
runner.prependListener('end', onReporterEnd);
```

@axelssonHakan, @jaydlawrence, @carsonreinke:
Do any of you have code that demonstrates the problem for testing?

**Comment by MartinPilny** [comment]
Hello there, does any of participants have update in this issue? I'm currently trying to write custom reporter to azure devops for Cypress and facing same issue (async HTTP request call at the end of run isn't proceeded).

**Comment by JoshuaKGoldberg** [comment]
This open question has existed for quite a while without a concrete answer. Per #5027 we've moved question-asking to Discord. If you're reading this and interested, please:

1. Search other issues for what you're trying to do
2. Ask there or StackOverflow

Cheers!
