### ISSUE TITLE
Using 'this' as a way to pass context

### ISSUE THREAD

**Issue by madcapnmckay** [mochajs/mocha#1942]
I was wondering whether there was any interest/desire to support this style of testing in mocha. I personally dislike polluting the shared scope and I also like to keep my "it" handlers assertion only if possible. 

https://gist.github.com/traviskaufman/11131303

It seems like allowing "this" to act as the carrier for the scope is the nice middle ground between the two extremes.

**Comment by boneskull** [comment]
At the risk of starting a holy war, using the context object to store arbitrary data is a bad idea:

1. It exposes a public API which a developer could unwittingly befoul 
2. It pollutes the test context. See [this article](https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4) for more info (though I hesitantly link to it)

Using `this` in the manner suggested is not recommended. 

If using the function or lexical scope is problematic, then:

1. Your test files are too big and should be split up, and/or
2. Maybe you should use a namespaces instead of 100 variables

**Comment by boneskull** [comment]
fwiw you can do this to a degree but the suite does not share context with the hooks or tests.

**Comment by travisjeffery** [comment]
Yeah you can already do this actually, but even still I think it's better to rely on the language for this.
