### ISSUE TITLE
Allow providing config to compiler hooks 

### ISSUE THREAD

**Issue by Swaagie** [mochajs/mocha#1943]
Wondering what the best approach is to tackling this issue. For instance, the Babel compiler can be supplied with additional config https://github.com/babel/babel/blob/master/packages/babel/src/api/register/node.js#L213-L227. 

However mocha is currently not taking this into account, https://github.com/mochajs/mocha/blob/master/bin/_mocha#L296. 

Config provided with either `.babelrc` or elsewhere are not supplied to the compiler. Could this be made possible, I'm unsure of implications for other hooks (if any).

**Comment by boneskull** [comment]
I need more information on how you are trying to run Mocha with Babel, as I don't have any problem with it

**Comment by hinok** [comment]
:+1: 

I'm using mocha and babel, tests are fired by command:

```
./node_modules/.bin/mocha app/scripts.babel/**/*Spec.js --compilers js:babel-core/register
```

It works but I got timeouts for some tests and warnings, like:

```
Note: The code generator has deoptimised the styling of /angular/angular.js" as it exceeds the max of "100KB".
```

I googled for a while and found that It can be easily fixed by setting option `compact` to `false` - https://babeljs.io/docs/usage/options/

I don't see anywhere in documentation how to pass options to specified `--compilers` so this is probably the use case for providing config to compilers.
