### ISSUE TITLE
Run tests on globals without exports/imports

### ISSUE THREAD

**Issue by ShMcK** [mochajs/mocha#2034]
I'm writing a program that runs unit tests on user inputted code. The goal is to help users learn to code by verifying their work.

I want to be able to run mocha tests from a separate file without explicitly exporting them. An example:

`/file.js` has no module, no exports, etc. addOne is attached to the global scope.

``` js
function addOne(x) {
    return x + 1;
}
```

`/test.js` must run tests on file/js's globals.

``` js
var assert = require('assert');
describe('addOne', function() {
  it('should add one to the total', function() {
    assert.equal(2, addOne(1));
  });
});
```

How could I make the mocha test in `test.js` target `addOne` in `file.js`?

**Comment by ScottFreeCode** [comment]
Hey, @ShMcK, I don't know if you're still looking for an answer on this, but for what it's worth: As far as I can tell Node's module system doesn't let you do this, and Mocha or your code (really any library code) can't directly bypass it. Theoretically if you're receiving the code from end users anyway* it may be possible, instead of merely saving the files, to combine it with your test code in some way that they would run in the same context; but your users/students are going to need to learn how to use module systems to export/import code if they want to do anything non-trivial anyway, you may as well start them with good habits right away. (Even in the browser, where the kind of implicit leaky global functions you're asking for are the default, it isn't safe to use the global scope like that and even solutions like IIFEs + namespacing that stop short of a full module system generally don't scale as well as something like [AMD](http://requirejs.org/docs/whyamd.html).)

*Tangentially, if this runs server-side (as I'm assuming based on the need to ask the question in the first place, considering browsers allow this sort of behavior by default), you may need to think about how to sandbox the user/student code in the filesystem so that it can't tamper with the test code or anything (or send your files out onto the internet, or grab and try to run exploit kits over the internet -- basically, if you're running other people's code on your own server without first having a human look at it, you're going to want some sort of security auditing for the system that runs it).
