### ISSUE TITLE
closer integration with assertion libraries

### ISSUE THREAD

**Issue by willnwhite** [mochajs/mocha#2042]
```
describe("functionName", () => {

    it("it's passing because you forgot to write its body", () => {

    });
```
causes:

      ✓ it's passing because you forgot to write its body

I suggest:

      - it's passing because you forgot to write its body (body is empty)

**Comment by danielstjules** [comment]
Can you point to any other test framework that does this?

A naive implementation is a regexp trying to match `() => {}`, `function () {}`, and their variations in spacing/indentation/formatting, etc. But it seems like a little too much hand holding, and there's very little we can do to prevent people from writing useless tests. So I'd just rather avoid going down that rabbithole. For example, this is a useless test with a body:

``` javascript
it('adds numbers', function() {
  var a = 1 + 2;
  // no assertion, can't fail
});

**Comment by willnwhite** [comment]
I just started test-driven development yesterday. Mocha is the first test framework I've used.

I like it because you can program in English: take an English paragraph about how something should work, e.g. in a tutorial, boil it down to something to put in `it`'s first argument. If there are more than one of these at a time, I need to make more than one `it`, so there's a risk that you'll forget to write the body of each `it`. I think Mocha should help.

**Comment by boneskull** [comment]
@danielstjules @willnwhite 

QUnit has a feature wherein you can assert that *n* assertions were made.  I *think* it's configurable such that if a test makes *no* assertions, it will fail.  So there's a precedent for this, at least, but Mocha doesn't currently have any such feature.  

Implementing such a feature may be exceedingly difficult, since we're not guaranteed any given assertion framework will be running at any time.  That means we don't know *what* to check to make sure an "assertion" was indeed made; some libs will throw an `AssertionError`, some will throw an `Error`, some will throw something else entirely.

If we wanted this, we'd need closer integration between Mocha and assertion libraries.  A solution may be to wrap assertion libraries in plugins.  For example, the `mocha-chai` plugin would mark Chai as the assertion library in use (and optionally install Chai itself); from there we could write custom code that is able to detect when a Chai assertion is made, and react accordingly.  Given that there are umpteen assertion libraries, perhaps supporting a few popular libs out-of-the-box would be fine; users can always write new plugins to support integration with other libs.  

I'm not sure what other use cases there are surrounding this sort of integration.  If this is the only one, it's probably not worth the effort.

Anyway, I'm open to more ideas.

**Comment by boneskull** [comment]
I'm going to reopen this and leave it for discussion.

**Comment by boneskull** [comment]
cc @mocha

**Comment by danielstjules** [comment]
@boneskull Seems like this diverges from the original issue of an empty body?

As for counting assertions, it's been previously discussed here: https://github.com/mochajs/mocha/issues/1651 Maybe close this in favor of the other issue?

**Comment by boneskull** [comment]
yeah, good idea.

**Comment by boneskull** [comment]
see #2044

**Comment by willnwhite** [comment]
In the workflow I've described, it's unlikely that once you write something in `it`'s body you'll forget to write an assertion, so just testing for an empty body should be enough.

**Comment by boneskull** [comment]
as @danielstjules wrote, anything along those lines will be a brittle hack, since we're not in the business of analyzing an AST.
