### ISSUE TITLE
All but last test both passes and fails when `done` is called twice

### ISSUE THREAD

**Issue by isiahmeadows** [mochajs/mocha#2057]
Is this by design? It's not helpful with the HTML reporter.

Here's a repro for the BDD interface, but it's the case with all the ones that work in the browser:

``` html
<!DOCTYPE html>
<meta charset="utf-8">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mocha/2.3.4/mocha.min.css">
<div id="mocha"></div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/mocha/2.3.4/mocha.min.js"></script>

<script>
mocha.setup("bdd")
describe("foo", function () {
    it("fails", function (done) {
        done()
        done(new Error("fail!"))
    })

    it("fails 2", function (done) {
        done()
        done(new Error("fail!"))
    })
})
mocha.run()
</script>
```

**Comment by fesebuv** [comment]
Hello @isiahmeadows,
I believe that what you are describing is a bug related to the following issue: https://github.com/mochajs/mocha/issues/2600

**Comment by ScottFreeCode** [comment]
#2600 is unrelated; it's about determining successful `done` call based on number of arguments vs based on the argument being `undefined`.

This issue is pretty much expected behavior: Calling `done` more than once is a test error (regardless of whether another error is supplied to the second call), but calling `done` once is the normal way to pass a test, so the error when `done` is called more than once can only ever occur after the test is already believed to be passed due to the first `done` call.

**Comment by jsocol** [comment]
The error from the test is getting passed to `multiple` on runnable.js#285, which leads to getting the `Error('fail!')` recorded instead of the usual `done called multiple times` error. Not sure if that's necessary/intentional. On line 275 there's a fallback `|| new Error(...)` that can never happen because of the fallback on 285.

**Comment by ScottFreeCode** [comment]
> ...getting the  Error('fail!')  recorded instead of the usual  done called multiple times  error. Not sure if that's necessary/intentional.

I'd guess it's intentional since the code would've actually been simpler if it weren't doing that, but it definitely would be clearer about `done` being called multiple times erroneously if it always used the "done called multiple times" error. I'm not sure what the rationale was for using the error passed to `done` instead, though -- or whether it could somehow print both...
