### ISSUE TITLE
Before not waiting for promises to be resolved

### ISSUE THREAD

**Issue by michaelDomingues** [mochajs/mocha#2122]
Hi guys,

I'm trying to make a test suite where in `Before()` I handle a promise but others test cases run first than promise is resolved. My setup is **webdriverio+mocha**

What I'me doing wrong ?

```
describe('#test', function(done) {
    before(function(done) {
        var p1 = Promise.resolve(3);
        var p2 = 1337;
        var p3 = new Promise(function(resolve, reject) {
            setTimeout(resolve, 100, "foo");
        });

        Promise.all([p1, p2, p3]).then(function(values) {
            console.log(values); // [3, 1337, "foo"] 
            browser.call(done);
        }.bind(done));
    });
    it('should enter a space', function(done) {
        console.log('XPTO');
        // more code
        browser.call(done);
    });
```

The `console.log()` in the first `it` is executed first than promise resolve but that's not what I want. 
From Mocha docs I understood `Before()` would wait for everything to be done.

I tried returning the promise and written in docs but got same symptoms.

**Note**
If I put the `Before()` code inside `describe()` but before `Before()` it works. It waits for promises to be resolved.

What am I missing ? 
Thanks

**Comment by frogcjn** [comment]
Same here!!!

**Comment by frogcjn** [comment]
```ts
    before("clear DB", () => {
        // this.timeout(15000)
        return sequelize.drop() // drop table including its data\, this is a promise
    })
```
Then I got:
  1) import "before all" hook: create DB:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by webxl** [comment]
I was getting this error when I had concurrent ``mocha.run()`` calls on the page, so you might want to check for that. Never saw it running in node.

**Comment by ScottFreeCode** [comment]
@michaelDomingues I wasn't able to reproduce this without webdriverio (although I didn't try multiple `mocha.run()` calls; that would be user error, in any case). If you are able to get it to happen without webdriverio, could you give us a complete (but minimal) test setup to do so? If it only happens with webdriverio, on the other hand, I'd open an issue with them and see if they can dig in further (it might still turn out to be a problem on our end that merely comes up the way they're using Mocha, but we may need their help tracking down what they're doing that causes it even in that case).

A couple tips that may help you avoid other issues, although they shouldn't affect this one:
- If you're using `done` instead of returning the promise, call `.catch(done)` (or `.catch(function(error) { browser.call(done.bind(null, error)) })`) to avoid swallowing exceptions as promise rejections.
- `.bind(done)` immediately after the function just guarantees the function's `this` value (although that doesn't appear to be used in this case) will be the `done` variable.

@frogcjn Try making that a regular function instead of an arrow one and using `this.timeout` to set a longer timeout and see if it eventually goes through (also, you might get a clearer error message on the latest version of Mocha).
