### ISSUE TITLE
Bug: it.only does not work with --delay option - Delayed Root Suite

### ISSUE THREAD

**Issue by nazarhussain** [mochajs/mocha#2142]
I just found that there is malfunction of mocha if we use it with `--delay` option. It does not consider `only` method for the context. 

``` js
setTimeout(function() {
  // do some setup

  describe('my suite', function() {
    it('my it block 1', function(){
        //
    });

    it.only('my it block 2', function(){
        //
    });
  });

  run();
}, 2000);
```

If we run `mocha --delay test-case.js` the output came: 

```
  my suite
    ✓ my it block 1
    ✓ my it block 2
```

The skip works perfectly, only issue is with `only` case. I am using mocha version `2.4.5`.

**Comment by danielstjules** [comment]
Thanks for letting us know! Was able to reproduce locally.

**Comment by megagon** [comment]
root cause is that we are trying to require and set `options.grep` in bdd.js:98 to run only one test without `--delay`.
When we are trying to do it with `--delay `and `setTimeout()` it can't require `it.only()` and as result `options.grep` is undefined in `mocha.js:479`.

I want to fix it, what can be approx solution for this? looks like it will require major changes, isn't it?

**Comment by ektachawla** [comment]
Hi @megagon, I am having similar issue. Trying to use .only() along with --delay option in mocha and .only doesnt seem to work. Did you find a solution for this issue.
Thanks

**Comment by juergba** [comment]
```
my suite
    √ my it block 2

  1 passing (13ms)
```
This bug seems to be fixed meanwhile, the output by the current master is correct when using `only()` along with the `--delay` option.
