### ISSUE TITLE
Mocha bails on compile-time exceptions in test files.

### ISSUE THREAD

**Issue by jj4th** [mochajs/mocha#2147]
If I have a test file that fails to properly compile, mocha bails and does not try to run any other tests in any other files.

```shell
$: ../node_modules/.bin/mocha badFile*.js goodFile.js
/Users/.../badFile.js:1
(function (exports, require, module, __filename, __dirname) { var blah = notaglobal;
                                                                         ^
ReferenceError: notaglobal is not defined
```

It would be nice to have the option to output this as part of the test suite to continue to run good test files.  For example:
```shell
../node_modules/.bin/mocha -r mocha-loadFiles-patch.js badFile*.js goodFile.js

  !! Test file errors
    1) Failed to load: badFile.js
    2) Failed to load: badFile2.js

  SomeFeature
    ✓ should pass.

  1 passing (9ms)
  2 failing

  1) !! Test file errors Failed to load: badFile.js:
     ReferenceError: notaglobal is not defined
     ...

  2) !! Test file errors Failed to load: badFile2.js:
     Error: Cannot find module 'thismoduledoesntexist'
     ...
```

I've accomplished this in my own project by using a pre-require script to monkey patch `Mocha.prototype.loadFiles`.  I realize my specific use case is... specific... but at least some output, failing the overall test run, but still generating test results on the clean files could be useful to others as well.

**Comment by danielstjules** [comment]
Thanks for the issue!

This isn't compilation specific. Mocha bails on any uncaught exceptions that occur when loading your test files. I don't see this as behavior that we'd change though, sorry. If your tests can't be correctly loaded, I don't see any benefit in having them run.

Furthermore, I don't think it would be possible to achieve the output you desire without some elaborate hackyness. For example, imagine a test file like this:

``` javascript
var invalid = require('invalid');

it('test', function() {});
it('test2', function() {});
```

When that first exception is thrown (Cannot find module), node doesn't continue to evaluate the module/test's body - it throws and returns. As a result, there's no way for us to know how many specs were in there since the `it` are never called. Well, we can't without going down some parsing rabbit hole.

Hope that makes sense!

**Comment by jj4th** [comment]
Certainly it makes sense, my suggestion was for the case of multiple test files.  Mostly I just want Mocha to continue running other test files instead of bailing on the whole run the first time it hits a test file it can't handle.  Or better yet, emitting some sort of event rather than exiting with an uncaught exception

**Comment by danielstjules** [comment]
Ah, sorry - I definitely misread the original post last night.

But I'm not still not sure I see the benefit. Given such a severe issue (a file literally can't run), I'd like to see mocha quit immediately so I can fix it, rather than require the use of a --bail flag.
