### ISSUE TITLE
Test is passing without running when putting ".only" on "it"

### ISSUE THREAD

**Issue by benbracha** [mochajs/mocha#2157]
We worked with old mocha (1.18.2) and decided to upgrade to the latest.
Then, we saw that some tests are passing without even running.
We found that this regression started in mocha version 2.4.1 (it worked on 2.3.4, stopped working on 2.4.1 and also on latest).

This is a simple tests that reproduce the issue:

    it.only('mocha test', function() {
		var addAppBtn = $('[debugId="create-new-app-btn"]');
		addAppBtn.click();		
		// You see this console.log on both 2.3.4 and 2.4.1,
		// but on 2.4.1 the test stop right after it, not doing the rest of the actions.
		console.log('HERE');
		
        var appNameElem = $('[debugId="new-app-name-input"]');
		appNameElem.clear();
		appNameElem.sendKeys('new app');
		var okBtn = $('[debugId="ok0-btn"]');
		okBtn.click();
	});

We didn't see any relevant breaking change in the mocha change logs, unless we missed it.
Any idea how this should be resolved / what's the issue here?

**Comment by danielstjules** [comment]
Does the `console.log('HERE')` run in 2.4.1? Do you have a short reproduce case that doesn't involve your app?

**Comment by benbracha** [comment]
The console.log('HERE') does run on 2.4.1..
Actually, if you add console.log('HERE2') as the last line of the test - you see it as well.
But actual test logic doesn't happen.

I don't have a reproduction that doesn't involve my app, but I can come with this shorter one:

    it.only('mocha test', function() {
            var addAppBtn = $('[debugId="create-new-app-btn"]');
            addAppBtn.click();      

            // The click doesn't happen, test just ends before it.
            console.log('HERE'); // This is shown.
    });

But this actually fix the issue:

    it.only('mocha test', function(done) {
          var addAppBtn = $('[debugId="create-new-app-btn"]');
          addAppBtn.click().then(function() {
          // Do something
          done();
      }
    });

Now the button is clicked, and only then the test finish.

But this fix makes writing tests very annoying - we need to add a callback almost for each statement. 
It breaks the whole idea of writing things fluently, which is a strong point of protractor (that we use).

**Comment by danielstjules** [comment]
Looks like `addAppBtn.click()` is a promise (async), and you're running the test in an sync manner. Thankfully, you can also return promises in tests.

I'd suggest the following:
``` javascript
it('example', function() {
  var addAppBtn = $('[debugId="create-new-app-btn"]');
  return addAppBtn.click().then(function() {
    // Add your assertions here
    console.log('INSIDE');
  });
});
```

Hope that helps!

**Comment by benbracha** [comment]
@danielstjules  you are right - but it *worked* on Mocha 2.3.4, and *stopped working* on 2.4.1
I have more then 100 tests, I don't want to re-write them all. We need to understand what has changed.
Can you reopen ?

**Comment by benbracha** [comment]
Writing tests in "sync" manner is the whole idea of protractor.
That's why we wrote tests in the above manner. (similar example can be found on https://angular.github.io/protractor/#/ - no need to put "then" to a button click).

Thanks for reopening. I'll try to share this with protractor team as well.

**Comment by danielstjules** [comment]
No problem! Could you write a minimal reproduce case?

**Comment by benbracha** [comment]
The above example is the minimal I can think of - simple app with 1 button, just try to click it (using protractor API).
Can you be more specific of what can I supply you with?

**Comment by danielstjules** [comment]
An example that I can copy-paste and run would be perfect. If it's reproducible outside of protractor (no external deps), even better!

**Comment by sjelin** [comment]
Hi, I'm from the protractor team and I'm working to sort out who's bug this is.  I'll let you know if I can reproduce it without protractor :smile:

**Comment by benbracha** [comment]
Thanks.
Actually I made some progress in reproducing the issue in a simple example.
I can share my sample app later. Generally it seems like that something is
wrong when running the test with ".only".
Meaning - put a .only on the "it" and it will not run properly, but put
.only on the "describe" containing it, just works.

Seems this happens only when I run with grunt protractor runner and not
directly with protractor, but not sure yet.

I'll keep pin point the issue and will update.

**Comment by benbracha** [comment]
I pinned down the issue and wrote a simple app that reproduce it:
https://github.com/benbracha/mocha-test-run/blob/master/README.md

Seems like when putting an ".only" on an "it" cause the test to pass without even running.
It doesn't seem related to mocha 2.4.1, it happened also before.

**Comment by benbracha** [comment]
I'm not sure if this is mocha or protractor issue, but I'll continue the discussion on the related protractor issue. So closing this.

**Comment by noisette44** [comment]
I have same issue since 2.4.1;

This commit [08bf74d](https://github.com/mochajs/mocha/commit/08bf74d8440b811e42bf4b8150a4977a05472c9a) named "always reference the correct it from it.only" by @cowboyd introduce this issue.

When i use mocha which protractor, selenium webdriver use a Mocha's BDD interface wrapper ([index.js](https://github.com/SeleniumHQ/selenium/blob/ede98def1f85600ec120536bd1f36f244a331b86/javascript/node/selenium-webdriver/testing/index.js)):

`exports.it = wrapped(global.it);`
`exports.iit = exports.it.only = wrapped(global.it.only);`

Now wrapped "it.only" function not use the wrapped "it" function but the original mocha function and test is passing without running when putting ".only".

@cowboyd : Can you tell us why you did this update?

**Comment by cowboyd** [comment]
@noisette44 This commit resolved #1964 wherein `beforeEach` hooks were _not_ being run by `it.only` when they were defined with `require('mocha').beforeEach` and `require('mocha').it`.

This [testcase]( https://github.com/mochajs/mocha/blob/08bf74d8440b811e42bf4b8150a4977a05472c9a/test/acceptance/misc/only/bdd-require.js) failed without this change.

**Comment by noisette44** [comment]
@cowboyd : Thanks for reply
In this case, maybe a duplication of code is necessary between `it` and `it.only` function.

**Comment by benbracha** [comment]
Thanks for the reply, just to understand - on which mocha version we can now have the it.only() working properly? Because it wasn't working with 2.4.1

**Comment by noisette44** [comment]
in my case (protractor + mocha), the latest version working with `it.only` is the 2.3.4.

**Comment by benbracha** [comment]
Same here, although I didn't test recent versions (I see there are up to 2.5.3 now..).
@noisette44  did you try them?

**Comment by noisette44** [comment]
Yes, issue is still present with latest version 2.5.3.

**Comment by ScottFreeCode** [comment]
So, if I've understood this correctly...

1. Logically, Mocha's synchronous tests can't be used for asynchronous code.
2. Selenium WebDriver, used by Protractor among other things, has asynchronous code and handles it by monkey-patching the test interface with a wrapper that looks like Mocha's synchronous tests but acts like the asynchronous version, tied to whatever asynchronous WebDriver commands are called instead of to `done`. (Tangentially, if a library or framework is going to supply their own behavior, it'd be nice if they didn't make people think it's Mocha. This isn't the first issue to come up with such modifications, and I doubt it will be the last...)
3. To [work around](../pull/1965) a [nasty side effect](1964) of the fact that [the BDD interface is still initially set up even when another is chosen](2207) (such as the require interface, which tries to set up some of the same stuff again), `it.only` was changed from using the currently exposed `it` to using the same `it` that `it.only` was originally defined along with.
4. Thus, whereas before `it.only` made use of Selenium's monkey-patched `it`, it now makes use of Mocha's original `it`, which won't work with the asynchronous WebDriver code.

Is that accurate? And does anyone know if a similar issue applies to `describe.only`?

I'm inclined to say that Selenium WebDriver (or anything that monkey-patches `it` or `describe`) should replace `only` with a version that recreates [the functionality](../blob/master/lib/interfaces/bdd.js#L95) using their own `it` (or `describe`). (Fortunately, this should be possible since `only` is really a shortcut for `it` + `grep`; if, as most people usually expect, `only` were actually doing something direct to force the thing `only` is called on to be the sole suite or test, it might not be possible to recreate externally.) The behavior of most functions in the face of wrapping monkey-patches doesn't seem like part of the external API to me, at least not if it isn't deliberately intended and specifically documented. And even if it were, at this point if Selenium is intended to support arbitrary Mocha versions it'll have to handle these ones where `it.only` is tamper-proofed (although, if they only want to support arbitrary "minor" versions, I suppose we could publish new patch versions fixing the issue for each affected "minor" version).

(On the other hand, for what it's worth, if it were to rely on `only` referring to the monkey-patches `it`, it would not need to wrap `only`; it may or may not hurt, but it shouldn't be needed in that case.)

That being said, I think we could change the behavior of `it.only` back if we fixed the underlying issue -- and I think there is an underlying issue that the way the BDD interface is defaulted is wrong. What we should have is that only the specified interface is set up and the CLI specifies BDD if no other is requested, but what we've got, if I'm not mistaken, is that the BDD interface is always set up and then if another interface is specified that other interface is set up too, and then we try to remove effects of the originally set up BDD interface after the fact ([not entirely successfully](2207)).

**Comment by noisette44** [comment]
Thanks for reply. I totally agree with you.
So, I will open a Selenium WebDriver issue to know their opinions about this.

**Comment by benbracha** [comment]
Thanks for the reply. I agree as well with @ScottFreeCode comment.
@noisette44  can you reference the Selenium WebDriver issue you opened so I can see the progress of it?
Currently, this issue blocks me from upgrading Mocha, and I'm waiting for some new features I want to use..  (like "retry" added in 2.4.1)
As there a reasonable workaround for this issue you can think of that will allow me to upgrade to newer Mocha versions?

**Comment by noisette44** [comment]
Selenium webdriver issue : [https://github.com/SeleniumHQ/selenium/issues/2302](https://github.com/SeleniumHQ/selenium/issues/2302)

**Comment by ScottFreeCode** [comment]
My [comment](#issuecomment-224475198) has been corrected to reflect new information acquired with the help of the Selenium team (see the Selenium issue).
