### ISSUE TITLE
Ignoring browser-related variables while frontend testing react + redux app

### ISSUE THREAD

**Issue by Robinnnnn** [mochajs/mocha#2163]
I'm currently using mocha for frontend testing my react/redux app.

It seems like whenever there are browser-related variables in my functions, the test fails.

For example, one of my functions looks like this:

```
export const loginUserSuccess = (token, user) => {
    localStorage.setItem('token', token); // browser-related variable here
    return {
        type: LOGIN_USER_SUCCESS,
        payload: {
            token: token,
            user: user
        }
    }
}
```

Note my use of `localStorage`. This variable is obviously not available while testing, so any test that happens to trigger the `loginUserSuccess` action never passes. To be honest I don't need to test the localStorage logic -- I just want the action to return the correct thing. But even if I do something like this:

`if (localStorage) localStorage.setItem('token', token);`

I still get an error saying localStorage is undefined. How can I get the testing module to ignore certain variables? I also get an error when I call the global `window`.

**Comment by ScottFreeCode** [comment]
(TL;DR version: use `if (typeof localStorage != "undefined")` -- substitute `!==` for `!=` if you prefer, as far as I'm aware it doesn't make a difference in this case -- *if this is really what you want to do*; however, *strongly consider instead refactoring your tests and functionality, and/or testing in a browser, so that the code to be tested doesn't do anything special based on whether it's being tested*.)

---

If I've understood correctly, this is really a JavaScript thing rather than a Mocha thing. Javascript will evaluate variables to `undefined` if they are declared but not set to a value, are explicitly set to `undefined` or are non-existent members of an object that is defined, but throws an error rather than merely evaluating to `undefined` if you directly refer to a non-member variable that is not declared:
```js
var someVariable = {}
console.log(someVariable.memberThatIsNotDefined) // prints undefined
console.log(someVariableThatIsNotDefined) // throws error because of reference to nonexistent variable
```
Fortunately, `typeof` works even on these variables and can therefore be used to check for whether a member of the global context is available without prefixing it with the global object:
- `if (typeof someVariableThatMayOrMayNotBeDefined != "undefined") { // do stuff...`
- `var someVariableWithDefault = typeof someVariableWithDefault != "undefined" ? someVariableWithDefault : "default"`
- or in your case: `if (typeof localStorage != "undefined")`

To tackle that problem from the opposite direction, you could also change `if (localStorage)` to `if (window.localStorage)`, `if (self.localStorage)` or `if (global.localStorage)` -- but `window`, `self` and `global` may also not exist and have the same problem. Specifically, `window` is available in the main context of a browser, `self` is a synonym for `window` in the main context of a browser but is also available in the browser in Web Workers, and `global` is the equivalent in Node.js (as far as I'm aware). An alternative to using `typeof someVariable != "undefined"` would therefore be to make `global` available in all three contexts by starting the script with `var global = typeof global != "undefined" ? global : self` or wrapping the script in `(function(global){ `[...script contents here...]` }(typeof global != "undefined" ? global : self))`, and then in the script use `global.someVariable` the way you're trying to test `localStorage` here: `if (global.localStorage)`. This will break if any other scripts in the same context set a global variable named `global` to anything other than `self` or `window`, but... hopefully nobody's doing that?

Anyway, all these approaches convey slightly different things to the reader, but amount to the same effect for the code as far as I can tell (except that wrapping the script in an immediately invoked function expression may have some subtle differences that shouldn't matter if you aren't doing anything goofy, and will reduce problems or side effects if it's concatenated with other script files if you also add a `;` before the initial `(function`... -- although raw text concatenation has fallen out of favor with the rise of code-aware bundlers and bundling minifiers and transpilers anyway).

---

All that being said because it's knowledge worth having in general, *there may be a more important overarching design issue here.* The browser's `localStorage` or other `window` functionality doesn't need to be tested here, but *your program's code that uses them does*, and **making it change its behavior based on trying to guesstimate whether it's being tested introduces an extra layer of risk that you have to avoid changing any of the behavior that should be tested (which may include the way it's trying to use `localStorage` or other `window` members) and avoid triggering the test-mode behavior in non-test environments with unanticipated similarities to the test environment/context**. That's pretty dangerous stuff! Even if it looks simple and obvious now, it's an extra layer of maintenance to do it everywhere it comes up and make sure that it's all correct and remains correct even as code changes.

So, instead, you'd probably want to mock `localStorage` somehow -- that is, in testing replace the `localStorage` object with an object that doesn't need to replicate the full behavior of the real `localStorage`, only replicate the API and enough of the behavior (if any) to test the code that's supposed to be using `localStorage`. Some folks swear by making this sort of thing an injected dependency, i.e. make the function or the object of which it's a member take `localStorage` as a parameter or setting somewhere along the line rather than hardcoding it, so it can be replaced with a mock for testing -- or with a different implementation, should that ever be useful. This being JavaScript, however, you could also just have the test "polyfill" a mock `localStorage` on the global context/object instead. As another variation, you could isolate the code that interacts with `localStorage` and make *that* where you can swap out `localStorage` for testing, but this is extra abstraction overhead to merely limit the problem rather than resolve it (does the `localStorage`-isolating code layer itself not need to be tested?) -- it may, however, integrate well with a solution to abstract away the difference between `localStorage` and an alternative implementation, in which case it might work out naturally anyway. So you've got a few options along those lines.

Alternatively, if the functionality you want to test doesn't work (or doesn't even make sense) without an actual browser, it might make more sense only to test in-browser in the first place and not worry about any out-of-browser scenarios, testing or not. This doesn't really address testing how your code uses `localStorage` or other browser features independent of whether the browser's implementation of those features is available or correct, but it's important in general to be sure you're testing in the type of environment in which your code is meant to actually run. Plus, it may also be useful to know if a particular browser's implementation (or lack thereof) is causing problems, even if your code is correct in and of itself; so, actually testing with the real thing may matter even if you do also want to isolate your code and test it without dependence on the browser features.

In any case, *you almost certainly shouldn't try to skip behavior based on the absence of `localStorage` or other `window`-centric variables unless that's how the code should behave if run in some environment without those variables for real and not just for testing, and even if you did support that you would still want to test the `window`-specific features in a browser so they're not left untested*.

**Comment by fesebuv** [comment]
@ScottFreeCode should this question be resolved/closed?

**Comment by ScottFreeCode** [comment]
I believe the question has been answered; I usually like to let the original poster at least reply to let us know whether there's anything that still needs clarification or correction, but if the issue gets old I also don't mind letting the bot close it.

Except, of course, some of these issues that have been properly categorized with tags are ignored by the bot... I guess I'll get this closed manually. Thanks for bringing it to my attention!

@Robinnnnn If you still need further help with this please just let us know!

**Comment by fesebuv** [comment]
@ScottFreeCode you are welcome! Happy to help! 👍
