### ISSUE TITLE
cli don't watch new added file

### ISSUE THREAD

**Issue by p2227** [mochajs/mocha#2176]
let's say there is one file name  `a.js` in a dictionary `test`
my test script `mocha test/*.js -w`
when i change `a.js` and save ,mocha will restart;

but when i add a new `b.js` in `test` ,mocha won't restart;

**Comment by jordanmkoncz** [comment]
Having the same issue. With the `--watch` flag, Mocha does not seem to detect when a new test file has been created, forcing you to completely close the running `mocha` process and restart it so that it picks up the new test file.

I'm running Node v5.4.1 and Mocha v2.4.5.

**Comment by nadeemja** [comment]
Same here.

**Comment by lddubeau** [comment]
The first thought that came to my mind when I saw this report is that your shell is probably messing up your glob. When you run this in a Bash shell, for instance:

```
mocha -w test/*.js
```

the shell will expand `test/*.js` to the list of files that match and what is finally executed would be something like:

```
mocha -w test/a.js test/b.js [...]
```

The pattern is turned into a finite list. So it would have to be protected from expansion by quoting. Again, in Bash: `mocha -w 'test/*.js'` With this, the glob is passed to Mocha, which performs the expansion itself.

However, while expansion by the shell is definitely something to work around, **this is not the whole problem here**. Because, this also fails with the same symptoms reported in the original report:

```
mocha -w --recursive
```

Changes to files in `test` that were already existing will be detected but added files do not trigger a new run.

**Comment by wilhen01** [comment]
Does anyone have a solution for this?

**Comment by lanespade** [comment]
I ran into this issue as well and solved it using nodemon...

`nodemon --exec mocha -w`

...although since I am running a node.js application inside of a docker container, my specific code looks more like...

`
"scripts": {
    "watch": "docker exec -it admin_api node_modules/.bin/nodemon --exec \"node_modules/.bin/_mocha -w\""
}
`

...so I use mocha watch to detect when my docker files (app / test) change to re-run the tests and I use nodemon to run my server to restart whenever my docker files (app) change. I needed to include nodemon into my mocha watch command to detect the new files issue mentioned here, but after all of this, I can have my docker instance up, re-running tests as I edit application or test code and be able to hit my localhost endpoints and manually test / interact as I develop.

I  hope this helps you guys!

**Comment by vulkanosaure** [comment]
+1

**Comment by Billy-** [comment]
Is there any plan to fix this?

**Comment by ScottFreeCode** [comment]
We've actually wanted to get rid of `--watch` for a long time: https://github.com/mochajs/mocha/issues/909#issuecomment-20311034 #1780

An external watcher would eliminate a lot of issues like this one; the main problem, discussed in #1780, seems to be that Mocha is way slower when running multiple times through the CLI, but running multiple times through the programmatic API is broken in several ways.

Basically, the preferred way to address this would be to find and fix those issues, e.g.: #736 #995 #1938 #2435 #2706 #2783 Note that these look, at a glance, mostly redundant; it would be really helpful if anyone would go through them and identify a list of specific things that need to be fixed. It would also be great to get testing for running Mocha multiple times programmatically, but obviously since those tests would fail initially they can't go on the master branch yet -- I guess we need a development branch for addressing the various problems with multiple programmatic runs?
