### ISSUE TITLE
Ignore ".only" by config

### ISSUE THREAD

**Issue by amiram** [mochajs/mocha#2185]
What do you think about an option to ignore ".only" by config. This can be useful if a developer forget and commit such code, but in build we want to execute all tests.

**Comment by jiangyang** [comment]
Happen to be wondering about almost the same thing. In our use case, we want to raise an error on the build machine if ppl accidentally check in code with exclusive tests

Found a hack as follows

```
  var mocha = require('mocha')
  var original_loadFiles = mocha.prototype.loadFiles
  mocha.prototype.loadFiles = function (fn) {
    this.suite.on('pre-require', function (context, file, self) {
      context.describe.only = function () {
        throw new Error('Exclusive test suite is not allowed(remove "describe.only" in file ' + file + ').')
      }
      context.it.only = function () {
        throw new Error('Exclusive test case is not allowed(remove "it.only" in file ' + file + ').')
      }
    })
    original_loadFiles.call(this, fn)
  }
```
There is prob a better way to do it and you might not want the same thing. You could also try using a custom interface based on interfaces/bdd.js or something like that. However, I think it ll be nice if mocha provides a way to toggle different behaviors around this.

**Comment by dasilvacontin** [comment]
@amiram I personally prefer to fail the build if a `.only` is committed, unless you want to start having a bunch of `.only`s in your tests. And then you would start having builds that pass locally (because some tests are omitted because of the `.only`), but don't pass in CI (because all tests are ran).

You can use this package for your hooks and CI: https://github.com/dasilvacontin/dot-only-hunter.

**Comment by amiram** [comment]
@jiangyang your code looks good enough for me. @dasilvacontin you're probably right.

**Comment by dasilvacontin** [comment]
Closing since I feel like the proposal – ignoring `.only` – is not really wanted (probs looking for #1935).

Let us know otherwise! :)

**Comment by zardilior** [comment]
I would say ignoring only as a flag would be ideal

**Comment by shelbykauth** [comment]
I actually found this because I'm looking for a way to use two terminals, both with mocha --watch, one running with the .only on new tests that I'm adding while the other runs all my tests as I make major modifications.  That would allow me to focus on just the new tests, while also ensuring that the rest of the tests are still fine.
