### ISSUE TITLE
2 support questions

### ISSUE THREAD

**Issue by ORESoftware** [mochajs/mocha#2192]
Two questions that I couldn't find answers to in the dox

Question 1 -  if there is a before/after hook, but no applicable test cases, the hooks don't run - does the same apply when the tests are stubbed out / "pending" ?

It appears that the hooks _do in fact run_ for pending tests, and that seems inconsistent. For example:

```js
describe('a', function () {

    before(function(){
        console.log('before this a:', this.parent);
    });

    after(function  () {

        console.log('after this a:', this.parent);

    });

    it('a');

});
```

Question 2 - The docs make it clear that we can stub out tests, but my question is can we stub out hooks too? Would be curious, thanks.

**Comment by danielstjules** [comment]
> It appears that the hooks do in fact run for pending tests, and that seems inconsistent. For example:

Not entirely. The suite's before/after hooks will run since the entire suite isn't being skipped. That said, no beforeEach/afterEach hooks will run. E.g.

``` javascript
$ cat test.js
before(function() {
  console.log('before');
});

beforeEach(function() {
  console.log('beforeEach');
});

it.skip('pending', function() {});

$ mocha test.js


before
  - pending

  0 passing (4ms)
  1 pending
```

As for "stubbing out tests", I'm not 100% sure what you mean. If you're just referring to using stubbing/mocking frameworks, then sure!

Hope that helps!
