### ISSUE TITLE
is it possible to pass values from "beforeEach" to the actual test

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [mochajs/mocha#2245]
I am writing unit tests for file operation functions. This tests work in a temporary directory, which I create with

```
fs.mkdtemp()
```

But now the test has to know its temporary directory. Can I somehow pass this information to the test?

**Comment by iknowcss** [comment]
Maybe something like this?

```
describe('File operations', function () {
  var tempFolderPath;

  beforeEach(function (done) {
    fs.mkdtemp(function (err, folder) {
      tempFolderPath = folder;
      done();
    });
  });

  it('writes the alpha file', function () {
    console.log(tempFolderPath);
  });
});
```

**Comment by RudolfVonKrugstein** [comment]
cool, thank you!

**Comment by zcmgyu** [comment]
Try this one
https://gist.github.com/icirellik/b9968abcecbb9e88dfb2

**Comment by iknowcss** [comment]
Hey @zcmgyu, thanks for your suggestion. Your `this` solution is the only other way I know of to solve the problem of passing data from `beforeEach` blocks to `it` blocks. I think it's even the way the mocha developers imagined people should solve this issue.

However, in the OPs code, he has to create a callback function that handles the completion of the folder creation and stores the folder path somewhere for the test to pick up. Dealing with `this` in this situation can be a bit tricky. If someone took your suggestion and applied it to the code without being careful about `this`, they might write something like this:

```javascript
describe('File operations', function () {
  beforeEach(function (done) {
    fs.mkdtemp(function (err, folder) {
      this.currentTest.tempFolderPath = folder;
      done();
    });
  });

  it('writes the alpha file', function () {
    console.log(this.test.tempFolderPath);
  });
});
```

This code would probably not work right. The mistake here is in the `beforeEach` block. The value of `this` inside the callback passed to `mkdtemp` will not refer to the same `this` as in the `beforeEach`. There are several ways to fix this:

*Option 1 - Use a fat arrow*
```javascript
beforeEach(function (done) {
  // The fat arrow here binds the callback's `this` to the same `this` in the `beforeEach`
  fs.mkdtemp((err, folder) => {
    this.currentTest.tempFolderPath = folder;
    done();
  });
});
```

This option ☝️ isn't so nice IMO because you have to mix fat arrows functions with unbound functions. That subtle difference could be missed, and that would cause more confusion.

*Option 2 - Maintain a reference `this` for the `mkdtemp` callback*
```javascript
beforeEach(function (done) {
  // No mixing function styles here, but now I've got an extra variable
  var self = this;
  fs.mkdtemp(function (err, folder) {
    self.currentTest.tempFolderPath = folder;
    done();
  });
});
```

This option ☝️ avoids mixing fat arrow functions with traditional `function () {}` functions, but it adds the odd `self` variable to the mix just get around the fact that JavaScript treats `this` in this way. Someone might think "why does this need to be here?", remove the line, and then the test fails. Or *worse*, the test **still passes**, but doesn't actually test the functionality!

*Option 3 - Bind the reference `this` to the `mkdtemp` callback*
```javascript
beforeEach(function (done) {
  fs.mkdtemp((function (err, folder) {
    this.currentTest.tempFolderPath = folder;
    done();
  }).bind(this));
});
```

This option ☝️ doesn't mix fat arrow functions with traditional functions, and there's no odd `self` variable stuff, but now I have to use the "function" function `bind`, which just feels double confusing because you have to deal with both `bind` and `this` at the same time. All this confusion for a simple test!

Which brings me to my original suggestion of creating a variable in the parent scope. This approach:

1. avoids mixing function definition styles
2. avoids making another variable for the sake of holding the value of `this`
3. doesn't use confusing "function" functions like `bind`

...and most importantly

**it doesn't require you to reason about `this`, which is arguably the most confusing concept in JavaScript**

This was my thinking 3 years ago when I left this small comment in hopes of helping a fellow coder get un-stuck from a small but annoying detail keeping him from moving on to actual feature development. I assume it worked for him as he then commented 

> cool, thank you!

and went on about his merry way.

But a lot of people reacted to my comment with 

> 👎

And every time I get a notification for this issue, I see the counter for 👎 has incremented one or two. And I seriously always scratch my head trying to figure out what is wrong with my suggestion. And I relate to the guy who asked 

> Is this a good practice?

because he must just be as confused as I am about all this. Is what I'm doing a bad practice? Am I a bad coder? Should I feel bad? I genuinely do not know. Because no one has ever said:

> Hey, iknowcss, get back to writing CSS and leave the Mocha unit tests to the professionals. Your code is weak, and your squat is weak. Here, since I'm such a nice guy (who lifts), I'll show you how an actual developer would do it properly:

followed by a condescending explanation of how to do it the "best practice way".

But just 👎++. For 3 years. 🤷‍♂ 

So for all of you out there who are scratching your head thinking to yourself "if this is not the right way, what is?". I don't know. I still don't know. I may never know. But it's pretty funny, hey.

**Comment by shelbykauth** [comment]
@iknowcss 

## Disclaimer
I don't think there really is a "best practice" way to do this yet.  All we're doing is taking shots in the dark.  I'm not trying to put you down, but offer a possible explanation to the downvote phenomenon.  I don't think your way is wrong.  And it is highly documented.  But I don't think it's the best way possible.

Also, for all three examples, append this in order to get vsCode to give type hints.  No, none of the tests actually pass, because I was trying to make this as slim as possible.

```js
class FakeServerClass {
  async addItems() {}
  async getCount() {}
}
class SpecialFakeServerClass extends FakeServerClass {}
```


## Parent-scoped variable pitfalls

<details>
<summary>(click to see code)

Okay so here's the reason why you _wouldn't_ want to use a parent-scoped variable.

It is ~~more~~ _just as_ likely that a new developer on the project will mix up `before` and `beforeEach` as the possibility that they'll mix up `function(){}` and `()=>{}`, especially when running the boilerplate multiple times doesn't change anything for the first several tests looked at.  And it's also easy to miss.  So it may be unclear at first glance the difference between something like the following two suites.

(code below fold)
<hr/>
</summary>

```js
describe("suite", ()=> {
  /**@type {FakeServerClass} */
  let fakeServer;
  beforeEach(async ()=> {
    fakeServer = new FakeServerClass();
    await fakeServer.setupPromise;
  });

  it("Should Test Thing A", async ()=> {
    await fakeServer.addItems([/*...three items...*/]);
    let count = await fakeServer.getCount();
    assert.equal(count, 3);
  });
  it("Should Test Thing B", async ()=> {
    await fakeServer.addItems([/*...two items...*/]);
    let count = await fakeServer.getCount();
    assert.equal(count, 2);
  });
});
```

```js
describe("suite", ()=> {
  /**@type {FakeServerClass} */
  let fakeServer;
  before(async ()=> {
    fakeServer = new FakeServerClass();
    await fakeServer.setupPromise;
  });

  it("Should Test Thing A", async ()=> {
    await fakeServer.addItems([/*...three items...*/]);
    let count = await fakeServer.getCount();
    assert.equal(count, 3);
  });
  it("Should Test Thing B", async ()=> {
    await fakeServer.addItems([/*...two items...*/]);
    let count = await fakeServer.getCount();
    assert.equal(count, 5);
  });
});
```

</details>

So using parent-scoped variables can create confusion about what that item actually is.  Using `before` would also cause a lot of problems should you skip a test or try to run in parallel.

## Keyword `this` pitfalls

<details>
<summary>(click to see code)

Personally, I mix `function(){}` and `()=>{}` all the time.  They have meaning to me, like mixing `const` and `let`.  An arrow notation is any function that should be taken as part of the parent scope, while function notation indicates that a thing is attached to a particular object.  Or rather, `function` means that `this` is involved somewhere, while arrow notation means that `this` is skipped.  I also use variables such as `theModel` or other descriptive alternatives to `that` and `self` when I need to change `this` contexts or when the functions get a little more nested than I'd like.

However, I agree with you that using `this` is tricky and not really best practice.  Especially with mocha, it's completely not clear that the beforeEach function and the it function share a `this` space.  It's not intuitive and very surprising.

(code below fold)
<hr/>
</summary>

```js
describe("suite", ()=>{
  beforeEach(async function () {
    /**@type {FakeServerClass} */
    this.fakeServer = new FakeServerClass();
    await fakeServer.setupPromise;
  });

  it("Should Test Thing A", async function () {
    /**@type {FakeServerClass} */
    let fakeServer = this.fakeServer;
    await fakeServer.addItems([/*...three items...*/]);
    let count = await fakeServer.getCount();
    assert.equal(count, 3);
  });
  it("Should Test Thing B", async function () {
    /**@type {FakeServerClass} */
    let fakeServer = this.fakeServer;
    await fakeServer.addItems([/*...two items...*/]);
    let count = await fakeServer.getCount();
    assert.equal(count, 2);
  });
})
```

</details>

If you change beforeEach to before, you have the same problem as the other method.  And it's equally invisible.  And in order to get typecasting, you have to declare /**@type*/ multiple times.

## My preferred Method

<details>
<summary>(click to see code)

I may be wrong about this, but my current belief is that we should not use before as a crutch for passing data around.  If your test depends on some variable, it should be explicitly specified.  Before, After, BeforeEach, AfterEach should only be used for things that are invisible to the test.  Such as log suppression, config changes, etc.

If you truly want to use the same service instance for each and every test, then it makes sense to declare a parent-scoped variable.  But typically, that's something we wish to avoid.  A better solution may be as follows.  (It's bigger because there's twice as many tests and double the setup)

(code below fold)
<hr/>
</summary>

```js
describe("suite", ()=>{
  it("Should Test Thing A", async () => {
    let {fakeServer} = await SetupTestComponentA();
    await fakeServer.addItems([/*...three items...*/]);
    let count = await fakeServer.getCount();
    assert.equal(count, 3);
  });
  it("Should Test Thing A (second)", async () => {
    let {fakeServer} = await SetupTestComponentA();
    await fakeServer.addItems([/*...three items...*/]);
    let count = await fakeServer.getCount();
    assert.equal(count, 3);
  });
  it("Should Test Thing B", async () => {
    let {fakeServer} = await SetupTestComponentB();
    await fakeServer.addItems([/*...two items...*/]);
    let count = await fakeServer.getCount();
    assert.equal(count, 2);
  });
  it("Should Test Thing B (second)", async () => {
    let {fakeServer, otherComponent} = await SetupTestComponentB();
    await fakeServer.addItems([/*...two items...*/]);
    let count = await fakeServer.getCount();
    assert.equal(count, 2);
  });
})

async function SetupTestComponentA () {
  let fakeServer = new FakeServerClass();
  await fakeServer.setupPromise;
  return {fakeServer};
}

async function SetupTestComponentB () {
  let fakeServer = new SpecialFakeServerClass();
  await fakeServer.setupPromise;
  let otherComponent = blah;
  return {fakeServer, otherComponent};
}
```

</details>

I still use before/after stuff.  But mostly it's to set stuff that should _not_ be accessed by the tests.  Such as `const originalEnvVars = process.env` before and `process.env = originalEnvVars` after. (when testing a config factory, for example)
