### ISSUE TITLE
Mocha output only showing timing for the the first it function

### ISSUE THREAD

**Issue by Avcajaraville** [mochajs/mocha#2254]
When I run my tests, I can see the following:
![captura de pantalla 2016-05-13 a las 17 24 15](https://cloud.githubusercontent.com/assets/2271201/15252735/9edbc058-192f-11e6-94af-a824b6fef32e.png)

Why Mocha is showing the time employed only for the first "it" ?

The code is something like this:
```
describe( 'html rendering through smarty', function() {
  it( 'returns an HTML response', function( done ) { .. });
  it( 'write templates variables on html document', function( done ) { .. });
  it( 'write snippets on html document', function( done ) { .. });
});
```
I guess this is not correct, or is this expected ?

**Comment by boneskull** [comment]
A "slow" test, by default, is considered to take longer than 75ms.  You're seeing a "medium" (or "somewhat slow") test, which is greater than or equal to 1/2 of 75ms.  The second and third tests execute faster than 37.5ms, so neither shows the duration.  If you would like to *always* see the duration, you can reduce the "slow" value to 1ms via `--slow` or otherwise.

**Comment by Avcajaraville** [comment]
Thank you so much for your answer !
