### ISSUE TITLE
Multiple Assertions?

### ISSUE THREAD

**Issue by Aftabnack** [mochajs/mocha#2288]
Testing for **one single component**
Does it make sense to write separate `it()` statements with one *expect* for each attribute of an element.
Or just one `it()` for the component with multiple expects for that component's attributes

```javascript
it("with class name = btn btn-primary & label = Add Project", () => {
			let myButton = scryRenderedDOMComponentsWithTag(component,'button')[0];
			expect(myButton.className).to.equal("btn btn-primary");
			expect(myButton.textContent).to.contain("Add Project");
});
```

**VS**

```javascript
it("with class name = btn btn-primary", () => {
			let myButton = scryRenderedDOMComponentsWithTag(component,'button')[0];
			expect(myButton.className).to.equal("btn btn-primary");
});
it("with label = Add Project", () => {
			let myButton = scryRenderedDOMComponentsWithTag(component,'button')[0];
			expect(myButton.textContent).to.contain("Add Project");
});
```

**Comment by agyanttiwari** [comment]
If you two separate tests it will be easier to debug the code when the test fails. 
As you would then have results for both the conditions and would know which one is failing.
However, if you have both the conditions in the same test:
if **expect(myButton.className).to.equal("btn btn-primary");** would fail, you wouldn't know if **expect(myButton.textContent).to.contain("Add Project");** also failed.

**Comment by ScottFreeCode** [comment]
Regarding the practical angle of knowing what's failing in each assertion: depending on your assertion library, you may be able to get more specific errors using messages in the assertions even in the same test, if the default assertion messages aren't sufficiently distinct (in some cases they will be); it's sort of like providing a message to the constructor of an exception being thrown.

To the original question, I think it comes down to a philosophical issue: is this one thing being tested that requires multiple assertions, or multiple things being tested in the first place? For instance, in your example the test message about both class name and label suggests that they should be multiple tests. But for a counterexample, you could have a single "should be an integer" test that asserts `typeof value` strict-equals `"number"`, `isFinite(value)` is ok/truthy, and `value` strict-equals `Math.floor(value)` -- three assertions needed to validate a single thing, integer-ness. Similarly, it's possible that your example makes more sense using one test and multiple assertions but the message should be about the type of element being tested while the assertions should make clear that they're checking the class and the label, rather than using the whole test message just to say what the assertions are checking.

For that matter, it's a good idea in general to avoid putting information in the test message that could be conveyed through the assertion failure message -- not that you want to have uninformative test messages, but that you want the test message to convey the higher-level info that the assertions can't.

To quote a maintainer of another project I use: closing as a discussion ticket, but feel free to continue discussion here.

**Comment by Aftabnack** [comment]
I agree with you that the message written here is doesn't make a difference since exactly what I am testing, I can change it something like "Add project button is proper".

The point of contention here is, whether a **unit** in "Unit testing" refer to just one basic html component, or is it each single attribute associated with that component. I feel testing one complete html element as one entity makes sense. Even though if multiple assertion fails, it shows only the first failed, It should be fine since we are testing one element, and if that fails we can easily go over all the asserts related to that element.
*What do you guys think??*

**Comment by jamesmortensen** [comment]
When writing API tests, we are testing one endpoint request, but there are many things in the response to validate.  I felt separating them into multiple tests essentially wasted time repeating the same test over and over again.  We could also execute the test in the before block and add assertions in independent test blocks, but this artificially increases the number of test cases, and some of our engineers thought the test code looked more complex when we split everything up.

Keeping them in the same test block looks simpler but, as others mention, meant we only get feedback on the first failing assertion, which means we don't get the full picture of exactly what fails.

Jasmine, by default, executes all assertions and reports on all the ones that fail, and they are able to do this because the test runner is more tightly coupled to their assertion library.

To enable similar functionality with mocha/chai, I just published multi-assert, which allows you to use multiple assertions in the same test case and get feedback on all of them.  https://github.com/jamesmortensen/multi-assert

I do think there is a use case for multiple assertions, but please do look carefully at your tests to make sure you don't actually have two distinctly separate test cases in a single test block. Separating may be better in some cases,  but in others where multi-assertions are needed, I hope this library is helpful.

**Comment by Munter** [comment]
A different option from attempting multiple assertions, is to expand the scope of your single assertion. Given the right assertion library you can do partially exhaustive assertions on deeply nested objects, like a DOM-node in the OP.

Here is how I would do that with [unexpected-dom 'to satisfy'](https://unexpected.js.org/unexpected-dom/assertions/DOMElement/to-satisfy/):

```js
expect(domNode, 'to satisfy', '<button class="btn btn-primary"> Add Project </button>'
```

You will get much better error messages when your assertion fails with the full context available.

Similary, for the http testing use case @jamesmortensen describes above, [unexpected-http](http://unexpected.js.org/unexpected-http/assertions/object/to-yield-response/) gives fantastic errors with an overview of the full context of the response
