### ISSUE TITLE
Clarify timeout message

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#2294]
We should consider updating the timeout error message from "timeout of [time] exceeded. Ensure the done() callback is being called in this test." to something like "timeout of [time] exceeded. Ensure the test completes within [time] or increase the timeout set, and ensure the done() callback is being called when this test completes." The current message makes it sound like the problem is forgetting to call `done` even when the problem is simply that the test took too long or that some asynchronous action never got called back.

**Comment by dasilvacontin** [comment]
We added "Ensure the done() callback is being called in this test." because the most common issue is that people don't know `done` exists or forget to use it. Problem is that if you return a Promise then there's no such thing as `done`.

I agree that this could use a rewording. `timeout! Test didn't complete within [time]. For async tests, make sure you are calling 'done' or that the returned Promise eventually resolves.`

We could even use a different message depending on whether a Promise is returned or not, which would be more user friendly.

**Comment by ScottFreeCode** [comment]
> The current message makes it sound like the problem is forgetting to call  done  even when the problem is simply that the test took too long...

I still think this is an issue. See for example https://github.com/mochajs/mocha/issues/2025#issuecomment-327797643 and https://github.com/mochajs/mocha/issues/2025#issuecomment-328000439, or #2958

**Comment by Munter** [comment]
Maybe we need to write a good faq on this and change the error message to contain a link to it. it's to much for a single error message. We'd need to both explain about error conditions using async `done`, promises, async functions and increasing an individual tests timeout

**Comment by boneskull** [comment]
yes, rewording as @dasilvacontin suggested would be good.  even better would be providing links to documentation that further explains the error, like angular or [nps](https://npm.im/nps)
