### ISSUE TITLE
Q: CLI grep regex behavior?

### ISSUE THREAD

**Issue by simov** [mochajs/mocha#2360]
``` js
it('hey', () => {})
```

``` bash
$ mocha test.js 
# _mocha /(?:)/


  ✓ hey

  1 passing (6ms)

$ mocha test.js -g hey
# _mocha /hey/


  ✓ hey

  1 passing (5ms)

$ mocha test.js -g ^hey$
# _mocha /^hey$/


  0 passing (0ms)
```

Is this the expected behavior?

**Comment by simov** [comment]
Oh wow, so it seems that there is an empty space before the string:

```bash
$ mocha test.js -g '^ hey$'
```

**Comment by gurdiga** [comment]
It looks like @simov is right in that the space at the beginning is now necessary to get the match. 😳  This seems to be caused by a mix of things that we have in version 2.5.3: `-g` [applies](https://github.com/mochajs/mocha/blob/v2.5.3/lib/runner.js#L489) the given regexp to the test’s **full title**, which is `it`’s description + containing `describe`’s description. In this particular case because the `it` block is in the top level suite which [has an empty title](https://github.com/mochajs/mocha/blob/v2.5.3/lib/mocha.js#L85), the test full title [becomes](https://github.com/mochajs/mocha/blob/v2.5.3/lib/runnable.js#L176):

`'' + ' ' + 'hey'`, and so ```' hey'```. 🙃

One thing that first surprised me is that we match the full title. Thinking some more about it though, I think it makes good sense in many cases. For example in an average test suite, there could easily be more than one `it` block that says for example `it('is serializable', ...)` or `it('handles nulls', ...)` or some other general thing like that. 🤔

So, it looks like the current behavior quite sensible, and so we could probably attack the confusion from the documentation side, maybe changing the option description from:
```
    -g, --grep <pattern>                    only run tests matching <pattern>
```
to
```
    -g, --grep <pattern>                    only run tests having full title matching <pattern>
```
and maybe add a note somewhere about what “full title” means. 🤓

What do you guys think?

/cc @simov

**Comment by simov** [comment]
That won't work too:

```js
escribe('test', () => {
  describe('', () => {
    it('hey', () => {
      
    })
  })
})
```

```bash
$ mocha test.js -g 'test hey'


  0 passing (2ms)
```

Can the implementation be a bit smarter and add empty space only if there is a title?

**Comment by gurdiga** [comment]
@simov Hm… I think you have a point. 🤔

This should be trivial change (even for me as a newcomer here), and I wouldn’t expect it to break anyone’s scripts involving Mocha, mainly because I wouldn’t expect someone to have `describe` blocks with empty descriptions. 😆

So I’d be glad to take on this task. 😇  So far I see two things:
1. adjust the logic in `Runnable.prototype.fullTitle` to skip parent’s full title if it’s empty;
2. adjust the `-g` option’s documentation to mention that it is about test’s full title.

@mochajs/core What do you guys think? 🤓

**Comment by boneskull** [comment]
@gurdiga @simov Before doing anything here, you will want to compare this with the behavior in v3.0.0-1 (`npm install mocha@beta`).

**Comment by gurdiga** [comment]
@boneskull It looks like this is reproducible with v3.0.0-1 too.

**Comment by boneskull** [comment]
@ScottFreeCode I feel like you had your fingers in this semi-recently... unassign from yrself if not

**Comment by juergba** [comment]
With current master all three commands do run the test "hey" as expected.
- `mocha test.js`
- `mocha test.js -g hey`
- `mocha test.js -g ^hey$`
