### ISSUE TITLE
Compiler not using Babel Plugins?

### ISSUE THREAD

**Issue by alycda** [mochajs/mocha#2408]
Shouldn't Mocha be able to compile presets AND plugins?

[Plugin](https://www.npmjs.com/package/babel-plugin-version-inline)

```` json
{
  "presets": [
    "es2015"
  ],
  "plugins": [
    "version-inline"
  ]
}
````

`$ mocha --compilers js:babel/register`

`Uncaught ReferenceError: __VERSION__ is not defined`

**Comment by ScottFreeCode** [comment]
As far as I'm aware, Mocha doesn't know about *any* Babel settings, it just calls Babel and Babel looks for these settings; if so, this is *probably* a Babel issue rather than a Mocha one (assuming Babel gets plugins from `.babelrc` -- that's what that Version plugin's readme seems to imply...). Could you double-check that Babel is finding these settings at all (e.g. before using `__VERSION__`, use something that won't compile without the preset), and that Babel finds the plugin when run without Mocha?

Thanks!

**Comment by alycda** [comment]
That's the interesting thing, I don't have to even tell mocha to use the compiler, it was running fine on this without the `--compile` flag (as long as I don't use anything other than es2015)

````javascript
/**
 * @file Entry Point
 * @author Alyssa Davis <alyda@me.com>
 *
 * @module index
 */
define(()=> {

    /** This is a constant */
    const CONSTANT = 'Hello';

    /**
     * A module.
     * @constructor
     */
    var myFunc = ()=> {
        /** @access private */
        /* istanbul ignore next */
        let _world = 'World';

        /* istanbul ignore next */
        console.log(`${CONSTANT} ${_world}`);
    };

    return myFunc;
});
````

```` javascript
describe('Index.js', ()=> {
    let require = requirejs,
        Subject;

    beforeEach('require' ,done=> {
        require(['js/index'], Module=> {
            Subject = Module;
            done();
        });
    });

    afterEach('cleanup', ()=> {
        for (var module in require.s.contexts._.defined) {
            require.undef(module);
        }

        Subject = undefined;
    });

    it('is a function', ()=> {
        expect(Subject).to.be.a('function');
    });
});
````

My current workaround is to just run Mocha on my dist files rather than src.

**Comment by ScottFreeCode** [comment]
Hmm, so that seems consistent with my hunch that Babel isn't actually finding its settings when run through Mocha -- if Node is handling the ES2015 and Babel isn't doing anything, then that would explain why Babel isn't handling the plugin. To my knowledge Node has support for most of ES2015's features (the only one I know it doesn't have off the top of my head is `export`/`import`). Maybe try using `export`/`import`? What's you're directory structure look like in terms of where you run Mocha from, where you run Babel from and where Babel's configuration is located?

**Comment by alycda** [comment]
it's actually here on [GitLab](https://gitlab.com/alyda-playground/babel-requirejs-jsdoc-mocha-chai-istanbul)

mocha and babel are run from the root, but mocha looks inside src/js/spec for tests rather than a root folder test

**Comment by ScottFreeCode** [comment]
Well, I downloaded that, added "version-inline" to the plugins in `.babelrc`, installed `babel-plugin-version-inline`, installed `mocha`, changed `"Index.js"` in `src/js/spec/index.js` to `"Index.js " + __VERSION__`, and tried these two commands:

`npm test -- --compilers js:babel/register`
> Error: Cannot find module 'babel/register'

`npm test -- --compilers js:babel-register`
>  Index.js 0.1.0
>    √ is a function
>
>  1 passing (108ms)

Also tried adding `--compilers js:babel-register` to the `test` command in `package.json` and got the same successful result.

So, I'm still not sure what went wrong for you, but if nothing else this confirms Babel will use the plugin. Let me know if there's anything more I can troubleshoot.

**Comment by alycda** [comment]
I'm sorry, clearly it was that forward slash instead of a hyphen. 

I grabbed the code from [here](http://jamesknelson.com/testing-in-es6-with-mocha-and-babel-6/), which was using a forward slash in the command.

I appreciate your help.
