### ISSUE TITLE
browser mocha globals

### ISSUE THREAD

**Issue by mkastner** [mochajs/mocha#2431]
In browser mocha, how can I access the items, defined in mocha.globals?

```
    var myVar = {var: 'var'};

   mocha.globals(['myVar']);
```

I've tried all of these in my test and I am running out of ideas:
-   myVar
-  window.myVar
-  mocha.myVar
-  mocha.options.myVar
-  mocha.options.globals.myVar

**Comment by gurdiga** [comment]
Hey @mkastner! 🙂

> how can I access the items, defined in mocha.globals?

`mocha.globals` seems to list the names of known global variables so that it can check for global variable leaks after the tests are run. 🤓

I’m not completely sure what you mean when you say “access the items“. 😶 If I’d want to check what I have told Mocha to consider known globals, I’d do something like this:
```js
window.MyApp.knownGlobals = ['MyApp', 'myVar'];

// pass this to Mocha in its setup
mocha.globals(window.MyApp.knownGlobals);
```
Now whenever I need the list known globals somewhere else in code, I can use `window.MyApp.knownGlobals`. 😎

Maybe you can give some background around what you want to achieve. I think this would help find the right approach. 🤓

**Comment by boneskull** [comment]
Yes, I'm not quite sure what @mkastner wants to know.  What are you trying to accomplish?

**Comment by mkastner** [comment]
I apologize for my late answer.  I was misunderstanding the purpose of mocha globals. I wasn't trying to accomplish something in particular. I was just wondering about the rationale behind it.

So mocha globals' purpose it to keep track of globals and not to make any any variables global, which was my initial understanding.

Sorry again! I am herwith closing this issue.
