### ISSUE TITLE
Provide finer grained control of global variable leak detection

### ISSUE THREAD

**Issue by ghost** [mochajs/mocha#245]
It would be nice to be able to specify global names to ignore within the source file, rather than on the command line. My makefile does one run of mocha on several source files. One of these has a leak in a third party module for the variable named 'result'. I'd rather not exclude that variable for all test files, and I'd rather not have to modify my makefile to run mocha separately on different files.

**Comment by danielstjules** [comment]
It can sort of be done using private properties, though it needs to be invoked from the context of each runnable... which is also unfortunate. For example:

``` html
<html>
<head>
  <meta charset="utf-8">
  <title>Mocha Tests</title>
  <link rel="stylesheet" href="mocha.css" />
</head>
<body>
  <div id="mocha"></div>
  <script src="mocha.js"></script>
  <script>mocha.setup('bdd')</script>
  <script>
    describe('ignore leaks', function() {
      after(function() {
        delete window.foo;
      });

      it('ignored!', function() {
        this._runnable.globals(['foo']);
        window.foo = 'global';
      });
    });

    describe('detect leaks', function() {
      it('detected!', function() {
        window.foobar = 'global';
      });
    });
  </script>
  <script>
    mocha.checkLeaks();
    mocha.run();
  </script>
</body>
</html>
```

![screen shot 2015-03-14 at 7 51 26 pm](https://cloud.githubusercontent.com/assets/817212/6654462/8f675bc4-ca83-11e4-8ef6-897df4a4b356.png)

Not something that I'd recommend, but could be another quick alternative. In order to improve on this, both mocha.globals and runner.globals would need to be updated such that we could overwrite ignored globals on the fly.

**Comment by boneskull** [comment]
nobody seems interested in picking this up.
