### ISSUE TITLE
Unittests fail in node 6.5.0

### ISSUE THREAD

**Issue by palortoff** [mochajs/mocha#2467]
With Node 4 unittests fail:

 1) Suite .beforeAll() wraps the passed in function in a Hook adds it to _beforeAll:
 2) Suite .afterAll() wraps the passed in function in a Hook adds it to _afterAll:
 3) Suite .beforeEach() wraps the passed in function in a Hook adds it to _beforeEach:
 4) Suite .afterEach() wraps the passed in function in a Hook adds it to _afterEach:

All have a similar Error:
`AssertionError: expected '"before all" hook: fn' to be '"before all" hook'`

Reason:
In node 6.5.0 anomynous functions have a name when assigned to a variable:

```
var myFunc = function(){};
console.log(myFunc.name); // ->  'myFunc'
```

Prior to node 6.5.0 the function name would be empty

**Comment by palortoff** [comment]
Fixed with #2468

**Comment by ScottFreeCode** [comment]
I have to say I'm a bit surprised by the Node change in the first place; did this change in the ECMAScript standard and I missed it? (With my focus on portable browser programming I miss a lot of cutting-edge things, so I'm not exactly going to be shocked if so, I'm just wondering.) I'm also marginally surprised it wasn't considered semver-major -- I can see where they might expect that nobody is actually relying on certain functions being literally anonymous for behavioral differences and thus more functions having names could be seen as a positive, but technically it's a deviation from the documented way functions get named up till now. (The way I see it, and I would contend the actual standard agrees with me, SemVer is primarily about API contracts [in the code sense; and hence the standard's focus on documentation] and not whether a change happens to actually break anything [which goes almost unmentioned in the standard]. Every change is going to happen to break something, but having an documented contract allows you to determine *which code is incorrect by the specification and should be fixed*.) Also, while I can see it being helpful for people who want to use the new arrow syntax for its own sake, I wonder if there are edge cases where the whole reason somebody assigned an anonymous function to a variable instead of using a function declaration statement is because the variable and the function aren't meant to be that tightly coupled? I guess I'd have to know more about exactly what cases Node treats as no longer anonymous.

Not that it matters much in practice; if Node decided to make all functions have the name "foobar", we'd probably need to support it.

**Comment by Munter** [comment]
These are the v8 release notes: http://v8project.blogspot.dk/2016/04/v8-release-51.html

> Function names inferred for function expressions are now typically made available in the name property of functions, following the ES2015 formalization of these rules.

We hit the same problem in unexpected: https://github.com/unexpectedjs/unexpected/commit/a69540ebcb2b4cd3ffa29bf031572ad8abeebf58

**Comment by ScottFreeCode** [comment]
Huh, so that actually is standard. Now I know!

**Comment by from-nibly** [comment]
Dang this actually is a big change for my dependency injection library that has precedence higher for the name of the function than it does for a passed in name. Now the name of the variable you assign to it becomes the `func.name` property...
