### ISSUE TITLE
browser tests should cleanup after themselves

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2488]
Currently we have to build Mocha (I think) to use it with `karma-mocha`.  But after the tests are complete, we tend to have a modified `mocha.js`.

Solution:  modify the `clean` target to `git checkout -f -- mocha.js` instead of `rm -f mocha.js`.

I _hope_ that works in Windows.

**Comment by ScottFreeCode** [comment]
That `git` command seems to work fine on Windows as far as I can tell.

**Comment by ScottFreeCode** [comment]
This was a neat idea, but apparently at some point we opted for the `BUILDTMP` folder instead, perhaps to ensure that if the cleanup were missed due to failing tests everything would remain OK (and we could then look at the BUILDTMP file from the failed tests if needed for investigation). Feel free to reopen if this issue is still needed for any reason.
