### ISSUE TITLE
Can't run tests on Browser

### ISSUE THREAD

**Issue by Nex76** [mochajs/mocha#2497]
Hello,

For the last few days I've been trying to run Mocha tests on Browser. [Following the documentation](https://mochajs.org/#running-mocha-in-the-browser) I have an "Require not defined" issue. After trying several things I was able to do it with Chai, but the tests don't run (I have 0 passed, 0 fails, etc).

index.html (in the test folder)
```html
<html>
<head>
  <meta charset="utf-8">
  <title>Mocha Tests</title>
  <link href="https://cdn.rawgit.com/mochajs/mocha/2.2.5/mocha.css" rel="stylesheet" />
</head>
<body>
  <div id="mocha"></div>
  <script src="https://cdn.rawgit.com/mochajs/mocha/2.2.5/mocha.js"></script>
  <script src="../chai.js"></script>
  <script>mocha.setup("bdd")</script>
  <script src="test.js" type="text/javascript"></script>
  <script>
    mocha.run();
  </script>
</body>
</html>
```

test.js (in the test folder)
```
var expect = chai.expect;
expect(1).to.equal(1);
```

Is this a bug?

Thanks.

**Comment by ScottFreeCode** [comment]
If that's your whole test.js, then you're not actually defining any test functions in it. `expect` is just an assertion; it throws if the assertion is false, but it doesn't define a test for that assertion error to fail (I believe that if you change it to `expect(1).to.equal(2)`, open your browser's developer tools and reload the page you'll see that the error is simply uncaught, since it runs in top-level code outside Mocha's test functionality). See e.g. the [bdd interface](https://mochajs.org/#bdd) section for an example of actual tests, or start at the top of the documentation for info on writing tests in general (the browser section doesn't repeat anything about test writing, just gives an example of how to set up the HTML to run them on a page once you have the tests).

I don't see anything in particular in the documentation or in your example here that would cause an error due to require not being defined. I do know that the browser environment does not, by default, have `require`, so if you tried to use it in writing your test it would not work in the browser unless you used some kind of bundler to process the file(s). Note in particular that while Mocha [allows you to `require` its interface functions](https://mochajs.org/#require), you don't have to unless you really want to avoid Mocha's default behavior of adding them to the global namespace (which occurs before the tests are loaded in normal commandline usage and when the `mocha.setup("<interface>")` function is called in browser usage).

(P.S. GitHub issues tip: use \`\`\` instead of \` for multiline code snippets; [see "code" under the markdown examples](https://guides.github.com/features/mastering-markdown/#examples).)

**Comment by Nex76** [comment]
Hello ScottFreeCode, thanks for your answer.

The problem is that I can't use require - as you said -, I get the "_require is not defined_" error. If I don't use require (like my chai example) I get "_describe is not defined_".

(This is what I'm trying)
```
var assert = require('assert');
describe('Array', function() {
  describe('#indexOf()', function() {
    it('should return -1 when the value is not present', function() {
      assert.equal(-1, [1,2,3].indexOf(4));
    });
  });
});
```

What should I do to run tests on browser? Do I have to use a bundler like you said? Why it isn't in the documentation? Or it is?

**Comment by ScottFreeCode** [comment]
*If* you've put `mocha.setup("bdd")` before the `script` tag that pulls in your test file, `describe` *should* be defined without using `require`, since `describe` and the like are supposed to be set up by choosing the BDD interface (before the test files try to use that interface). Can you double-check that and, if it's correct but is still saying `describe` is not defined, put up a minimal complete example that reproduces the issue "describe is not defined" issue?

**Comment by Nex76** [comment]
So, I changed the computer and this works fine:

```html
<html>
<head>
  <meta charset="utf-8">
  <title>Mocha Tests</title>
  <link href="https://cdn.rawgit.com/mochajs/mocha/2.2.5/mocha.css" rel="stylesheet" />
</head>
<body>
  <div id="mocha"></div>

  <script src="https://cdn.rawgit.com/mochajs/mocha/2.2.5/mocha.js"></script>
  <script src="../chai.js"></script>
  <script>mocha.setup('bdd')</script>
  <script src="test.js" type="text/javascript"></script>

  <script>
    mocha.run();
  </script>
</body>
</html>
```

And the test:
```
var expect = chai.expect;

describe('Array', function() {
    it('should return -1 when the value is not present', function() {
      expect(1).to.equal(1);
    });
});
```

Thanks!!

**Comment by ScottFreeCode** [comment]
Glad I could help you get it worked out!
