### ISSUE TITLE
.only does not respect hierarchy in mocha 3.x

### ISSUE THREAD

**Issue by furstenheim** [mochajs/mocha#2498]
I don't know if this is intentional, but I could not find it in the changelog.
In version 2.x if there was an upper level with the tag .only then all the childs would run. For example in:

    var assert = require('assert')
    describe.only('First level', function () {
        describe('Second level a', function () {
           it('Third level a', function () {
               assert.equal(1,1)
           })
           it('Third level b', function () {
               assert.equal(1,1)
           })
        })
        describe('Second level b', function () {
            it('Third level c', function () {
                  assert.equal(1,1)
            })
            it.only('Third level d', function () {
                assert.equal(1,1)
            })
        })
      })

All the four tests would be run. This is very nice in some scenarios, for example, forcing all tests to be ran in the CI tool even if I forget a .only tag in one of the children.

However, this is no longer the case in Mocha 3.0.2, now only the test "Third level b" is ran. Is there a way to go back to the previous behaviour?

**Comment by ScottFreeCode** [comment]
Mocha should still work with hierarchies. Your example has multiple `only`s, which was undefined behavior in Mocha 2.x (in practice, it usually ignored all but one `only`, but I don't know if which one it used was predictable), whereas there are at least a few ways multiple `only`s are allowed in 3.x. This is covered in the relevant section on mochajs.org: https://mochajs.org/#exclusive-tests Notably:
>But *tests will have precedence*:
>
>```js
>describe('Array', function() {
>  describe.only('#indexOf()', function() {
>    it.only('should return -1 unless present', function() {
>      // this test will be run
>    });
>
>    it('should return the index when present', function() {
>      // this test will not be run
>    });
>  });
>});
>```

This is the case demonstrated in your example, since "Third level d" has `only` on `it`.

If you want all four of those to run, just use `only` on the suite and not on any of the tests.
