### ISSUE TITLE
steal ES5 shims from somewhere else

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2504]
Our shims (in `lib/utils.js`) probably miss quite a few edge cases.

[es5-shim](/es5-shims/es5-shim) has better--and more thoroughly tested--implementations.

But we can't monkeypatch globals, so we can't just throw this in.  We'd have to isolate the implementations somehow.

**Comment by ScottFreeCode** [comment]
It'd be cool if [es5-shim](https://github.com/es-shims/es5-shim) itself were broken up into the actual functions (for use by cases like ours) and an automatic polyfill patching them into the objects (as it does now, so backwards-compatible). Then we could just pull in the former part as a regular dependency, rather than trying to maintain our own copy that extracts the functions yet has to be kept up to date with relevant changes while ignoring any changes that don't affect the actual function implementations.

**Comment by Munter** [comment]
Isn't it about time to not shim and write a piece of documentation that the developer doing browser testing in old browsers needs to add the shims themselves?

**Comment by ScottFreeCode** [comment]
I typically figure libraries should leave polyfilling up to the end application code, but I think test libraries are an exception. Specifically, we don't want a project testing non-library code (and thus not relying on downstream users to provide polyfills) supplying polyfills to the test runner that would make it impossible for testing to catch errors due to lack of those polyfills in production. (Notably, that's an issue regardless of *who* supplies the shims/polyfills; it comes down to whether they're supplied by patching anything global such as object prototypes that would affect both the test library and the code being tested.) At least, that was what I thought the reason for internally using (non-patched) shims in a testing library is.

Also, I believe IE7 doesn't support patching prototypes, although I don't know how much that matters.

**Comment by boneskull** [comment]
> Isn't it about time to not shim and write a piece of documentation that the developer doing browser testing in old browsers needs to add the shims themselves?

We don't do global shims--we have a bunch of internal, handrolled ones, which suck--so this is the case as it currently stands.  Just probably no explicit documentation.

**Comment by boneskull** [comment]
My terminology is probably not correct, but what I'm trying to say is that we have our own implementations of `Array.prototype.reduce()`, `Array.prototype.forEach()`, etc., which should be replaced with something better.  But patching globals is a no-no either way.

**Comment by Munter** [comment]
I guess we could pull in the separated underscore functions that do about the same thing then. They would be required explicitly and thus not leak out and polyfill globals

**Comment by ScottFreeCode** [comment]
Really, any dedicated source of such shims that doesn't patch the globals would do.

For what it's worth, regarding es5-shim I found https://github.com/es-shims/es5-shim/issues/175#issuecomment-37774949 and https://github.com/es-shims/es5-shim/issues/276#issuecomment-69117766 basically indicating that the sort of setup we'd need is or was in the works, but (according to the last comment on the former) is blocked on [getting a unified testing browser page](https://github.com/es-shims/es7-shim/issues/8) of some sort for the modularized version.

**Comment by btd** [comment]
It maybe makes more sense to use [core-js](https://github.com/zloirock/core-js). It is more like ponyfill and do not pollute globals.
