### ISSUE TITLE
Default test directory with non-global mocha installation

### ISSUE THREAD

**Issue by RyanMcDonald** [mochajs/mocha#2515]
I am trying to write an npm script in my `package.json` to run a bunch of pre-test tasks followed by my `mocha` unit tests. I want the caller to be able to specify which paths `mocha` will run. This is how it's currently implemented, which works correctly if I want to run all tests in my `test` directory.
```json
"test": "eslint && gulp db:prepare_test && istanbul cover _mocha ./test"
```
If I want to specify a single test or directory for mocha to run, I can do this:
```json
"test": "eslint && gulp db:prepare_test && istanbul cover _mocha --"
```
and then call it like this:
```
npm test ./path/to/specific/test.js
```
The second form should, theoretically, support both the default case and the specific case. So if I don't specify a path, it will default to the `test` directory. However, the default case does not work, and results in 0 tests being executed.

I'm going to assume this is because I'm not using the global installation of mocha, so the `node_modules` version in my project doesn't know where to look for the default `test` directory to run. If that's the case, I guess this can be filed as a bug?

**Comment by ScottFreeCode** [comment]
- Consider "pretest" ([which is run before "test" automatically](https://docs.npmjs.com/misc/scripts)) for your pre-test tasks, if for no other reason than to help narrow down issues like this. I'd guess anything before the final `&&` can/should be moved there.
- Mocha is designed to be run from a local install, because it's used heavily in continuous integration; if anything, global installation is not deliberately supported and is potentially hazardous (e.g. having two installs can interfere with each other in subtle ways, or you can call the wrong version when running manually).
- Mocha's default test directory is `test` and it will find it if you really are running the local version and nothing else is interfering, as this is the normal way Mocha is used with such a folder.
- I don't know what happens if you use `_mocha` instead of `mocha`; the former is, if I'm not mistaken, an artifact of how some technicalities are handled while the latter is typically intended for actual usage (`mocha` will run `_mocha` with some additional wrapping/configuration that could be relevant here).
- Try an NPM script that runs Mocha directly, or running the local instance of Mocha yourself, instead of the version augmented with `istanbul`, in order to confirm that it isn't an issue with correct usage of the `istanbul` augmentation.
- Do you have a `test/mocha.opts` file that could be interfering?

**Comment by RyanMcDonald** [comment]
@ScottFreeCode Thank you for the detailed response! It led me to discover the real problem, which  wasn't so much a problem as a misunderstanding.

I had a `mocha.opts` file which had this line:
```
--require test/globals.js test/setup_test.js
```
I assumed this was requiring both files, which allowed me to declare global `beforeEach` and `afterEach` hooks in `setup_test.js`. But what it actually does is tell mocha to run the `setup_test.js` file, overwriting the default test path.
