### ISSUE TITLE
use appropriate error messaging when timeouts occur in synchronous or Promise-returning runnables 

### ISSUE THREAD

**Issue by ckedwards** [mochajs/mocha#2521]
Occasionally on our Jenkins server we get the following error on synchronous tests:

```
timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

This message does not make sense to the user since it is a synchronous test which has no done callback.

It looks like Runnable's done() is always called, even in the sync case. (When there is no done function parameter and no Promise is returned). The issue is the following code inside done()

```
if (!err && self.duration > ms && self._enableTimeouts) {
  err = new Error('timeout of ' + ms + 'ms exceeded. Ensure the done() callback is being called in this test.');
}
```

Is it expected for done to throw an error in this case? If so it would be nice to have an option to only warn when the timeout was exceeded. Otherwise it is just a bug that needs to be fixed. I don't mind making a PR but I'm not sure what is expected.

**Comment by ScottFreeCode** [comment]
I believe (though I'd have to double-check with the more veteran team members to be certain) that timeout errors for synchronous tests are intentional, but the message needs to be fixed; this also overlaps potentially with various ongoing work in the area of how to properly report timeout issues with promise-based tests, which in turn overlaps with ongoing work in the area of how to handle tests using both promises and `done` to report completion. /cc @mochajs/core

**Comment by boneskull** [comment]
- The error is intentional.
- To avoid timeout errors, use `--timeout` or use `this.timeout(number)` in a `beforeEach()` or `before()` block.
- The error text is incorrect in the case of synchronous runnables.  This is likely due to the fact it's generally *asynchronous* tests which timeout.   Should be modified to something like simply "Timeout of 2000ms exceeded" if the runnable is *not* asynchronous.
- Related, this should be corrected for Promises which are returned from runnables, but not fulfilled before the timeout.
- When I say "runnables", I mean tests or hooks.  This behavior should be consistent for both.

**Comment by juergba** [comment]
This issue is outdated. The actual error message is:
`Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.`
