### ISSUE TITLE
Moving test files with a mocha.opts file

### ISSUE THREAD

**Issue by MatthewKosloski** [mochajs/mocha#2522]
I want to move my test files and put them next to my React code.  `Foo` is a React component and `index.js` is the component file, and `Foo.spec.js` is my test.

_An example of my file structure:_

	root-folder
		src
			components
				Foo
					Foo.spec.js
					index.js
		test
			mocha.opts

_mocha.opts:_

	src/components/**/*.spec.js
	--recursive

This options file isn't working as expected.  I don't even know if I'm doing it correctly.  There isn't really any documentation on this file.  When I run it, I get this error:

	Error: Cannot find module '../../src/components/Foo'

_Here is my current test script:_

	"test": "mocha --recursive --require babel-register --require ignore-styles || true"

I need to use ignore-styles because I am using CSS modules with Webpack.

**Comment by ScottFreeCode** [comment]
Some helpful side points:
- You shouldn't need `--recursive` with a glob with `**`
- You shouldn't need to repeat anything both in the command and in `mocha.opts`
- I haven't reviewed the documentation for it lately, but `mocha.opts` is pretty simple: everything in it is treated as though it were among the commandline arguments.

Now to the main issue here: if that path isn't in your opts file or your command, and it's relative like it's backing out of some other directory (such as the `test` directory) in order to find the source directory, and seems to be trying to point to the source files... I am guessing this is in your test files' imports/requires and is the path from the test files to the source files that just needs to be updated since you moved the test files. In fact, if the test files are now in the same directories as the corresponding source files, I'd expect most of them could be changed from `<one or more ../>/src/<zero or more folders>/<source file>` to just `./<source file>` (e.g from `../../src/components/Foo` to just `./Foo`).

**Comment by boneskull** [comment]
agreed. please check to ensure your relative paths are correct.  use a glob *or* `--recursive`; not both.
