### ISSUE TITLE
Can't see how retried test failed before passing.

### ISSUE THREAD

**Issue by JustinRainwater** [mochajs/mocha#2529]
It would be great when using the retries feature if I could get the exception and stack trace info on the failed attempts before it eventually passes. 

Currently it looks like `this.currentTest.err` remains undefined unless the last retry is a failure. Instead when going through `afterEach()` before retrying the test I'd like to be able to log the contents of `this.currentTest.err`.

**Comment by JustinRainwater** [comment]
Playing around locally it looks like this could be resolved just by adding `test.err = err` after this line: https://github.com/mochajs/mocha/blob/master/mocha.js#L5039

**Comment by boneskull** [comment]
It might be difficult to do this in a way that works with all of the reporters.  Which reporter are you using?

**Comment by JustinRainwater** [comment]
I wouldnt expect this to work with any reporters unless we created a new state like "Passed After Retry" to go with Passed and Failed. I'm just console logging this info so I can parse it in Jenkins console output. I originally wanted to differentiate retried tests in the reporter but that doesnt seem possible.

To answer your question we're using https://github.com/juhovh/mocha-jenkins-reporter when running on jenkins and when running locally we just write to console. I'm not sure if that is default spec reporter or what.

If we wanted this to work in reporters then I could imagine test.err being an array where each index would store the error output for a specific retry so the reporter could dump all of the errors related to the retries. I'm not sure that is all worth it though. It makes sense that the reporter would report the ultimate result of the test "Passed/Failed" and then within the test run we can log details related to tests passing after retry.

**Comment by LToronto** [comment]
I also need this feature for a custom reporter.
see https://github.com/mochajs/mocha/pull/2901

example:
runner.on('test', function (test) {
    if(test._currentRetry > 0) {
      reportErr(test, test.retryErr[test._currentRetry-1]);
    } 
});

**Comment by catdad** [comment]
I am also trying to take a crack at this, as it has recently come up with a large legacy test suite I am working on.

From what I have gathered, it's really up to the reporters to decide what to do with passing or failing tests. In the case of mocha and retries, the runner simply ignores the failure of a test when it is possible to retry it,  clones that test, and adds it back to the tests array to be executed again. This is a fine approach, but it completely discards the failure information, so a reporter cannot take action on it.

I think rather than having mocha do any magic to include retried test information, it should simply make that information available to reporters, allowing reporters to choose what to do with that information.

The current method being discussed has some drawbacks with some methods of testing and reporting. For example, I have a test suite that prints out a bunch of debug information as the test is running. When a test finishes, the reporter prints out the test name and indicates the pass/fail status. When the test fails, I look at the debug information for extra context. If only a single test is reported at the end of multiple retries, I will have multiple sets of that same debug information followed by a single test name and pass/fail indication. This makes looking at the extra debug info confusing. Instead, it would be best to report each try of the test separately, so it can correspond to any additional runtime logging done by tests or the reporter.

**Comment by catdad** [comment]
I added #2926 to add an event that reporters can choose to take action on.

This PR does not update any reporters, as I don't necessarily see a reason for any of the built-in reporters to report on this. And in some of the examples given above, such as the `mocha-jenkins-reporter`, it would be up that module owner to update the reporter to support this new functionality.

**Comment by ScottFreeCode** [comment]
I don't have any strong opinions for or against this feature in general, but a couple opinions I do have:
- Emitting an event on each retryable failure should allow any reporter that wants to report a different end result to save the information from the retryable failures for use on test end; thus, both reporting approaches are supported by that implementation if I understand correctly, whereas waiting till test end to report the retryable failure info with the test only supports one of the two reporting strategies. That seems like a point for #2926 as the implementation.
- I'm fine with the idea of making the feature available to custom/third-party reporters while not using it in Mocha's provided reporters, but we should really get documentation for reporter support just so down the road the difference between what we support and what we use in Mocha itself doesn't become unclear (i.e. whether we intended to support features like this). This doesn't need to hold up merging an implementation, but when we merge an implementation it'd be great to create an issue to track adding that documentation.
