### ISSUE TITLE
Unexpected behavior of skip().

### ISSUE THREAD

**Issue by yuriyKazan** [mochajs/mocha#2550]
I have resided to rewrite my test using skip() inside of before().
`describe(`Comparison... `, function() {

	xmlFilesInDir.forEach(function(file) {
		
		var docId = path.basename(file, '.xml');
		var eResponse;
		var mResponse;
		
		before(`Get data for ${docId}`, function() {
			var self = this;
			return helper.getEventsByDocId(docId).then(function(eRes) {
				if (eRes.status !== 200) {
					console.log(`Document id: ${docId}. Get Document\'s Events(s). Expected HTTP status 200 but was received ${eRes.status}. Test is skiped.`); 
					self.skip();
				}
				eResponse = eRes;
			}).then(function(){
				return helper.getMetadataByDocId(docId).then(function(mRes) {
					if (mRes.status !== 200) {
						console.log(`Document id: ${docId}. Get Document\'s Metadata. Expected HTTP status 200 but was received ${mRes.status}. Test is skiped.`); 
						self.skip();
					}
					mResponse = mRes;
				});
				});
		});		
				
		it(`Document id: ${docId}. Should...`, function(done){

			done();				
		});	

	});
});`

Where xmlFilesInDir = ["1.xml", "2.xml"] and I expect that test for 1.xml will be performed, but for 2.xml will be skipped.
But in execution I found that the Mocha are skipped the test for both documents:

_Comparison...
Document id: 2. Get Document's Metadata. Expected HTTP status 200 but was received 404. Test is skiped.
      - Document id: 1. Should...
      - Document id: 2. Should..._

If there is something that I forgot to add or the issue is not related to Mocha just let me know.

**Comment by ScottFreeCode** [comment]
Each `before` is run before the whole suite and applies to the whole suite, so when you call `skip` in any `before` it sets the whole suite to skipped. If I'm understanding correctly, you want to associate specific `before`s with specific tests? Mocha doesn't currently have a hook for that (although it does have a `beforeEach` that will run before every test instead of only once for the whole suite, but again, not test-specific `beforeEach` functions). You can, however, either move the `before` logic into the start of the test itself (since calling `skip` works fine inside tests too), or create nested suites that only contain one test each (and in which `before` and `beforeEach` are equivalent, either will run just once before the suite's one test).

**Comment by yuriyKazan** [comment]
Thank you for answering my question.
It's my fault, next example more understandable:

	var should = require("should");

	describe('Test', function() {
	  var tests = ["1.xml","2.xml","3.xml"];

	  tests.forEach(function(test) {
		  
		before ('Before test' + test, function() {
			if (test.indexOf('2') > -1) this.skip();
		});
		it('test1', function(done) {
		  done();
		});
		it('test2', function(done) {
		  done();
		});
		it('test3', function(done) {
		  done();
		});	
	  });
	});

  I want to run the test suite for each value from the array if this value meets a certain logical value, but if not then skip run the test suite. In other words tests 'test1', 'test2', 'test3' should be executed for "1.xml" and "3.xml", and skipped for "2.xml". But by some reason all execution are skipped.

	d:\dir>node node_modules/mocha/bin/mocha --version
	3.1.2

	d:\dir>node node_modules/mocha/bin/mocha test.js


	  Test
		- test1
		- test2
		- test3
		- test1
		- test2
		- test3
		- test1
		- test2
		- test3


	  0 passing (44ms)
	  9 pending

**Comment by ScottFreeCode** [comment]
Aaaaah, ok -- the problem is you're only creating one suite total, not a suite for each `.xml` entry, so your `before` condition skips that one whole suite rather than just the suite for that specific `.xml` (because there is no suite just for that specific `.xml`). You want this:
```js
describe('Test', function() {
  var tests = ["1.xml","2.xml","3.xml"];

  tests.forEach(function(test) {
    describe(test, function() {
      before (function() {
        if (test.indexOf('2') > -1) this.skip();
      });
      it('test1', function(done) {
        done();
      });
      it('test2', function(done) {
        done();
      });
      it('test3', function(done) {
        done();
      });	
    });
  });
});
```
(The important thing here, btw, is the `describe` inside the `forEach`, not what's in any of the names; Mocha only uses the names of suites, tests and hooks in printing the results, not for any association between them.)

**Comment by yuriyKazan** [comment]
OMG, how I missed it. You are right in 100% percent. Thank you for helping me.
Definitely, it is not an issue.

**Comment by ScottFreeCode** [comment]
👍 You're welcome! Glad we got it figured out.
