### ISSUE TITLE
Stuck at bootstrap_node.js:509:3

### ISSUE THREAD

**Issue by nevethlexfiend** [mochajs/mocha#2551]
<img width="550" alt="myscreenshotname 2016-10-22 at 11 46 57 am" src="https://cloud.githubusercontent.com/assets/8331719/19617107/4cb21c12-984d-11e6-8844-738a7b535715.png">

**Comment by ScottFreeCode** [comment]
This doesn't look like it has to do with Mocha.

For future reference, it's helpful when opening an issue on a project to provide a brief description of what you're trying to do and minimal code that will trigger the error rather than just the error message by itself, and using text (even if merely copy-pasted) instead of an image allows the issue to come up in searches and be meaningfully viewed in email notifications.
