### ISSUE TITLE
Support for reporting both to console and a file?

### ISSUE THREAD

**Issue by jeversmann-civitas** [mochajs/mocha#2558]
Is there an easy solution for running a spec reporter while also writing out an xunit.xml?
https://www.npmjs.com/package/reporter-file seems built for that, but since it's a little old I was wondering if there's another way.

(Opening this as an issue since I didn't get a response in Gitter.)

**Comment by ScottFreeCode** [comment]
Looks like there are plans to support multiple reporters, which I imagine overlaps with this (since multiple reporters on the console would not really be helpful): #2184 That apparently was put off till after more pressing changes (better browser testing, v3.x release) and needs to be picked back up now that those are done...

**Comment by boneskull** [comment]
dupe of #2184
