### ISSUE TITLE
ES6 mocha.opts return error

### ISSUE THREAD

**Issue by carloschneider** [mochajs/mocha#2562]
When I try run my tests with mocha.opts I get this error. Not sure if it's a Mocha error.
![screen shot 2016-10-29 at 14 58 34](https://cloud.githubusercontent.com/assets/577143/19831445/fada8b9e-9de8-11e6-9ce1-b82fdee51833.png)

When I pass the parameters without using the mocha.opts the test runs normally.

**Comment by ScottFreeCode** [comment]
`mocha <filename>` means that `<filename>` is the test file, so it's getting an exception trying to parse `mocha.opts` as a JavaScript file.

Use `--opts path/to/mocha.opts` to specify the location of the `mocha.opts` file -- or leave it out altogether if the location is the default `test/mocha.opts`. (You can see from the fact that the exception is raised by Babel rather than Node's built-in parser that the `mocha.opts` file's configuration is already in effect here, for example.)

Let me know if that resolves your issue!

**Comment by carloschneider** [comment]
Holly... Nice! Thanks!
