### ISSUE TITLE
beforeEach/afterEach runs regardless of the block, before/after runs are not synchronized

### ISSUE THREAD

**Issue by lewisdiamond** [mochajs/mocha#2569]
The first part of this issue seems to be very important and there are no open issues that I've found. It's possible that it's caused by the environment I'm running this in.

The second part may be intended, but that causes problems (for example, mocking a global object and restoring it after a test will fail other tests).

```
describe('TEST1', () => {
    before(() => {
        console.log('outer before')
    })
    beforeEach(() => {
        console.log('outer beforeeach')
    })
    afterEach(() => {
        console.log('outer aftereach')
    })
    after(() => {
        console.log('outer after')
    })
    describe('inner1', () => {
        before(() => {
            console.log('inner1 before')
        })
        beforeEach(() => {
            console.log('inner1 beforeeach')
        })
        afterEach(() => {
            console.log('inner1 aftereach')
        })
        after(() => {
            console.log('inner1 after')
        })
        it('test inner1', () => {
            console.log('inner1 test')
        })
        it('test2 inner1', () => {
            console.log('inner1 test2')
        })
    })
    describe('sub-inner', () => {
        describe('inner2', () => {
            before(() => {
                console.log('inner2 before')
            })
            beforeEach(() => {
                console.log('inner2 beforeeach')
            })
            afterEach(() => {
                console.log('inner2 aftereach')
            })
            after(() => {
                console.log('inner2 after')
            })
            it('test inner2', () => {
                console.log('inner2 test')
            })
        })
    })
})
```

Outputs 
```
2016-11-01T21:40:08Z [1] INFO outer before
2016-11-01T21:40:08Z [1] INFO inner1 before
2016-11-01T21:40:08Z [1] INFO inner2 before
2016-11-01T21:40:08Z [1] INFO outer beforeeach
2016-11-01T21:40:08Z [1] INFO inner1 beforeeach
2016-11-01T21:40:08Z [1] INFO inner2 beforeeach
2016-11-01T21:40:08Z [1] INFO inner1 test
2016-11-01T21:40:08Z [1] INFO outer aftereach
2016-11-01T21:40:08Z [1] INFO inner1 aftereach
2016-11-01T21:40:08Z [1] INFO inner2 aftereach
2016-11-01T21:40:08Z [1] INFO outer beforeeach
2016-11-01T21:40:08Z [1] INFO inner1 beforeeach
2016-11-01T21:40:08Z [1] INFO inner2 beforeeach
2016-11-01T21:40:08Z [1] INFO inner1 test2
2016-11-01T21:40:08Z [1] INFO outer aftereach
2016-11-01T21:40:08Z [1] INFO inner1 aftereach
2016-11-01T21:40:08Z [1] INFO inner2 aftereach
2016-11-01T21:40:08Z [1] INFO outer beforeeach
2016-11-01T21:40:08Z [1] INFO inner1 beforeeach
2016-11-01T21:40:08Z [1] INFO inner2 beforeeach
2016-11-01T21:40:08Z [1] INFO inner2 test
2016-11-01T21:40:08Z [1] INFO outer aftereach
2016-11-01T21:40:08Z [1] INFO inner1 aftereach
2016-11-01T21:40:08Z [1] INFO inner2 aftereach
2016-11-01T21:40:08Z [1] INFO outer after
2016-11-01T21:40:08Z [1] INFO inner1 after
2016-11-01T21:40:08Z [1] INFO inner2 after
```

As you can see,  "inner1 test" is wrapped by 2 beforeEach and 2 afterEach, one coming from its own block (expected) and the other coming from the inner2 block which is not expected according to the documentation. The same problem applies for all other tests run.

Also, "inner2 before" is run right after "inner1 before", before "inner1 after" is run. This may be by design but it would be great to have a way to wrap multiple tests assuring the before and after are both run before the next test is. Without it you can't mock a global object that may be used elsewhere.

**Comment by lewisdiamond** [comment]
Disregard. The environment running my test (it's a database with V8/node built in) is causing the issue. I managed to extract the tests and run it independently.

**Comment by ScottFreeCode** [comment]
There's no design for `before` to run at any time other than the beginning of the suite in which it is declared; that looks like just the same problem `beforeEach` is having: it's as though "inner 2" were nested inside "inner 1". Additionally, I'm pretty sure the order "before outer, before inner, after outer, after inner" is wrong; it should be "before outer, before inner, after inner, after outer" (whether for `Each` versions or the whole-suite version, and where "outer" and "inner" are any two suites for which "inner" is nested inside "outer"). In other words, I believe the expected output for this code is:
```
outer before
inner1 before
outer beforeeach
inner1 beforeeach
inner1 test
inner1 aftereach
outer aftereach
outer beforeeach
inner1 beforeeach
inner1 test2
inner1 aftereach
outer aftereach
inner1 after
inner2 before
outer beforeeach
inner2 beforeeach
inner2 test
inner2 aftereach
outer aftereach
inner2 after
outer after
```

However, that's also the output I get when running it with the latest Mocha on the latest Node in a fresh project, so if that code actually did produce the output you're citing, there must be something else interfering somehow. What environment do you get this issue in, and with what all libraries (including version of Mocha), frameworks, options and settings in play? (Feel free to cut out stuff and narrow it down to as few as are necessary to make it happen -- actually, it may save us trouble, since unless there's some obvious red flag giving away what really happened the next step we're going to have to do is narrow down which particular thing or things is/are the key.)

**Comment by ScottFreeCode** [comment]
Ah, sorry, cross-posted; I was trying the code out and writing up an explanation when this got closed, I guess. Glad to hear you found the source of the issue! (And let us know if there's anything else we can do to help.)

**Comment by lewisdiamond** [comment]
Thanks for your answer, that's what I was expecting too. I reported the issue to the other repository using mocha hopefully it will be fixed soon.
