### ISSUE TITLE
Expose Mocha instances Runner

### ISSUE THREAD

**Issue by rijnhard** [mochajs/mocha#2580]
So I'm writing a custom interface thats basically the `bdd` interface.
Alongside that I have a framework that wraps mocha and basically uses it as the underlying engine. 

One of the things we do is we use the mocha specs as a predefined "behaviour" and then with the custom interface we run the same behaviour with variances. Kind of like mocha-cases but with describes and the variances are written in yaml files.

One of the big issues we have is that we have to hack a bunch of things into the interface between runs on the variances on the behaviours. 

This is pretty difficult to explain, but what I would like is the `Runner` instance that the mocha instance uses should be a property on the mocha instance instead of created on the `run` command. 

This will allow users to 
1. add custom events in the `Runner`s `EventEmitter` that will allow us to wrap mocha more easily
2. allow us to replace the `Runner` instance with our own instance

At the moment `mocha.run` returns a `Runner` instance, but at this point its too late to setup anything useful ahead of time, because the testing has already started.

**Comment by boneskull** [comment]
This issue is part of a much larger one--see #1969.  Much work has been done here, but there's *tons* more to do--and it's on hold while we address other concerns (roadmap, governance, tech debt, etc.).

Mocha is not easily extended, nor wrapped, nor can its core functionality currently be used as a library without unreasonable hacks.  Its programmatic (internal) API is not officially documented nor supported, and can break at any time.  Thus, it's not really safe to use in the manner you've described.

So for now, we can't support these types of enhancements--we need to ensure the *current* functionality is rock-solid, so we can be more confident in accepting PRs and making changes.  

A personal goal of mine is to help shape Mocha into a tool that users can easily build upon.  But it isn't the first thing that the project needs.  If you are interested in helping further, I'm interested in input on the project's roadmap--we'll publish a draft soon.

**Comment by rijnhard** [comment]
@boneskull considering our extensive use of mocha as a component in a bigger system I would most definitely want to provide feedback.
