### ISSUE TITLE
Done called, but next test never runs

### ISSUE THREAD

**Issue by delventhalz** [mochajs/mocha#2581]
I have an unconventional setup I can't change. It looks something like this:

1) test POSTs to server
2) server POSTs to blockchain
3) blockchain updates
4) syncing script updates the database

It is absolutely imperative that I do not run the next test until the test before it has completed that entire workflow, which typically takes 2-3 seconds. Here is an example of a test written for that flow with supertest and chai:

```javascript
it('should create a user', done => {
  request(server)
    .post(`${API}/signup`)
    .set('Content-Type', 'application/json')
    .send(`{
      "email":"${USER_EMAIL}",
      "password":"${USER_PASSWORD}"
    }`)
    .expect(200)
    .expect(res => {
      expect(res.body.role).to.equal('user');
      expect(res.body.id).to.match(ID_PATTERN);
    })
    .end(_wait(done));
});
```

That `_wait` function is the key issue here. If I write it very naively with a setTimeout, it _will_ work:

```javascript
const _wait = cb => () => setTimeout(cb, 5000);
```

However, this isn't a great solution since the blockchain is very unpredictable, and can sometimes take much more than 2-3 seconds. What would be much better is to watch the database for changes. Thankfully the database is written in Rethink, which provides cursor objects that update dynamically on changes. So that should be easy, and look something like this:

```javascript
var _wait = cb => () => {
  connector.exec(db => db.table('chain_info').changes())
  .then(cursor => {
    cursor.each((err, change) => {
      cb(err);
      return false;
    });
  });
};
```

This setup breaks the tests. As near as I can tell `done` _does_ get called. Any console logs in and around it fire, and the test itself is logged as completed, but the next test never starts, and eventually everything times out:

```shell
  Manager API Workflow:
    Account Creation:
      ✓ should create a user (6335ms)
      1) should login an administrator


  1 passing (1m)
  1 failing

  1) Manager API Workflow: Account Creation: should login an administrator:
     Error: timeout of 60000ms exceeded. Ensure the done() callback is being called in this test.
```

Any assistance would be greatly appreciated. I am using Mocha 3.1.2, Chai 3.5.0, Supertest 2.0.1, and Node 6.9.1.

**Comment by delventhalz** [comment]
On further examination, I think this is a rethink problem, not a Mocha one, with `cursor.each` only ever being called once. Closing the issue.

**Comment by ScottFreeCode** [comment]
A few other things you can look at to make sure your code isn't swallowing any errors or otherwise having trouble working with both the system your testing and Mocha:
- `<stuff>.end(_wait(done))` calls `_wait(done)` immediately and passes whatever it returns to `end`; since `_wait` does not return anything, it's equivalent to calling `<stuff>.end()` after `_wait(done)`. This may or may not be what you want, depending on how `end` is supposed to be used.
- Anywhere that you have promises or promise-like error-handling behavior you will need to pass `done`/`cb` to the error-handling callback, e.g. `.catch` after `.then`. Otherwise the error will never reach Mocha.
- If the DB never changes, the callback/cursor never fires, right? Ideally, there would be some way to get a signal/response from the specific DB action rather than just listening for any change, to avoid both false positives and lack of information on failure to change. (Depending on the system you're testing that might not be possible, however, in which case just keep in mind that a timeout error in the test could be caused by that particular test failing to change the DB.)
- Whatever you do work out to listen on the DB, it will need to run each test's `done` callback only once.
