### ISSUE TITLE
this.timeout is undefined

### ISSUE THREAD

**Issue by pronebird** [mochajs/mocha#2586]
Hi,

I can't increase the timeout of my tests. I get error saying that this is undefined.

```js
describe('Queue', () => {
  this.timeout(10000);
});
```

ok, arrow function. Take 2:

```js
describe('Queue', (suite) => {
  suite.timeout(10000);
```

`suite` is undefined. What's going on here and how to fix it?

**Comment by ScottFreeCode** [comment]
The fix, at this point, is not to use arrow functions for the test callbacks: https://mochajs.org/#arrow-functions (Although they're still fine used *inside* the tests, for what it's worth.) I think there's a certain amount of consensus that, if we had Mocha to do over again from the beginning with what we know now, we'd avoid using `this` and put all the behavior/configuration on a parameter passed to the test, but I don't know if it's ever going to happen given backwards compatibility. (Maybe someday, if other test runners with similar interfaces that Mocha aims to be easy to port from end up using the same approach?)

Another advantage, besides giving you access to `this`, using regular functions also avoids implicit returns, which can have surprising behavior since Mocha allows [returning promises to control test success/failure](https://mochajs.org/#working-with-promises) without an asynchronous callback.

Speaking of which, by the way, the parameter to the test function is (currently, anyway) [a callback to signal asynchronous test completion](https://mochajs.org/#asynchronous-code).

**Comment by pronebird** [comment]
Thanks for detailed answer!
