### ISSUE TITLE
Filter individual tests programmatically 

### ISSUE THREAD

**Issue by nicojs** [mochajs/mocha#2605]
For the JavaScript mutation testing framework [Stryker](https://stryker-mutator.github.io) we to be able to filter out individual tests based on its index in the entire run. The `it.only` won't work in our case, we need to do it programmatically. Is this possible? If not, is this something you would want to support? If you point me in the right direction, i can create a PR for this.

Right now, i'm using this piece of ugly magic. It works by overriding the `AddTest` method:

```javascript
var mocha = require('mocha');
var current = 0;
var realAddTest = mocha.Suite.prototype.addTest;
mocha.Suite.prototype.addTest = function () {
    if (filteredTestIds.indexOf(current) > -1) {
        realAddTest.apply(this, arguments);
    }
    current++;
};
```

However this only works for the server-side version of Mocha. Also, I'm overriding the `addTest` method, which is a kind of private interface. I would much rather have a supported way of filtering files, like `Jasmine`'s [`specFilter`](https://jasmine.github.io/edge/custom_boot.html#section-7)

If your interested in our use case: 

We measure the ability of your unit tests to identify bugs, or *mutants*. We do this by automatically inserting mutants in your source code, then rerunning your tests for each mutant. To speed things up, we first measure the code coverage per test. Once we know that, we know exactly which tests to run for each mutant. In order for this to work, we need a way to hookup into the test framework. For the code coverage we need a `beforeEach` and `afterEach` hook. Mocha got us covered here. However, we still need a way to exactly point out which tests we want to run.

**Comment by ScottFreeCode** [comment]
Would the `grep` option be sufficient? https://mochajs.org/#g---grep-pattern (This should also be available in the browser, or in programmatic usage, as a function on the `mocha` object, if I recall correctly.)

I'm not sure if it applies to this specific use case -- or whether something with a direct reference to the tests would work just as well as an index for your project -- but in the general case, I would worry that index-based behavior would be brittle due to the index of any given test changing every other time you add tests to the project or even if Mocha fails to look up files in the same order every time. Despite that issue, I'd expect people would try to use it and, when it causes problems for them, not all of them would recognise that it can't reliably do what they want it to do in the first place. So I'd actually be pretty wary of adding an official public API to do things based on index (though perhaps programmatically based on a direct reference to a specific test would be another matter).

**Comment by nicojs** [comment]
@ScottFreeCode thanks for your response.

The `grep` option does not seem sufficient to me. As far as I can see, you can only use one grep statement at a time. Maybe you could theoretically combine multiple test names, but that does not seem elegant. Also, a test name might not be unique.

Index-based running of the test is actually an implementation detail of our framework, which should indeed *not* be in the public api. What i would like is a way to filter specific tests at runtime based on a  simple function.

The API could be something like this:

```javascript
function myTestFilter(test){
   return test.title === 'my scoped test';
}
const mocha = new Mocha({ testFilter: myTestFilter });
```

**Comment by boneskull** [comment]
@nicojs Tried `this.only()`?

**Comment by nicojs** [comment]
@boneskull i don't think what will work for us. We don't want to change the tests, as we rerun the same suite multiple times while targeting different tests. It *would* work if it would be supported in a `beforeEach`. For example: this would be how to run only the even tests:

```javascript
let index = 0;
beforeEach(function() {
  if(index % 2 === 0) {
    this.only();
  }
  index++;
});
``` 

Would you be open for this change?

**Comment by boneskull** [comment]
@nicojs That behavior is supported.

**Comment by nicojs** [comment]
@boneskull this doesn't seem to work.

See: https://github.com/nicojs/mochajs-filter-tests-programmatically

```bash
git clone git@github.com:nicojs/mochajs-filter-tests-programmatically.git
cd mochajs-filter-tests-programmatically
npm i
npm test

  1)  "before each" hook for "should return -1 when the value is not present":
     TypeError: this.only is not a function
      at Context.<anonymous> (test/myTests.js:4:10)
```

**Comment by boneskull** [comment]
ahh sorry, confused myself. No, it's not supported. 

`it.only` can be called programmatically if your logic is within a suite. does that work?

**Comment by nicojs** [comment]
No sorry, that won't do for us. We want to be able to filter the tests while not altering the test suites at all (hence: programmatically).

I think this feature should be available in some way. Would you be open for a PR regarding this? In what way/shape/form? My test filter example? Or rather make this.only() work from outside a test suite? I haven't looked too much into the code, so i don't know what would be the easiest.

**Comment by boneskull** [comment]
I would not want to add `this.only` due to the numerous headaches around it and its ilk. not only is the implementation nontrivial, so is the specification. 

I would be much more interested in supporting a callback within the grep functionality. Especially if we can do it in a way that doesn't pollute the global namespace. Any ideas?

**Comment by nicojs** [comment]
Maybe something like this?

```javascript
function myTestFilter(test){
   return test.title === 'my scoped test';
}
var mocha = new Mocha({
    grep: myTestFilter
});
```

**Comment by boneskull** [comment]
I mean this:

```js
describe('something', function () {
  const test = someConditional ? it : it.only;
  
  test('my test that may or may not be the only one running', function () {
    //
  });
});
```

I can't get behind supporting `this.only()` because:

- we need [better coverage](/orgs/mochajs/projects/4) to support more features
- I haven't seen evidence of a wider need for this feature
- there's a workaround, albeit a gross one
- it makes assumptions about how many tests are running at any given time, which would annihilate anybody's far-off dreams about parallel test execution
- the "grep" callback is likely a better solution

For the forseeable future, determining whether a test runs exclusively *must* be determined prior to the first `Runnable` (hooks and tests) execution.

* * *

Regarding "grep":  

The given API only works for the limited set of users which programmatically invoke Mocha.  For 99% of Node.js users, there is no `Mocha` global; initialization is done by the CLI.  By the time you're in a test file, the train already left the station.

I've seen other libraries support `.js` config files (which I'd love to see in Mocha, eventually) where you can do this sort of thing.  This is probably the best way.  However (and this opens a can of worms)...  what if we exposed a static configuration function in the `mocha` module?

```js
// mocha.conf.js
// tests invoked via:
// $ mocha --require mocha.conf.js test/
require('mocha').setup({
  grep(runnable) {
    return /foo/.test(runnable.title);
  }
});
```

`bin/_mocha` instantiates a new `Mocha` instance pretty early, but I'm almost certain it doesn't need to (untested).  I believe we could process `--require`'d modules *before* calling `new Mocha()`, and use the options supplied in the `setup()` call.  

This would give Node.js users an easy way to do complex configuration in Mocha with very little implementation effort.  It also has parallels to browser setup.  @ScottFreeCode, how does that sound?  :smile:

**Comment by boneskull** [comment]
actually I think it's as easy as creating the function.  the runner isn't configured until later on, even if the object is instantiated.

**Comment by nicojs** [comment]
@boneskull I'm not sure i follow you exactly. I've taken a look in the `runner` and it seems like we could support a callback function in the [`grepTotal`](https://github.com/mochajs/mocha/blob/master/lib/runner.js#L129) method. Is this what you mean with

> actually I think it's as easy as creating the function. the runner isn't configured until later on, even if the object is instantiated.

?

This would not be supported at first when using the mocha cli, correct? But that shouldn't be too much of an issue. If you would later want to support a mocha config file (`mocha.conf.js`), wouldn't you also add that to the constructor options of Mocha as well (`new Mocha({ configFile: 'mocha.conf.js' })`)? The mocha CLI would than just supply that tot the mocha constructor and the `grep` callback could be supported in the config file. This way of reading the config file is also done in `karma` and `stryker`.

> there's a workaround, albeit a gross one

You mean my angy duck punching effort of changing the `addTest` method? That only works for nodejs mocha tests, not when combining it with karma and running in the browser.

**Comment by boneskull** [comment]
@nicojs no, what I'm concerned about is running with the CLI mainly.  it's trivial to use this sort of feature programmatically--there's just currently no reasonable way to run `mocha` on the command line and hand it a callback to "grep". see `bin/_mocha`.

`karma-mocha` allows you to specify options to Mocha; if we supported a function for grep then you could add it via Karma config's `client` property.

**Comment by nicojs** [comment]
> `karma-mocha` allows you to specify options to Mocha; if we supported a function for grep then you could add it via Karma config's `client` property.

No it won't. Client options get serialized using `JSON.stringify` as you can see on [lib/middleware/karma.js line 207](https://github.com/karma-runner/karma/blob/master/lib/middleware/karma.js#L207). A function doesn't survive this serialization process.

There is an other issue. With Stryker we choose to let filtering of tests be conceptually something that belongs to the `testFramework` and not the `testRunner`. The creating of the `mocha` object is done by the `testRunner`, while filtering should be done by files we load into the test runner later. An other solution would be most welcome for us.
