### ISSUE TITLE
nested tests/suites marked with .only() does not always run

### ISSUE THREAD

**Issue by villesau** [mochajs/mocha#2606]
If there is .only test in some parent scopes, nested .only might not run. There is even a test to document this behaviour: https://github.com/mochajs/mocha/blob/master/test/integration/fixtures/options/only/bdd.fixture.js#L63

I strongly believe that every suite and test marked with .only() should run, no matter how nested they are. Here is a pr which refactors the .only() logic a bit and fixes it: https://github.com/mochajs/mocha/pull/2601

**Comment by boneskull** [comment]
Thanks for the suggestion.

It's the way it is because of the ambiguity it would otherwise introduce:

```js
describe.only('suite', function () {
  it.only('test', function () {
    //
  });
  
  it('test 2', function () {
    //
  });
});
```

What should happen above?  Either way you go with this, you can't argue it isn't also completely reasonable to assume it's the opposite.  :smile:

In the current implementation, tests *always take precedence* over suites.  This behavior is **unambiguous**.  I reckon the documentation around it could be better, and I'm happy to merge any PR which improves upon it.

(You can also *work around* the current strategy, though it may be tedious; consider using `--grep` instead.  I understand this issue may be important for you, but because you can work around it--and it's not "core" functionality--discussing, designing & implementing other (breaking) strategies is low priority for the project.)

**Comment by villesau** [comment]
@boneskull It's really reasonable that the smallest nominator in this case wins, otherwise .only loses it's meaning in nested suites. describe.only says which suite should be run, test.only says which tests within suite should run. Really simple.


If you look at the current tests:

```

describe.only('should run this suite, even', function () {
  describe('should run this nested suite, even', function () {
    describe('should run this doubly-nested suite!', function () {
      it('should run this test', function () {});

      it('should run this test', function () {});

      it('should run this test', function () {});
    });
  });
});

describe('should run this suite with an exclusive test', function () { //<- this runs anyways
  it.only('should run this test', function () {});

  describe('should not run this nested suite', function () {
    describe.only('should not run this doubly-nested suite', function () {
      it('should not run this test', function () {});

      it('should not run this test', function () {});

      it('should not run this test', function () {});
    });
  });
});
```

There is inconsistency anyways since top level suites are always run if there is nested onlies.

**Comment by boneskull** [comment]
The suite has to run to know if a test has used `only`.

**Comment by dasilvacontin** [comment]
> The suite has to run to know if a test has used only.

And it shouldn't really be a problem if all your code is inside hooks or tests, afaik.
