### ISSUE TITLE
Specify path pattern within mocha.opts

### ISSUE THREAD

**Issue by vekexasia** [mochajs/mocha#2632]
Is it possible to specify the file pattern within mocha.opts? I cant find a full-reference for the options supported within mocha.opts.

**Comment by ScottFreeCode** [comment]
It should be possible to specify the file pattern within mocha.opts; mocha.opts is supposed to support everything the commandline supports (except maybe the flags passed to Node), which is why there isn't an explicit list -- basically its contents are appended to the arguments (or maybe it's prepended rather than appended, I forget which).

**Comment by Munter** [comment]
mocha.opts example with file patterns;

```
--option value
path/to/tests/**/*.js
test/**/*.jsx
```
