### ISSUE TITLE
Issues while naming tests containing []

### ISSUE THREAD

**Issue by rnagpal** [mochajs/mocha#2634]
I'm using mocha package(v 3.2) for running my tests using Visual Studio tools for Nodejs extension for VS 2015(v 1.2) and I've observed that that if My test name contains [] chars, the test doesn't even enter the first line but returns prematurely and marking it as passed.
Like: it("[nativeApi] tests")

If I remove [] from the test name it works as expected.

This used to work several months back and not sure if this is an issue with the latest version of mocha.

**Comment by ORESoftware** [comment]
I was going to say take a look at the Mocha source, but it turns out it might be hard to find out where the problem might be. I know I have named tests with [ ] characters before and it wasn't a problem, so curious what it might turn out to be. You are sure that when you remove the chars it's fine and when you add it's not?

Fire up the debugger, and step in!

**Comment by rnagpal** [comment]
@ORESoftware : Yes, if I remove those chars it works and if I have them it doesn't.

@a8m : This looks like related too your change of adding Regex support. Can you please confirm or tell me what's wrong here?https://github.com/mochajs/mocha/pull/1808/commits/194f19ed5283acce7401ac507586c0223594b46a

**Comment by kunagpal** [comment]
@rnagpal With Mocha `v3.4.1`, and Node `v4.x` and `6.x`, the presence/absence of `[]` in the test description does not affect the test's execution. Could you try it out and confirm?
