### ISSUE TITLE
Inline diff code appears dead

### ISSUE THREAD

**Issue by isiahmeadows** [mochajs/mocha#2663]
I searched around and found this:

1. `useInlineDiffs` is only used with `--inline-diffs`, and the option is never used anywhere.
2. `exports.inlineDiffs` from `lib/reporters/base.js` is never modified.

So, this basically equates to a bunch of visibly dead code.

Related: #2098

**Comment by ScottFreeCode** [comment]
I wouldn't worry so much about whether the code appears dead (anyone can use the `--inline-diffs` flag and see that it's functioning, after all) as the fact that the implementation design is of dubious quality in principle:

1. Users use the `--inline-diffs` flag...
2. ...which calls `useInlineDiffs`; or, users running Mocha programmatically call `useInlineDiffs` themselves; this function...
3. ...sets `options.inlineDiffs`, which is retained for when `mocha.run` is called.

...So far, so good; but then...

4. `mocha.run` uses `options.inlineDiffs` by setting `reporters.Base.inlineDiffs`
5. That's the `exports.inlineDiffs` flag in the `Base` reporter's file...
6. ...which then gets used by the reporter instance to tell which diff flavor to use.

As complex and mature as Mocha is, I'm not too concerned that it takes an hour to trace the journey of that value/flag. That's par for the course at this point -- maybe if Mocha weren't handling so many things, or if it were based more on input-output instead of on mutating states followed by taking actions, then we could cut out some of those steps, but it's less convoluted than, say, the reason we can't make the interface functions non-global without an extensive semi-internal rewrite.

There is one thing that gives me the heebie-jeebies about this, though -- the fact that reporter instances get the flag from *a global variable* in the `Base` reporter module (as opposed to taking it as a parameter or an option on a bulk parameter like `reporterOptions`) -- meaning that, for instance, it's unclear whether you can run two instances of Mocha programmatically at the same time and control having only one of them use inline diffs. This is hardly the only thing making Mocha hard to use more than one instance programmatically, but it's yet another obstacle on the list toward fixing that...

**Comment by boneskull** [comment]
@ScottFreeCode please close if nothing actionable here, or nothing pragmatically actionable, anyway.

**Comment by ScottFreeCode** [comment]
I don't think the code in question is any more dead -- in use or in mere appearance -- than any other code that is triggered by the programmatic API being called by the CLI. It's just harder than some of the others to trace how it gets from the call to the end resulting effect because the value is set through this weird global side channel. Which...

- It's like a buy-one-get-one-free antipattern sale: global-value behavior *and* effects by side-channel.
- On the other hand, I'm not convinced the lack of clarity is bad enough to justify the effort that would be involved in figuring out a proper way to communicate that value to/through an instance.
- But, we may eventually need to if we ever get the rest of the things fixed that make Mocha broken in multiple-instance programmatic usage, as it could potentially cause problems there (albeit less common ones than the ubiquitous "I can't run Mocha twice programmatically at all!").

I think we should make a note somewhere associating this with Thing That Would Need to Be Fixed for Multiple Programmatic Runs to Work 100% Right, but I don't think this issue reported re. the code appearing dead is the right place to keep that note.
