### ISSUE TITLE
describe.only inside describe.skip

### ISSUE THREAD

**Issue by alex-pollan** [mochajs/mocha#2679]
Hi:

A ``describe.only`` inside a ``describe.skip`` is taking precedence and preventing rest of tests from running.
Shouldn't ``describe.skip`` override any embedded modifier? I think it should.

Example:

file1.spec.js:

```javascript
describe.skip('test1: this should not run at all', function() {
    describe.only('run only this', function() {
        it('should not run this', function(){
           expect(true).to.be.true;
        });
    });
});

```
file2.spec.js:

```javascript
describe('test2: this should run if no other is marked as only', function() {
    describe('run this', function() {
        it('should run this', function(){
           expect(true).to.be.true;
        });
    });
});
```

Regards

**Comment by dennisbaskin** [comment]
From the docs and the code, it seems that `skip` is intended to be used to denote pending assertions, or suites. And adding a call to `only` whitelists the test to even show. 

While I see your point, I think it is okay to denote a suite of tests as pending, including ones that you are whitelisting. I also see a note in the docs:

> Be mindful not to commit usages of .only() to version control, unless you really mean it!

This tells me that the intention was for development purposes and or debugging. 

Do you have a real world example where this would be useful?

**Comment by alex-pollan** [comment]
Not really. Not one that i can think of.
It was by chance that I ended with that situation in my suites.
It's just that logically thinking it is unexpected to have a whitelisted test executed inside a skipped test suite.

**Comment by dennisbaskin** [comment]
Yeah, I see where you are coming from here. I thing some of this is due to the difference in the assumed expectation based on the method name vs actual behavior. To clarify: I expect tests and/or suites to not show if they are skipped as the name implies. However the behavior is closer to: if the tests and/or suites are marked skip, then just mark the test or all tests within the suite as pending, and whitelisting tests will decide whether they show.

Do you think this is something that should be pursued further, and discussed with the developers, or should this request be closed?

**Comment by alex-pollan** [comment]
No, I'm fine, I'll close it now.
