### ISSUE TITLE
Spec reporter should display test file name

### ISSUE THREAD

**Issue by lrowe** [mochajs/mocha#2717]
When defining tests with a helper function ([shared behaviours](https://github.com/mochajs/mocha/wiki/Shared-Behaviours)) the stack trace does not include the test file name. This makes it difficult to track down the failing test.

(Related: #1466)

**Comment by ScottFreeCode** [comment]
FWIW, I think the technique described in that old wiki page is generally frowned upon nowadays -- better to be explicit about what each test expects even if that means repeating stuff in the tests ("don't repeat yourself" is [not about code that happens to be the same but rather about information inherent in the code](http://verraes.net/2014/08/dry-is-about-knowledge/), but tests by their very nature validate the information inherent in the code, thus two tests aren't necessarily redundant just because they say the same thing about distinct objects); for perspective, the example on that page is full of other code smells such as using `this` to store state across tests (although there are ways to achieve such shared test behavior more cleanly if really needed... but I'd have to think about whether any of them would restore the stacktrace to the test file instead of the shared test behavior file).

**Comment by JoshuaKGoldberg** [comment]
There's been very little discussion on the spec reporter's displayed names/paths in the last few years. Closing this out as it doesn't look like many users need this functionality still. Someone please yell at me if I'm wrong!

If you do want this, it'd also be helpful to post a comparison list of other xunit reporters in equivalent tools. We should see what they generally do and consider mirroring that behavior.
