### ISSUE TITLE
Stack errors

### ISSUE THREAD

**Issue by mattfiocca** [mochajs/mocha#2723]
Im getting a JS error in the base reporter when i try to run a test on an express route. This route responds with a 500 error as part of my test, and i get the following error in my console whenever a route doesn't return OK.

```
[app path]/node_modules/mocha/lib/reporters/base.js:223
    stack = stack.replace(/^/gm, '  ');
                 ^
```

in doing a console log in this file, i noticed that `typeof stack` is an `object` for me, instead of a `string`, which is why I think the `.replace()` is failing.

To provide more context, i'm using `chai` and `supertest` with mocha to run http tests on my api.

```
chai
	.request(server)
	.post('/v1/introductions')
	.set('Authorization', "Bearer "+token)
	.end(function(err, res) {
		// if not a 200, we see the JS stack error happen
		// all good if this passes
		res.should.have.status(200);
		done();
	});
```

**Comment by mattfiocca** [comment]
further, `stack` is an array of `CallSite {}` objects when I inspect this

**Comment by mattfiocca** [comment]
on line 223 of reporters/base.js, changing:

```
stack = stack.replace(/^/gm, '  ');
```

to:

```
if (typeof stack == 'object') {
	for(var i=0; i < stack.length; i++) {
		stack[i] = stack[i].toString().replace(/^/gm, "\t");
	}
	stack = stack.join("\n");
} else {
	stack = stack.replace(/^/gm, '  ');
}
```

Got me rolling once again.

**Comment by ScottFreeCode** [comment]
I'm not sure about why Mocha's expectations for the stack is clashing with your test's behavior, but I do want to say: Either return `.then` instead of using `.end` and `done`, or handle the `err` parameter to your `end` callback, as a rule. (I was burned by this one recently and I'm still a bit sore, heh heh.)

For digging into this issue, could we get a complete example? That is, in addition to the test code above, what exactly do we need to `npm install` and what are the definitions of all the variables in the test code (even if you have to replace your real site with dummy examples such as trying to access a nonexistent page on mochajs.org or something like that). Basically, unless somebody just happens to recognise the particular behavior in question, we're going to need to be able to actually run this (with the same libraries -- I've used Chai before but I'm not familiar with the usage shown here...) and debug it ourselves to be sure we're looking for the issue in the right place, in order to understand if any potential fix is actually correct (isn't going to break other things or even unnecessarily complicate them, etc.). And then there's the fact that long-term we don't just need to fix it, we need to write a regression test so we don't unknowingly break it again later.

**Comment by mattfiocca** [comment]
ah, you know what... we have a redis connection happening in a different part of the app, and despite error handling on the redis client connect, the node-redis module seems to be ignoring the handler and is throwing errors anyway. 

the mocha error i describe here goes away entirely when I make sure that a redis connection is available during our tests. .... weird. Anyway, I'll close this, as it has nothing to do with Mocha.

thanks for getting back to me so quickly.

**Comment by GuillaumeLeclerc** [comment]
We have the same issue. It only occurs on Ubuntu. Other distributons of Linux runs fine.

**Comment by aadityataparia** [comment]
Having the same issue as well.
