### ISSUE TITLE
Ability to register a one-time 'after' hook from inside beforeEach() or it()

### ISSUE THREAD

**Issue by peterflynn** [mochajs/mocha#2741]
I'd love it if there were some Mocha API that lets me add a hook to run whenever the current context's `afterEach()` would run, but only a single time (i.e. only for the _current_ test).

There are two use cases for this:

#### 1) Easy clean up one-off, test-specific bits of test state

A test like this, with a one-off bit of setup that needs cleanup, is dangerous since if it fails the cleanup won't happen and later tests could get broken:
```js
it("some test", function () {
    sinon.stub(someGlobal, "someAPI");
    // ...test something...
    someGlobal.someAPI.restore();
});
```

Yet it's verbose to have to wrap a single test like this just because it's stubbing one extra API that the rest of the suite doesn't stub:  (and it gets in the way of grouping tests more semantically)
```js
describe("verifying someAPI", function () {
    beforeEach(function () {
        sinon.stub(someGlobal, "someAPI");
    });
    afterEach(function () {
        someGlobal.someAPI.restore();
    });

    it("some test", function () {
        // ...rest of test body...
    });
});
```

It would be nice if the test could just register a one-off "after this single runnable" hook, like this -- functioning sort of like a catch block:
```js
it("some test", function () {
    sinon.stub(someGlobal, "someAPI");
    afterThisTime(function () {
        someGlobal.someAPI.restore();
    });
    // ...test something...
});
```

(note that you couldn't use the existing `afterEach()` like this, since then it would run after every subsequent test in the suite too)

This is similar to some C++ unit-test patterns, where you have a local object tracking a certain stubbed/mocked thing, and when that variable goes out of scope at the end of the test its destructor automatically cleans up the stubbing/mocking.

#### 2) Easier to write 'self-cleaning-up' utility functions

If the same thing were possible during a `beforeEach()` too, then instead of setup utilities that need manual cleanup, like this:
```js
beforeEach(function () {
    // ...
    testUtils.disableAllAnalytics();
});
afterEach(function () {
    // ...
    testUtils.reenableAllAnalytics();
});
```

You could write a utility that _automatically_ registers its own cleanup hook by calling the global "afterThisTime" API:
```js
beforeEach(function () {
    // ...
    testUtils.temporarilyDisableAllAnalytics();
});
```

You can't do this either by calling today's `afterEach()` -- since `beforeEach()` is called once per test, it'll add an extra afterEach hook each time, causing the Nth test to run the cleanup code N times.  (You could get clever, e.g. passing `this` to the utility API so it can set a flag indicating whether it's attached its cleanup hook to the current test context or not, but that is messier and more verbose).

**Comment by ScottFreeCode** [comment]
I am unsure how important the 2nd point is, but to the 1st, it may be less verbose to work around it within a single test using `finally`, since assertions are typically implemented as throwing exceptions:
```js
// synchronous test
it("should clean up afterward", function() {
  try {
    // test stuff here
  } finally {
    // clean up here
})
```
Not sure there's a standard way to do that with promises but without `async` functions, let alone with non-promise asynchronous tests, however. But for simple cases like this, the main difference is that any errors thrown in cleanup will be reported as a test failure instead of as a cleanup hook error.

(Aside: that's an interesting use of RAII you mention. I wonder if there's a way to do something like that in JavaScript -- obviously, we don't have destructors, but maybe there's a way to, for instance, execute the code that uses a resource inside a callback and do cleanup when the callback is done? Or to get something less nesty and more flexible than callbacks, maybe a way to use generator functions for resource management [like how Co lets generators be used for unwrapping promises, but instead of unwrapping promises it would save and retrieve resources that will have their cleanup run when the generator is done]?)

**Comment by JoshuaKGoldberg** [comment]
This has been `status: waiting for author` for quite a while. And there hasn't been much activity. Closing as aged away.

If someone very much wants this, please do file a new issue with our new templates. I'd love to learn more. Thanks!
