### ISSUE TITLE
 Cannot set property 'onchange' of null

### ISSUE THREAD

**Issue by craigcosmo** [mochajs/mocha#2744]
I got some code like this

**index.js**

```
export function makeEl(){
  console.log('mama')
}
window.onload = function(){
	document.querySelector('#upload').onchange = function() {
		console.log('a')
	}

}
```

**home.spec.js**
```
import {makeEl} from '../app/index'

describe('makeEl', () => {
	it('should create an element', () => {
	
	})
})
```

when I run `npm run test`. I got this error in chrome's console

<img width="550" alt="screen shot 2017-03-17 at 10 21 27 pm" src="https://cloud.githubusercontent.com/assets/538657/24049977/1f31ed36-0b60-11e7-86b0-f3a348922148.png">

**Comment by ScottFreeCode** [comment]
This is unlikely to have anything to do with Mocha; probably there is no element with the ID "upload", at least at the time that window.onload fires... but in any case, Mocha is niether expected to create such an element nor likely to destroy such an element or prevent it from being created, so unless the real issue here is that the code that is supposed to create the element is part of your test code, it's unlikely to be relevant.

That being said, even to verify that the problem is or isn't Mocha-related, we also [can't do much to help you debug it with just these snippets of code out of context](http://stackoverflow.com/help/mcve).
