### ISSUE TITLE
expect().to.have.all.members on equivalent arrays throws assertion error

### ISSUE THREAD

**Issue by KernelDeimos** [mochajs/mocha#2758]
As a quick disclaimer, I just began using Mocha today and I may be misunderstanding something - but currently I'm convinced this is a bug.

I have the following assertion:

```
expect([false,0,"",null,undefined,NaN,"positive","negative"]).to.have.all.members(
    [false,0,"",null,undefined,NaN,"positive","negative"]
);
```

This raises an assertion error.
```
AssertionError: expected [ Array(8) ] to have the same members as [ Array(8) ]
```

I believe this is a bug because the following did **not** raise an assertion error:

```
expect(['a','b','c','d','e','f','1','-1']).to.have.all.members(
    ['a','b','c','d','e','f','1','-1']
);
```

**Comment by KernelDeimos** [comment]
Through trial and error I found the culprit value to be `NaN`

The following produces a similar assertion error:
```
expect( [NaN] ).to.have.all.members( [NaN] );
```

```
AssertionError: expected [ NaN ] to have the same members as [ NaN ]
```

**Comment by ScottFreeCode** [comment]
`NaN` sounds about right, although I'm sure some will be willing to debate whether this is even a bug or correct behavior since `NaN` is not supposed to equal other `NaN` (they could be produced by completely different calculations, all we know they have in common is that niether one validly results in an actual number).

That being said, this also isn't affected by Mocha one way or the other -- you will want to report the issue to whichever assertion library you are using.

**Comment by KernelDeimos** [comment]
Oh wow, my bad - I totally meant to post this on chaijs - thanks!

**Comment by ScottFreeCode** [comment]
No problem. 8^)
