### ISSUE TITLE
`it` not called when setting up tests through code.

### ISSUE THREAD

**Issue by amol-c** [mochajs/mocha#2760]
I am using the below code to kick off the tests.

```
export default function() {
    var mocha = new Mocha({timeout: 100000, reporter: 'spec'});
    var testDir = 'test'
    mocha.reporter('progress');

    // Add each .js file to the mocha instance
    fs.readdirSync(testDir).filter(function(file){
        // Only keep the .js files
        return file.substr(-3) === '.js';
    }).forEach(function(file){
        mocha.addFile(
            path.join(testDir, file)
        );
    });
    // mocha.reporter('list').ui('tdd').run();

    // Run the tests.
    mocha.run(function(failures) {
      process.on('exit', function () {
        process.exit(failures);  // exit with non-zero status if there were failures
      });
    });
}
```

The above code doesn't run the test inside the `it` block.
For e.g:
```
describe('Array', function() {
  it('#indexOf()', function() {
  		console.log("works")
      assert.equal(-1, [1,2,3].indexOf(4));
  });
});
```

The `it` block doesn't work. But if i replace the it block with `describe`, then it works fine.
For e.g:
```
describe('Array', function() {
  describe('#indexOf()', function() {
  		console.log("works")
      assert.equal(-1, [1,2,3].indexOf(4));
  });
});
```

But, if i run the above tests through command line, everything works fine. 

Please advice.
Thanks.

**Comment by amol-c** [comment]
After looking in deeper, looks like i had to add `.run` at the end for it to work. o_O

```
describe('Array', function() {
	it('#indexOf()', function() {
			console.log("works")
		  	assert.equal(-1, [1,2,3].indexOf(4));
	 }).run();
});
```

The `it` returns a `Runnable` and it doesn't get run on its own ? calling run works for some reason.

**Comment by ScottFreeCode** [comment]
You're missing `mocha.loadFiles()`, which is what actually processes the test files (which were added to its list by `mocha.addFile`) in order to collect their suites and tests to run later with `mocha.run`; try this:
```js
export default function() {
    var mocha = new Mocha({timeout: 100000, reporter: 'progress'});
    var testDir = 'test'

    fs.readdirSync(testDir).filter(function(file){
        return file.substr(-3) === '.js';
    }).forEach(function(file){
        mocha.addFile(
            path.join(testDir, file)
        );
    });

    // NOTE: if your tests use a different UI, it must be set before loading the test files
    mocha.loadFiles()

    mocha.run(function(failures) {
      process.on('exit', function () {
        process.exit(Math.min(failures, 255));
      });
    });
}
```

* * *

Additional notes:

- I'm not sure why `it` returns the runnable, considering that they aren't meant to be run by the script that calls `it`. We should look into either removing that or clarifying the intended purpose if there was one. Anyway, *with` loadFiles` added the `run()` in `it(...).run()` should be removed to ensure Mocha operates correctly.*
- `describe`s' callbacks are run immediately in order to find out what their `it`s (and before/after all/each hooks) are, whereas the callbacks to `it`s (and hooks) are run only on `mocha.run`. If changing an `it` to a `describe` caused the callback to be run -- that is, if `describe`s were being run even though Mocha was not loading the files -- then something other than `mocha.loadFiles()` was loading the test script. *If something else loads the test script, then it's possible that you might have to track down what was doing so and eliminate it in order for `mocha.loadFiles()` to work.* (Or you might not; I'm not really sure what all Mocha is doing under the hood in terms of state when gathering the tests via `describe` and `it`. *But that would be the next thing to look for if adding `mocha.loadFiles()` does not resolve the issue.*)

* * *

Sorry about the delay reviewing this issue; please let us know if the above advice works!
