### ISSUE TITLE
Add ability to run Mocha in debug mode from programmatic API

### ISSUE THREAD

**Issue by travs** [mochajs/mocha#2762]
Adding the ability to run Mocha in debug mode through the [programmatic interface](https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically) would be very helpful for testing suites that use Mocha internally, but do not run it as a subprocess and, thus, do not have access to many of the command-line parameters (ex: [Truffle](https://github.com/trufflesuite/truffle)).

If there is currently a way to do this that I am unaware of, please advise.

**Comment by ScottFreeCode** [comment]
Mocha's `debug`, `--debug` and `--debug-brk` options actually are actually just Node's `debug`, `--debug` and `--debug-brk` options -- the `mocha` command spawns another, internal command in order to pass Node options to `node` and the rest of the options to the actual Mocha process without requiring users to call `node <debug options> node_modules/mocha/bin/mocha <mocha options>`, so they're really just a shortcut for Node. I don't know if Node supports activating/using debug mode from within an already running script, but if it does, I doubt Mocha would need to do anything to support it. You'll probably want to look at the documentation for Node's debug options to find out if there's a non-CLI equivalent.

**Comment by daveabes** [comment]
Would be nice to know more about this.

**Comment by buddyp450** [comment]
What @ScottFreeCode alluded to @daveabes, and as I found, is that you don't actually need to do anything with Mocha to use this. In my case, I had an npm script that runs my tests with node as in: node run-tests.js. All I had to do was insert `--inspect-brk` in this to be able to use the debug breakpoint functionality present with node and then I used `chrome://inspect` with the address provided in my console output in order to continue.
