### ISSUE TITLE
New syntax suggestion 

### ISSUE THREAD

**Issue by shai32** [mochajs/mocha#2767]
Now that we have native async-await in node (soon to be in the LTS version)
we don't need so many blocks
maybe we can have a new syntax for e.g:
```
describe('Test Something',  async () => { // the new syntax will be used only if the function is async
  // initializing can be done here like the before() block
  const paramA = 'test';
  const asyncParam = await getAsyncParam();
  // the await ensure that the tests will be executed after all this is ready

  beforeEach(async () => {
    // set up whatever
  })

  afterEach("runs after every test", function() {
    // clean up what `beforeEach` set up
  })

lt('lt description, let mocha know a new test started, it will also run beforeEach ');

  // do some testing, you can use await
  // no need for a block because we have await syntax
  // if no error was thrown, the above lt was passed

lt('second lt description, let mocha know that the previous test is complete and  run afterEach => beforeEach');

  // do some more testing, you can use await
  // if an error occurred here the describe block will catch it
  // the describe will assign the error to the last lt that was executed

  end()

  //after block

});
```

**Comment by ScottFreeCode** [comment]
Because `async` functions are just syntactic sugar for functions returning chained promises, Mocha can already do something like this:
```js
describe("this suite is defined synchronously, but the hooks and tests can run asynchronously", function() {
  let localVariable
  before(async () => {
    localVariable = await Promise.resolve("This involves writing `localVariable` twice, but works with an arrow function and doesn't have any of `this`'s weird edge cases.")
  })
  beforeEach(async function() {
    this.contextVariable = await Promise.resolve("This does not require writing the variable name an extra time, but requires a traditional function, and doesn't necessarily use the built-in language scoping behavior")
  })
  it("synchronously uses asynchronously set-up variables", function() {
    // assert whatever on localVariable and this.contextVariable
  })
  it("asynchronous!", async function() {
    // await something else
    // assert whatever on localVariable and this.contextVariable
  })
})
```

(There also is the [delay](http://mochajs.org/#delayed-root-suite) option if the suite itself needs to be defined asynchronously; it might not be as pretty as an `async` function, but it is rarely needed and as far as I know works fine when it is needed.)

Changing Mocha to run tests when the `describe` callback is being run would not just be a new interface, but a backwards-incompatible change to how Mocha operates as a whole. The current design allow you to write code like this:
```js
describe("written in a setup-test-cleanup order", function() {
  beforeEach("runs before every test", function() {
    // set up whatever
  })
  it("here is a test", function() {
    // test whatever
  })
  it("here is a test", function() {
    // test whatever
  })
  afterEach("runs after every test", function() {
    // clean up what `beforeEach` set up
  })
})
```
In order for that to work, the tests can't be run until after the `describe` callback finishes so Mocha has the `afterEach` function before it starts running the tests; if it ran the tests as it was running the `describe` block, the `afterEach` would not run after the first test (before the second test and in addition to after the second) since it isn't written till after the second.

I can't necessarily, off the top of my head, rule out the possibility that one test runner *could* support two completely different *underlying behaviors* like that based on the different interface. However, given that this difference requires either losing compatibility with the existing interfaces or else at least twice the complexity to support both (on top of the fact that the new behavior, and not just a different interface, would have to be implemented in the first place)... We'd need a pretty compelling example of something that it would enable that is unreasonably difficult or impossible with the current support for promises (and/or the [delay](http://mochajs.org/#delayed-root-suite) option).

**Comment by shai32** [comment]
Thank you for the detailed answer, I am  already using the async syntax as describe above and it works well.
The only thing I don't like in the current syntax is when the lt tests depends on each others.
eg: if a lt block need the result from previous lt, I need to have  a variable in the describe context, and use it to 'share data'  between different let blocks.
in a  'synchronise syntax' its more natural to write a describe block that test a scenario when each let depends on the previous let result

**Comment by ScottFreeCode** [comment]
Something like this?
```js
// Using chai for example of `property` test.
// Choice of assertion library not relevant to technique,
// just need to demonstrate that value has been retrieved from promise.
const expect = require("chai").expect

describe("not sure if a suite is actually needed, except to prevent tests in other files from seeing the `this` member", function() {
	it("does stuff the other test depends on", async function() {
		this.shared = await Promise.resolve("bad idea?")
	})
	it("depends on the stuff the other test does", function() {
		expect(this.shared).not.to.have.property("then")
	})
})
```
Keep in mind that we don't encourage writing tests this way because there are other issues you can run into if they aren't isolated and self-sufficient -- regardless of syntax.

**Comment by boneskull** [comment]
this can be implemented as a custom interface, if you really want to, but IMO this is overthinking it
