### ISSUE TITLE
Timeout multiplier.

### ISSUE THREAD

**Issue by bennieswart** [mochajs/mocha#2771]
### Background
We have a suite of Mocha tests that are functional in nature and use Selenium to fully test our web application. Due to the amount of interconnected components, tests can often take a couple of seconds (each) to complete. For this reason the test timeouts are finely tuned to allow just enough time (and a bit more) for each test to complete, without wasting too much time waiting if the test times out.

### Problem
The timeouts are set according to the capabilities of our development server. The problem we have encountered is that, when these tests are run by other developers on their local machines they often timeout due to the other machines not being as powerful.

### Suggestion
Instead of changing all the timeouts to accommodate the slowest machine, we thought it would be an elegant solution to simply add a timeout multiplier, such that a machine that is twice as slow could simply add a 2x multiplier somewhere in a local config file (or command line parameter). This would allow the tests to pass without any modification to the existing codebase.

What do you think? Is this a problem worthy of addressing? Are there perhaps better solutions?

**Comment by ScottFreeCode** [comment]
I've had to deal with a similar situation at a recent job. It's definitely an issue that would be nice to have some kind of proper solution for -- whether in Mocha or as something that could be used along with it. Bear with me as I recall my anecdotes... ;^)

In our case, we had a site that was generally pretty fast except for the things that hit the underlying programmatic API; then the network it was behind varied wildly in terms of speed and reliability (or maybe it was that API that did? but since said API was required for logging in...); and we wanted the production copy of the test suite to run quickly and fail if things were being slow, but to be able to run tests locally that would be verrrrry tolerant of such issues in order to check that said tests work while developing them...

We ended up tackling it from a couple angles. On one hand, we took advantage of the fact that the site was generally fast but the network/API generally slow to keep just a few categories of how long the timeouts need to be. Fine-tuning the fastest reliable timeouts could have cut the time down even further in the failure case, but that seemed like a dubious microoptimization in our case given the variability; even aside from that, I think coming up with some kind of general categories is a good idea in general because it's easier to figure out which category a test fits into than to keep the fine-tuned amounts up to date if and when the tests -- or the underlying code implementing the functionality they check -- change slightly in the future. The other angle was how to get the parameterization of the timeout categories' times into the actual run. Since we were spawning a single Mocha process per run (and not, say, reusing a programmatic instance of Mocha), we ended up using an environment variable to change these times from their defaults as applicable.

(We also were using a long Mocha timeout just in case of infinite loops or whatever, and using this configuration for the timeout parameters of the Selenium commands, because the Selenium commands should usually be what time out [with their more specific error messages!] rather than Mocha itself -- that made it even simpler to devise general categories, since it was for steps rather than for entire series...es of steps. Also, we `require`d a file containing constants that were set via those environment variables -- so nothing could change them by messing with `process.env` later -- but theoretically they could also have been assigned by a global `before` hook to properties on Mocha's `this` object available in all the tests and hooks, in order to be less global -- though then it would have been harder to ensure it can't be messed up at some point, the usual peril of relying on state in Mocha's `this` object.)

If you do need something more fine-tuneable, it might even be possible to combine the idea of parameterizing the timeout like that with the idea of multiplying it. For example, you could have a test that needs to go through three pages set `this.timeout(pageLoadTime * 3)`, where `pageLoadTime` is the variable that could be adjusted as necessary. (Or, to go with your approach, `this.timeout(<this test's specific timing> * timeoutMultiplier)`.) Then instead of being stuck with multiplying all the tests' timeouts as your one mode of adjustment, you could handle tests that shouldn't be scaled if you end up with any (just omit any variables from their `timeout` calls and they'll be unaffected), or handle exponential growth instead of multiplication if you run into the need for that, etc. It's a bit more manual but it's way, way more flexible.

The one thing I really don't like about that whole approach, though, is that I can't think of a better way to get the variable override into the test runs in the first place than a global configuration in the form of an environment variable. I suppooooose that doesn't matter too much if using Mocha through the CLI though, which is the usual case (especially since the programmatic API is, well, basically broken when it comes to reuse, which is the one case where a global configuration would be a real problem as far as I can think of). So I guess my question would be, is there a good way to set something like that on a per-run basis if one got Mocha running multiple times in the programmatic API in the first place...? (Assuming there's a need to; it could be that even when using and reusing Mocha programmatically, the variables really only depend on the environment and need not change between one run and another. Hmm. Maybe global configuration happens to be fine for the majority of use cases?)

That's where I'm at right now in terms of my experience, anyway; let me know how those ideas sound to you, or if you'd like to work through more concrete code examples or anything like that.

**Comment by JoshuaKGoldberg** [comment]
This open question has existed for quite a while without a concrete answer. Per #5027 we've moved question-asking to Discord. If you're reading this and interested, please:

1. Search other issues for what you're trying to do
2. Ask there or StackOverflow

Cheers!
