### ISSUE TITLE
Broken symbolic link for supports-color

### ISSUE THREAD

**Issue by kkrull** [mochajs/mocha#2774]
I noticed that the symbolic link for `node_modules/mocha/node_modules/.bin/supports-color` is not pointing to an existing file.  I found this out when part of the runtime environment walked the directory tree under `node_modules`.

I'm not sure if this is an issue with mocha, npm, or supports-color, but I thought I'd try reporting it here first.

Here's what I notice so far:

```
[node_modules/mocha/node_modules/.bin]$ ls -l
total 4
lrwxr-xr-x 1 xxxx xxxx 24 Mar  2 14:41 supports-color -> ../supports-color/cli.js

[node_modules/mocha/node_modules/.bin]$ ls -l ../supports-color/
total 20
-rw-r--r-- 1 xxxx   38 Jul 18  2015 browser.js
-rw-r--r-- 1 xxxx 1154 Oct 13  2015 index.js
-rw-r--r-- 1 xxxx 1119 Apr  6  2014 license
-rw-r--r-- 1 xxxx 2837 Apr 18 09:15 package.json
-rw-r--r-- 1 xxxx 1491 Jul 15  2015 readme.md
```

and here's some information about my environment

```
$ npm --version
3.10.7

$ node --version
v6.6.0

$ npm ls mocha
tdc@1.1.2 xxxxx
└── mocha@3.2.0 
```

I'm happy to do some more digging and/or submit a pull request, if anyone has any suggestions on where to start looking.

**Comment by ScottFreeCode** [comment]
Everything in `node_modules` is installed by `npm` and is not in the project's version-control (or much of any control except for specifying which packages are its dependencies), so this is almost certainly not due to anything about Mocha. (Will reopen if we discover otherwise.)

Interestingly, current version of Mocha depends on `supports-color@3.1.2`, and when I `npm i supports-color@3.1.2` I don't get any `node_modules/.bin/supports-color` at all -- if you `npm rm mocha` and then `npm i mocha` does it go away?

**Comment by kkrull** [comment]
Thanks @ScottFreeCode.  Your suggestion of `npm rm mocha && npm i mocha` does cause the broken symlink to disappear, so this doesn't seem to be an issue with mocha.

Oddly enough, `npm prune` does not remove the link.  I'll have to read up more on how npm builds up each package's bin directory.

Thanks for the quick reply!
