### ISSUE TITLE
Mocha test stops without further execution of other test cases if an expect fails in a test case.

### ISSUE THREAD

**Issue by sandeepvedavyas** [mochajs/mocha#2781]
describe('API testing: meeting', function () {
    it('Testing meeting update view count call without error', function (done) {
        request(app).post('/meeting/updateViewCount').send({ videoId: 17 }).set('Accept', 'application/json').expect(200).end(function (err, res) {
            should.not.exist(err);
            should.exist(res.body);
            expect(res.body.status).to.equal('Success'); // This fails 
            done();
        });
    });-- In above test case I am passing invalid videoId as 17 , no record exists with this id and it will fail and mocha throws below error and exit.

  throw err;

  ^

AssertionError: expected 'Error' to equal 'Success'

But I want it to continue further executing below test and also many other in different files and show the result of passed and failed with proper execution.

    it('Testing meeting update view count call with error', function (done) {
        request(app).post('/meeting/updateViewCount').send({ videoId: 's' }).set('Accept', 'application/json').expect(200).end(function (err, res) {
            expect(res.body.status).to.equal('Error');
            done();
        });
    });
});

Is this an issue or am i missing something here, I am new to mocha tests, earlier i worked on java and grails testing frameworks where i never faced any such issues.

Thanks
Sandeep

**Comment by ScottFreeCode** [comment]
Mocha does normally run all tests and report multiple passes and failures; if it's not doing so that's a bug of some sort. However, it's also possible that what's actually happening is some other issue... What's the full output you get if you run just that file (`node_modules/.bin/mocha path/to/specific/test.js`)?

P.S. You can surround your code blocks with \`\`\` to get cleaner formatting (and optionally include a language to get syntax highlighting), e.g.:

    ```javascript
    your(
      code()
        .here
      )
    ```
...becomes...
```javascript
your(
  code()
    .here
  )
```

**Comment by sandeepvedavyas** [comment]
@ScottFreeCode , I have run the single test file with 3 testcases , but still am facing the same issue. 

Below is the output of single file execution, first test case passed and second failed due to expected error and 3rd did not run at all mocha exited with exception of 2nd and without running 3rd test.

  API testing: meeting synopsis
    ✓ Testing meeting synopsis list call (4554ms)

/Users/svedavya/Documents//package/repo/node_modules/temp-fs/index.js:32
  throw err;
  ^
AssertionError: expected 'Error' to equal 'Success'
    at Test.<anonymous> (/Users/svedavya/package/repo/test/api/MeetingSynopsisTests.js:53:40)
    at Test.assert (/Users/svedavya/Documents/package/repo/node_modules/supertest/lib/test.js:179:6)
    at Server.assert (/Users/svedavya/Documents/package/repo/node_modules/supertest/lib/test.js:131:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:188:7)
    at emitCloseNT (net.js:1568:8)
    at /Users/svedavya/Documents/package/repo/node_modules/async-listener/glue.js:188:31
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
    at process.fallback (/Users/svedavya/Documents/package/repo/node_modules/async-listener/index.js:529:15)

**Comment by ScottFreeCode** [comment]
That is definitely odd: it doesn't even look like a test failure reported by Mocha, looks more like an exception killing the Node process as a whole. But that *shouldn't* happen, since Mocha is supposed to (and normally does) catch any exceptions that occur during testing (and report them to the current asynchronous test if it is currently waiting for an asynchronous test to complete). (Not that that adds much over my initial thought that this is indeed a problem that shouldn't occur, but it's more specific at least...)

Hmm... three test cases in the file -- any chance I could look at the whole file, with some idea of what the dependencies are doing? Better yet (although I *hope* it won't be needed, it's hard to tell at this point -- nothing jumps out at me as obviously wrong with the code you've shown so far) -- if you feel like making it easier for me and getting some experience digging into the issue yourself, a complete example (but more minimal than the project as a whole, if possible) that I could copy-paste and run myself to play with and debug would be really helpful.

**Comment by sandeepvedavyas** [comment]
I have found the issue and solved it myself, it was the supertest plugin which was causing the issue when assert fails , it was not propagating the exception to next level instead it was exiting the node thread. I had used chai-http with proper exception mechanism and issue resolved.

**Comment by ScottFreeCode** [comment]
Interesting -- I've used Supertest before and didn't run into this... Is there a link to an issue on the Supertest repo we could put here for reference?

Glad you were able to track it down in, any case!

**Comment by phvajjha** [comment]
I have this exact same issue. Is there no way to use Supertest? Using chai-http is not an easy solution, we have way too many mocha test cases to change at this point!

**Comment by KidSysco** [comment]
I tried chai-http and supertest. Mocha is unable to run and report anything if any test fails. That is not a very good approach at testing. Unit tests should show up in red if they fail and green if they pass.

**Comment by Sean1127** [comment]
> I have found the issue and solved it myself, it was the supertest plugin which was causing the issue when assert fails , it was not propagating the exception to next level instead it was exiting the node thread. I had used chai-http with proper exception mechanism and issue resolved.

I am using grunt + mocha and run into similar issue.
Perhaps an easier solution is to set mocha option [--bail, -b](https://mochajs.org/#command-line-usage)
This will allow mocha to continue further tests when previous test fails.
But inside the test, it will stop after encountering the failing assertions.

```javascript
describe("Title", () => {
  describe('#Tag', () => {
    it('Test1', () => {
      assert(false);
      // this line will NOT be execute
    }

    it('Test2', () => {
      // this line will be execute
      assert(true);
    }
  }
}
```

**Comment by jayeshagarwal** [comment]
@sandeepvedavyas, Can you please tell us how did you solve the issue with chai-http as I'm also facing the same issue?

**Comment by hiteshbal91** [comment]
I also have a similar kind of situation, my tests are getting failed on the first occurrence. 

Mocha: 8.1.3
Supertest: 3.3.0
chai: 3.5.0

My observation is that when I use expect in order to do the assertion if assertions get failed then only I am getting this kind of issue, in a few of the cases where we have used should for the assertions those suites are not getting interrupted. 

Also, the --bail option is also not working out for me :(.

thanks
