### ISSUE TITLE
Using mocha programmatically - mocha/lib/runner.js - getting expected and actual results

### ISSUE THREAD

**Issue by AlanDu50** [mochajs/mocha#2782]
https://github.com/mochajs/mocha/blob/8cae7a34f0b6eafeb16567beb8852b827cc5956b/lib/runner.js#L47-L57

So in `mocha.run().on(eventName, handler)`, I can listen to many types of events, such as `test end`, `end` and so on.

I was wondering if there was a way to emit my own custom event from the mocha test JS.

For example, I want to know about which assertions took place, the values of each assertion (the expected and actual values).

Thank you.

**Comment by ScottFreeCode** [comment]
> For example, I want to know about which assertions took place, the values of each assertion (the expected and actual values).

The `fail` event should be provided the test and the error (e.g. assertion failure) as parameters; assertion failure errors are typically populated with the `expected` and `actual` properties (although I think that's up to the assertion library). Let me know if that works for you!

As to the more general question: to my knowledge, custom events might be possible in the sense that you could take the runner and `emit` instead of `on` in order to communicate to whatever else is listening `on` that runner, but I don't know of a way to get ahold of this for custom events from within the test run logic instead of from whatever is using the runner, and presumably if you had the information there you probably wouldn't need to emit it as an event... That being said, it's hard to be sure because I haven't dug around too much in the event messaging code -- it's pretty hairy down there and what can or cannot be done isn't always as straightforward as it seems.

**Comment by AlanDu50** [comment]
Thanks, and is it possible to get the test duration when the test fails?
