### ISSUE TITLE
Vulnerability in dependency growl 1.9.2

### ISSUE THREAD

**Issue by balsamiqFlorian** [mochajs/mocha#2791]
Hi,

I got a report that mocha includes growl 1.9.2 which is vulnerable to an arbitrary code injection.
https://snyk.io/vuln/npm%3Agrowl%3A20160721?utm_campaign=vuln_alert&utm_medium=email&utm_source=Vuln

This issue is closed in growl 1.9.3.

Thanks.

**Comment by ScottFreeCode** [comment]
Is there a way we can tell Snyk that Growl 1.9.3 does not in fact exist, and that the commit they reference is only in a fork (so it is possible that in the future Growl 1.9.3 could be published before fixing this issue, thus rendering their instructions incorrect once 1.9.3 does exist)?

If anybody wants to look at whether Mocha is actually at risk from this, I believe these would be the lines to examine: https://github.com/mochajs/mocha/blob/8a3cab063cfe68fa2e9aea8feada23aaf1a4db6f/lib/mocha.js#L241-L257

**Comment by andris310** [comment]
Got same warning in Node Security Platform https://nodesecurity.io/advisories/146

**Comment by Fzzr** [comment]
There is no growl 1.9.3, the issue is not actually fixed. See issue https://github.com/tj/node-growl/issues/60 and PR https://github.com/tj/node-growl/pull/61

**Comment by papakai** [comment]
Got same warning using retire.js

**Comment by davorivas** [comment]
I am getting the same error and my tests in circleCI are not passing because of this "vulnerability"


(+) 1 vulnerabilities found
┌───────────────┬───────────────────────────────────────────────────────┐
│               │ Command Injection                                     │
├───────────────┼───────────────────────────────────────────────────────┤
│ Name          │ growl                                                 │
├───────────────┼───────────────────────────────────────────────────────┤
│ CVSS          │ 9.8 (Critical)                                        │
├───────────────┼───────────────────────────────────────────────────────┤
│ Installed     │ 1.9.2                                                 │
├───────────────┼───────────────────────────────────────────────────────┤
│ Vulnerable    │ All                                                   │
├───────────────┼───────────────────────────────────────────────────────┤
│ Patched       │ None                                                  │
├───────────────┼───────────────────────────────────────────────────────┤
│ Path          │ my-project > mocha@3.4.2 > growl@1.9.2 │
├───────────────┼───────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/146                │
└───────────────┴───────────────────────────────────────────────────────┘

**Comment by janvennemann** [comment]
As a workaround, until a decision was made on #2930 and mocha being a dev dependency in almost all cases, you can resort to only check your production dependencies with `retire -p`. NSP seems to do this by default as i'm getting no vulnerability warnings when running against a project that uses mocha as a dev dependency. If you still want to check your dev dependencies, explicitly ignore growl for the time being by adding `@growl` to your `.retireignore` or the more detailed [.retireignore.json](https://github.com/RetireJS/retire.js/tree/master/node#retireignorejson)

**Comment by nitrocode** [comment]
@janvennemann thanks

```
✗ cat .retireignore.json
[
  {
    "component": "growl",
    "version" : "1.9.2",
    "justification" : "Ignored according to mocha issue #2791: https://github.com/mochajs/mocha/issues/2791#issuecomment-319963186"
  }
]
```

**Comment by boneskull** [comment]
fixed

**Comment by tejsfrank** [comment]
I have updated to 1.10.2 still have this issue.
