### ISSUE TITLE
Mocha semver minor update 3.4.0 breaks builds

### ISSUE THREAD

**Issue by felixfbecker** [mochajs/mocha#2803]
Details and linked failed builds: 
https://github.com/sourcegraph/javascript-typescript-langserver/issues/253
https://github.com/felixfbecker/node-sql-template-strings/issues/38

**Comment by ScottFreeCode** [comment]
This should be fixed in version 3.4.1 after reports in #2799; do we need to do anything to trigger Greenkeeper to see 3.4.1?

**Comment by felixfbecker** [comment]
Probably just takes a while. Feel free to close or keep open for visibilty

**Comment by ScottFreeCode** [comment]
I'll go ahead and keep this open till we confirm that Greenkeeper's picking it up; it would kind of suck to have all these other issues out there still open after the fix is published...

Thanks!

**Comment by ScottFreeCode** [comment]
Per https://github.com/mochajs/mocha/issues/2799#issuecomment-301349268 it looks like Greenkeeper is picking up the new version, but I'm also seeing that some of these issues haven't yet been updated with it -- I think I'll keep this around for a while till we're confident nobody's going to open a new issue about their unresolved Greenkeeper issue, since GitHub tends to make open issues fairly obvious and closed issues, well, they're there but you have to look for them...

**Comment by j-f1** [comment]
@ScottFreeCode Are you planning to unpublish 3.4.0?

**Comment by ScottFreeCode** [comment]
It should already be unpublished; I did that next thing after publishing 3.4.1, hoping that doing so would help stem the tide of Greenkeeper, but I'm not sure if it actually made a difference...

**Comment by felixfbecker** [comment]
Imo unpublishing is never a good idea. If someone upgraded and locked his version with a lockfile, you broke his build even if we wasn't affected by the bug. 3.4.1 being a semver-patch clearly means that 3.4.0 had a bug that is now fixed in 3.4.1 and you should upgrade if you are affected.

**Comment by ScottFreeCode** [comment]
Feel free to tell the NPM people that.

In this case, the only projects that might not have been affected by the bug are those that either:
- are strictly Windows only, or
- are using Mocha only through the (undocumented) programmatic API

I'd be willing to bet that those are in the minority, and that the number of them who happened to find 3.4.0 and lock to it in the five minutes that it was the latest version are in the minority among that minority, and that among *that* minority anyone who isn't obsessively checking for the latest version so as to see 3.4.1 come out in turn is yet another minority.

That being said, for full disclosure, I had spent the weekend fighting two different operating systems just to get Mocha's publishing process to work (long story; well, medium story, but the details aren't really relevant here -- suffice to say I don't have an infrastructure department supporting my work on open source projects), and next thing I know I'm hit with literally hundreds, potentially thousands, of automated bots pointing fingers at me... I was afraid of becoming famous for having broken the internet like the Lefpad guy, and the minority of minority of minority of developers who hypothetically might be out there somewhere affected by the quick unpublish but not affected by the original bug, frankly, don't scare me as much. So there is that, whether objectively right or wrong. (I mention this, really, mostly because at this point I'm also nervous that I'm probably going to come off touchy about all this over the toneless text of the internet at some point if I haven't already, so, well, that may be because I am a bit touchy at the moment -- but nobody need take it personally.)

**Comment by felixfbecker** [comment]
Bugs happen

**Comment by boneskull** [comment]
@scottfreecode just use `npm deprecate` in future
