### ISSUE TITLE
double asterisk not working on mac

### ISSUE THREAD

**Issue by krzysztofpniak** [mochajs/mocha#2808]
I'm calling mocha with this line:
`mocha --compilers js:babel-register --require ignore-styles --require babel-polyfill ./client/**/*.spec.js`

It does work perfectly on windows machines, but on mac it only handles tests from the first level of directories, ie.
`./client/dirA/testA.spec.js`
but not test that are located deeper, ie.
`./client/dirA/dirB/testB.spec.js`

It looks like a bug, but for now I'm looking for a quick workaround for it.

**Comment by ScottFreeCode** [comment]
It's not so much a bug as a bad interaction between the conventions Mocha implements and the conventions your shell is configured to follow -- if you don't quote the path, the stars may be handled by the shell before the argument is even passed to Mocha, and some shells treat `**` the same as `*` instead of using the multi-directory behavior (at least by default; might be configurable in "globstar" settings...).

The workaround at the project level is to use `"./path/**/*.to.tests.js"` instead of `./path/**/*.to.tests.js`, which should work everywhere (since `"` is a valid argument quote on both Windows and Posixy shells).

**Comment by krzysztofpniak** [comment]
Thanks, quotes solved the problem. I didn't know that shell preprocess that paths. Now it looks logical.

**Comment by ScottFreeCode** [comment]
Glad we could help!

**Comment by javahaxxor** [comment]
I'm wondering if there is a bug. I'm getting this error on both OSX and Linux:
![screen shot 2017-12-12 at 18 29 33](https://user-images.githubusercontent.com/3932029/33899059-9230cf26-df6a-11e7-93b2-4ea5fd2d2317.png)
![screen shot 2017-12-12 at 18 31 32](https://user-images.githubusercontent.com/3932029/33899093-b3558c46-df6a-11e7-8bb2-97d2b9275eb7.png)
![screen shot 2017-12-12 at 18 33 29](https://user-images.githubusercontent.com/3932029/33899187-06433156-df6b-11e7-8b35-07e08189070d.png)

**Comment by ORESoftware** [comment]
MacOS comes with Bash version 3, not Bash version 4.

TMK, globbing works better on Bash version 4

**Comment by javahaxxor** [comment]
If you take a closer look at the screenshots, the last two are taken in Linux. Glob or - - recursive, same result regardless of platform
