### ISSUE TITLE
Code coverage for the client-side

### ISSUE THREAD

**Issue by tj** [mochajs/mocha#281]
probably best to remove jade, use one of the really small template engines so we can have it on both ends, less cruft

**Comment by Zhigalov** [comment]
It's actual problem, because when I install `mocha` with `iojs-v1.8` or next versions I get error:
``` bash
$ npm i mocha
npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/foo/.nvm/versions/io.js/v2.0.2/bin/iojs" "/Users/foo/.nvm/versions/io.js/v2.0.2/bin/npm" "i" "mocha"
npm ERR! node v2.0.2
npm ERR! npm  v2.9.0
npm ERR! path /Users/foo/bar/node_modules/mocha/node_modules/jade/bin/jade
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/foo/bar/node_modules/mocha/node_modules/jade/bin/jade'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by gogoleff** [comment]
+1

**Comment by boneskull** [comment]
@Zhigalov Not sure what's causing it, but I haven't encountered any problem like that

**Comment by boneskull** [comment]
anyway, I'm not sure if this ticket is something Mocha needs to be doing, since packages like [blanket](https://www.npmjs.com/package/blanket) purport to work in the browser

**Comment by xi** [comment]
Even if this will not be included in mocha, there is still stuff to do

-   The website claims that mocha has browser support *and* built-in coverage. It should be pointed out which features are actually available in the browser and which are not. I came to mocha specifically because it claimed to do both. It was kind of frustrating to find out that they are mutually exclusive.

-   I tried to make blanket work with mocha, but I failed. The mocha documentation does not even mention blanket. The blanket documentation only mentions mocha in the context of node, not the browser. So if you claim that this feature is not required in mocha because people can just use blanket, please mention that in the docs and give a brief example on how it can be done.

I would really like to help with these. If I find the time, I will create a pull request to the homepage for the first point. And if I make mocha work with blanket, I will create a pull request for the second one. But I feel like I am not the most qualified to do that.
