### ISSUE TITLE
Allowing functions to be passed in as titles as long as they have names

### ISSUE THREAD

**Issue by armsteadj1** [mochajs/mocha#2811]
This would allow functions or even React classes to be passed in when testing against them and allow for easier refactoring than praying IntelliJ finds all of your stings with that function in them.

For example: 

```
function addition (a, b) { return a+b; };
describe(addition, function () {
    it('will add the two numbers', function () {
       ....
    });
});
```

Now if `addition` were ever renamed to `addNumbers` our test would nicely be updated along the way.

**Comment by ScottFreeCode** [comment]
...I might be missing something, but wouldn't it do to just write it like this?
```js
function addition (a, b) { return a+b; };
describe(addition.name, function () {
    it('will add the two numbers', function () {
       ....
    });
});
```

**Comment by armsteadj1** [comment]
Considering the backwards compatibility issues with what I tried to create. :). That actually may be better off. I figured it would just be nice if that was wrapped up in mocha to clean up the code. I'm totally fine with your suggested route though.

**Comment by boneskull** [comment]
@armsteadj1 Relying on `Function.prototype.name` can be folly due to transpilation, minification, lack of support, etc.  It also makes for terse reporter output, as the function names cannot have a host of characters in them.

Maybe [reflect-metadata](https://npm.im/reflect-metadata) would be useful, or even TypeScript decorators?  Tagged template literals? This would be cool for some future Mocha.

Either way, if what you have works for you, you can create a custom ui and load it.

I'm going to close the associated PR, but thanks for bringing it up!
