### ISSUE TITLE
[Suggestion] Shift contributors from package.json to CONTRIBUTORS.md

### ISSUE THREAD

**Issue by kunagpal** [mochajs/mocha#2815]

**Comment by boneskull** [comment]
is there a precedent for this elsewhere?

**Comment by boneskull** [comment]
@kunagpal Anyhow, I'm a bit more interested in just automating the generation of the list from the commit history.

Usually I'll just run `git authors` from [/tj/git-extras] because Git respects the `.mailmap` file, then massage the output and stuff it into `package.json`.

It'd be nice to have that file automatically updated when we publish.

The authors list is cool and all but it seems tools depend on `package.json` to generate this data...  seems burdensome to hand-edit either one.  What do you think?
