### ISSUE TITLE
How to pull array values in post body request

### ISSUE THREAD

**Issue by kvb6682** [mochajs/mocha#2847]
Can anyone suggest a method to pull array values dynamically from and post in post body request along with other parameters.

**Comment by kunagpal** [comment]
@kvb6682 Could you provide deeper context on what you're trying to do, and how this relates to Mocha as well? 😄

**Comment by ScottFreeCode** [comment]
Since Mocha does not do HTTP requests, this is presumably a question about another library or API. As such I'm going to close it for now -- *with the caveat* that I would still be happy to try to help you find help for your issue (or even answer your question if I happen to know the answer) provided more info on what library or API you're using, so feel free to continue discussion here!
