### ISSUE TITLE
Suggestion: Add issue and pull request templates

### ISSUE THREAD

**Issue by kunagpal** [mochajs/mocha#2851]
Sample reference: 
https://github.com/atom/atom/blob/master/PULL_REQUEST_TEMPLATE.md
https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md

**Comment by ScottFreeCode** [comment]
Considering how often I link people to https://stackoverflow.com/help/mcve we might want to recommend it in the issue template. It might be less annoying to read it beforehand than to read it coming from me as the main response to an issue, heh heh.

We might also look at suggesting things to double-check for common issues, e.g.:
- next-gen ES issues and syntax problems should be checked against using the same environment and/or transpiler configuration *without* Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in the user's code
- similarly but more generally, "smoke-testing" the user code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, the user's usage of the test library, or the test library itself

**Comment by ScottFreeCode** [comment]
One thing I see in those templates that I haven't seen elsewhere but I particularly like is "Reproduces how often" -- it's great to acknowledge that some issues really are intermittent, and to give the maintainers a heads-up on whether it's possible the issue won't appear for them immediately when they try it so that doesn't just seem like something wrong on the user's end. (Of course, inconsistent reproduction is one of those things that goes down with a good, thorough MCVE, which is why I keep linking that too. But these are complementary measures.)

**Comment by ScottFreeCode** [comment]
We could put a link in the issue template to a search for issues with the "common mistake" tag too.
