### ISSUE TITLE
Does mocha watch the test files modified only?

### ISSUE THREAD

**Issue by mrdulin** [mochajs/mocha#2928]
I use `mocha -w --recursive` cli to watch my test files changed.

But it will re-run all my tests, even I just modify a single test file.

I want something like just watch and re-run the __modified test file__ tracked by `git`?

**Comment by maraisr** [comment]
Hi @mrdulin - very interesting! Mocha doesn't necessarily want to know about the GIT domain, because what about the Mercurial people and such.

Can I suggest you look into [Husky](https://github.com/typicode/husky) or [Lint Staged](https://github.com/okonet/lint-staged). Lint staged is probably what you're after, because it gives you a list of staged files.

**Comment by mrdulin** [comment]
@maraisr I am looking for a way that re-run the test file I modified , not all test files. Like `Jest` watch mode.

**Comment by junpos** [comment]
@mrdulin I had a similar issue and this is how I use to avoid re-run entire test suites. 
Instead of watching all test files, you can specify files that you want to test/watch only. 
For example, 
```js
// package.json
"tdd": "mocha ${TEST_FILES:-test/} --watch --recursive"
```

```sh
# terminal
TEST_FILES='test/a.spec.js test/b.spec.js' npm run tdd
```

This will only test files specified in `TEST_FILES` and watch the changes.

**Comment by mrdulin** [comment]
@junpos This seems like a manually work. My thought is If `mocha` know the test files modified which tracked by `git` . So `mocha` can re-run the modified test files.

**Comment by junpos** [comment]
@mrdulin I think `git` tracks all file changes not limited to test files. So Mocha doesn't know which files it should be watching at. Instead you can pass a list of filenames for Mocha with this simple bash script (I assume test files contain `.spec.js`)

```
# If your changes are not committed yet
mocha --watch $(git diff --name-only | grep .spec.js)

# If it's commited
mocha --watch $(git diff master... --name-only | grep .spec.js)
```

**Comment by mrdulin** [comment]
@junpos Yeah.`git` tracks all file changes. But `Mocha` should be care about the test files according to file extension or directory name. e.g: `*.spec.js`, `*.test.js`, `/__tests__/`.  

Can you take a look about `jest` `--watch` cli option? I don't know do I explain clearly.
https://facebook.github.io/jest/docs/cli.html#watch

**Comment by ScottFreeCode** [comment]
> ```js
> // package.json
> "tdd": "mocha ${TEST_FILES:-test/} --watch --recursive"
> ```
>
> ```sh
> # terminal
> TEST_FILES='test/a.spec.js test/b.spec.js' npm run tdd
> ```

This can be done without environment variables:
```js
// package.json
"test": "mocha --watch --recursive"
```

```sh
# terminal
npm test test/a.spec.js test/b.spec.js
```

OR in `test/mocha.opts`
```txt
-- watch --recursive
```

```sh
# terminal
mocha test/a.spec.js test/b.spec.js
```

* * *

> My thought is If  mocha  know the test files modified which tracked by  git  .

Mocha doesn't know anything about Git, Mercurial, SVN etc.

* * *

To answer the question as generally as possible:
- Any files passed to Mocha, whether by NPM script or by the CLI command, and any files specified in `mocha.opts`, are all "test files" -- they will be loaded with `describe`, `it` etc., which Mocha uses to run the tests.
  - The default file is the `test` directory; when a directory is specified Mocha will interpret it as referring to all `.js` files in that directory, or all `.js` files in the directory and all subdirectories if `--recursive` is also specified.
- `--watch` will rerun all the "test files" (see above) when any of the following are changed:
  - any files in the project, whether test files or not, with the `.js` extension
  - any files in the project, whether test files or not, with extensions specified in `--watch-extensions`

Mocha doesn't have any knowledge about which tests are testing which files; such a tool could presumably be built, but...

*The built-in `--watch` feature has never been favored by Mocha's maintainers to begin with*: the recommendation for more sophisticated watching behavior is to use an external watcher such as Chokidar (however, `--watch` has not been removed because we are aware of efficiency problems spawning an entirely new `mocha` process for each test run and [consistency problems when making multiple runs through the programmatic API](https://github.com/mochajs/mocha/issues/2176#issuecomment-305340676)).

**Comment by tomitrescak** [comment]
Hi, this script will allow you to execute only affected files. Please modify:

1. your mocha execution pattern to fit your needs
2. your test matcher

KNOWN ISSUE

This will not work if you are using imports by variables, such as `const b = 'path', const a = require(b)`

```js
var watch = require('node-watch');
var execSync = require('child_process').execSync;
var dependencyTree = require('dependency-tree');
var glob = require('glob');

var changedFiles = [];
var timeout = null;
var trees = {};

function buildDependencyTree(filename) {
  return dependencyTree({
    filename,
    isListForm: true,
    directory: './src',
    filter: path => path.indexOf('node_modules') === -1
  });
}

function scan() {
  glob('./src/**/*.test.ts?', {}, function(er, files) {
    trees = {};

    for (let file of files) {
      trees[file.replace('./', '')] = buildDependencyTree(file);
    }
  });
}

scan();

watch('./', { recursive: true, filter: /\.tsx?/ }, function(evt, name) {
  changedFiles.push(name);

  if (timeout) {
    clearTimeout(timeout);
  }
  timeout = setTimeout(() => {
    try {
      // build test list
      let tests = [];
      for (let file of changedFiles) {
        console.log('Check: ' + file);
        if (file.indexOf('.test') >= 0) {
          tests.push(file);
        } else {
          // find it in dependency tree
          for (let f of Object.getOwnPropertyNames(trees)) {
            if (trees[f].some(n => n.indexOf(file) >= 0)) {
              tests.push(f);
            }
          }
        }
      }

      changedFiles = [];

      if (tests.length) {
        let files = tests.join(',');
        const command = `CI=true TS_NODE_FAST=true ./node_modules/.bin/mocha -R luis-mocha-reporter --exit --require ./mocha.js --ui snapshots './src/tests/client_start.ts' '${files}' -P`;
        console.log('\n-- Running --\n');
        console.log(command);

        execSync(command);
      }
    } catch (ex) {
    } finally {
      scan();
    }
  }, 100);
});
```

Just add it to package.json as

```json
{
"watch": "node mocha-watch"
}
```

**Comment by sudhir512kj** [comment]
@tomitrescak Hello Sir, I am using node js API project using javascript only not typescript. Then may I use this script and how? Please help, urgently needed.
