### ISSUE TITLE
second then promise not work

### ISSUE THREAD

**Issue by pooya-az** [mochajs/mocha#2942]
Hi, i use mocha test
and in target function use multi then promise

```javascript
exports.getCompanyDetailsAll = function ($version, $response) {
    pg_vendor.openConn(global_config.dbConfig).then(function (db) {
        pg_vendor.query(db, 'my query')
            .then(_databaseResultOutput.bind(null, $version, 'companyDetailsAll', $response))
            .fail(_databaseErrorOutput.bind(null, $response, 1))
    }).fail(_databaseErrorOutput.bind(null, $response, 1))
}
```

and my mocha test script

```javascript
const codal = require('my_address/db');

//noinspection JSUnresolvedFunction
describe('Codal', function () {
    it('service check', function (done) {
        codal.getCompanyDetailsAll('v1', {
            writeHead: function () {
                console.log('>', arguments);
            },
            end: function () {
                console.log('>', arguments);
            }
        })
        done()
    })
});
```

in first script in pg_vendor.query first then executed but secend then function not called and no return output

**it's work with http server as well but with mocha not work**

---

**ps**

if i use defer in exports.getCompanyDetailsAll and return defer.promise, second then function is called and return output

```javascript
exports.getCompanyDetailsAll = function ($version, $response) {
   let defer = require('q').defer()
    pg_vendor.openConn(global_config.dbConfig).then(function (db) {
        pg_vendor.query(db, 'SELECT fa_name, fa_symbol FROM codal.companies')
        .then(function (data) {
            _databaseResultOutput($version, 'companyDetailsAll', $response, data, defer)
        })
        .fail(function (error) {
            _databaseErrorOutput($response, 1)
            defer.reject(error)
        })
    }).fail(_databaseErrorOutput.bind(null, $response, 1))
    return defer.promise
}
```

```javascript
describe('Codal', function () {
    it('service check', function (done) {
        codal.getCompanyDetailsAll('v1', {
            writeHead: function () {
                console.log('>', arguments);
            },
            end: function () {
                console.log('>', arguments);
            }
        }).then(function () {
            console.log('finish')
            done();
        }).fail(function (error) {
            done(error)
        })
    })
});
```

**Comment by ScottFreeCode** [comment]
> ```javascript
> exports.getCompanyDetailsAll = function ($version, $response) {
>     pg_vendor.openConn(global_config.dbConfig).then(function (db) {
>         pg_vendor.query(db, 'my query')
>             .then(_databaseResultOutput.bind(null, $version, 'companyDetailsAll', $response))
>             .fail(_databaseErrorOutput.bind(null, $response, 1))
>     }).fail(_databaseErrorOutput.bind(null, $response, 1))
> }
> ```

Assuming that `.fail` is an extension of a promise implementation being used here (I can only guess what libraries you're using based on these out-of-context snippets of code), you probably need to `return pg_vendor.query(...` so that the outer promise knows when the inner promise finishes -- in fact, you may be able to flatten such code to something like:

```javascript
exports.getCompanyDetailsAll = function ($version, $response) {
    pg_vendor.openConn(global_config.dbConfig)
    .then(function (db) {
        return pg_vendor.query(db, 'my query')
    })
    .then(_databaseResultOutput.bind(null, $version, 'companyDetailsAll', $response))
    .fail(_databaseErrorOutput.bind(null, $response, 1))
}
```

You may *also* want to `return` the `pg_vendor.openConn(...` promise, unless the `$response` object is intended to be reliably used to communicate results from this API (this may be more of a design point than a testing point, but I generally recommend sticking to either a promise API or a callback API rather than trying to mix the two; conversion from one to another is doable, but short of a dedicated automatic conversion approach it's often not as simple as it looks and error-prone to have to handle it in multiple places).

> ```javascript
> const codal = require('my_address/db');
> 
> //noinspection JSUnresolvedFunction
> describe('Codal', function () {
>     it('service check', function (done) {
>         codal.getCompanyDetailsAll('v1', {
>             writeHead: function () {
>                 console.log('>', arguments);
>             },
>             end: function () {
>                 console.log('>', arguments);
>             }
>         })
>         done()
>     })
> });
> ```

`done` is called immediately here; once `done` is called Mocha considers the test to be finished. If callback functions should be used with the API, you should call `done` in the callback(s); if promise completion should be used with the API, you should remove `done` and `return` the promise in the test function so Mocha can wait for the promise to resolve or reject (it will treat this as success and failure respectively). More details here: https://mochajs.org/#asynchronous-code

**Comment by pooya-az** [comment]
my problem resolve with move done() to fake end function.

```
const codal = require('my_address/db');

//noinspection JSUnresolvedFunction
describe('Codal', function () {
    it('service check', function (done) {
        codal.getCompanyDetailsAll('v1', {
            writeHead: function () {
                console.log('>', arguments);
            },
            end: function () {
                console.log('>', arguments);
                done()
            }
        })
    })
});
```

sorry for ask simple question 😁
