### ISSUE TITLE
emit retry so we know when tests are using this feature

### ISSUE THREAD

**Issue by fpereira1** [mochajs/mocha#2950]
Hi,

I would like to know which of my tests are being retried but, with existing mocha this is not possible.

I was thinking to emit 'test retry' on the block below and then, the reporters could display this. https://github.com/mochajs/mocha/blob/075bd51906b828812b320f33cd1c7fa60d1702f1/lib/runner.js#L556-L563

Would it be possible to add this, or is there another way that this can be achieved?

Thanks!

**Comment by ScottFreeCode** [comment]
This has actually been discussed in #2529 (although it's not as clear if it's what that issue was about from the start), and an implementation submitted in #2926. #2901 also adds information to the test object that would, presumably make it possible to view the retried failures at the point when the test ends and the existing events are emitted, but does not allow these errors to be seen at the time when they actually occur (see https://github.com/mochajs/mocha/issues/2529#issuecomment-315510743 for more detail).

/cc @mochajs/core Let's not forget to review those at some point.

**Comment by fpereira1** [comment]
@ScottFreeCode perfect thank you. Closing this for the issue https://github.com/mochajs/mocha/issues/2529
