### ISSUE TITLE
Mocha ignoring .litcoffee files in test/

### ISSUE THREAD

**Issue by joaomlneto** [mochajs/mocha#2964]
Hi!

I'm using [iced-coffee-script](http://maxtaco.github.io/coffee-script/), which is essentially coffeescript for our purposes AFAIK.

I have a few `.litcoffee` files inside `test/`, and running `mocha --compilers coffee:iced-coffee-script/register` will result in:
```
No test files found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mypackagename@0.0.0 test: `mocha --compilers coffee:iced-coffee-script/register`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mypackagename@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Issuing `mocha --compilers coffee:iced-coffee-script/register test/*.litcoffee` runs all files just fine:
```
  File1
    ✓ Test1-1
    ✓ Test1-2
  File2
    ✓ Test2-1
    ✓ Test2-2
  4 passing (0ms)
```

If I add a `.coffee` file to the `test/` directory, running `mocha --compilers coffee:iced-coffee-script/register` results in:
```
  SimpleCoffeeFile1
    ✓ Test1-1
    ✓ Test1-2
  2 passing (0ms)
```

**Comment by ScottFreeCode** [comment]
If you change `--compilers coffee:<module>` to `--compilers litcoffee:<module>` Mocha should look for `.litcoffee` files instead of `.coffee` files; let us know if that resolves your issue!

**Comment by joaomlneto** [comment]
That solves the issue! Thanks!

I hadn't really understood that `coffee:` was the file extension. Sorry :)
Would be nicer to handle both coffeescript file extensions implicitly

**Comment by ScottFreeCode** [comment]
Glad we could get that resolved! (I'm going to close this issue for now since that's addressed, but feel free to continue discussion of the `--compilers` option; in fact...)

> I hadn't really understood that  coffee:  was the file extension. Sorry :)

No need to be sorry; we could use better documentation about what exactly `--compilers` does, instead of just the usage examples we have.

> Would be nicer to handle both coffeescript file extensions implicitly

Well, although the examples are all about Coffeescript (I guess it was the popular transpile-to-JS at the time Mocha was first developed?), I'm fairly sure there's nothing specific about any one compiler in the `--compilers` code. In fact, it's pretty much just a shorthand for "add the extension on the left to the default glob (and `--watch-extensions` if `--watch` is used) and `--require` the file on the right". Could be Typescript, Purescript, next-gen ECMAScript Modules ("Michael Jackson Script"), you name it... as long as it has a file extension and a module that can effect the transpilation just by being `require`d before the modules that need to be transpiled, `--compilers` lets the user specify it. (And if it only needs a file extension, then it's even simpler to forego `--compilers` and use `path/to/files/*.extension`; likewise, if it only needs a transpiler and the extension is JS, it's simpler to just use `--require transpiler`.)

There's even been talk of deprecating/removing `--compilers` in favor of improving the documentation on how to glob multiple file extensions while `--require`ing a transpiler to handle them (since it's equivalent to doing so) -- I want to say off the top of my head it's something like `mocha --compilers extension:transpiler folder` is equivalent to `mocha --require transpiler --watch-extensions extension "folder/*.{js,extension}"` (or maybe `(js,extension)`; I'd have to double-check the docs for our Glob dependency) but you can simplify that to just `mocha --require transpiler folder/*.extension` if you're not using JS files or `--watch`.
