### ISSUE TITLE
Cannot read property 'timeout' of undefined

### ISSUE THREAD

**Issue by YevheniiHerasymchuk** [mochajs/mocha#2966]
`Uncaught TypeError: Cannot read property 'timeout' of undefined`
Error occurs when trying to skip test with increased default timeout.
``` 
  xit('true equals true', (done) => {
    setTimeout(() => {
      expect(true).to.be.true
    }, 2200)
  }).timeout(3000)
```
Both ```xit``` and ```it.skip``` don't work.

**Comment by ScottFreeCode** [comment]
Someone else on the team can chime in if they know otherwise, but I am not sure that `it("test", ...).timeout(<number>)` is meant to be supported in the first place (as opposed to an accidental artifact of how the object hierarchy and interfaces were structured historically). The "canonical" way to configure Mocha's tests is to use non-arrow functions and call the functions on `this`. There's more detailed discussion of the incompatibility between arrow functions and Mocha's `this`-based configuration in #2018 (and it is already brought up in other places, including multiple GitHub issues and documentation on Mocha's website).

**Comment by boneskull** [comment]
that isn't in the API, no.
