### ISSUE TITLE
Puppeteer support

### ISSUE THREAD

**Issue by sauliusgrigaitis** [mochajs/mocha#2967]
Is there any plans for [Puppeteer](https://github.com/GoogleChrome/puppeteer) support?

**Comment by ScottFreeCode** [comment]
Is Mocha not usable with Puppeteer now? It looks like an alternative to Selenium; if that's accurate, you should simply be able to use it inside `it`.

**Comment by sauliusgrigaitis** [comment]
Thanks @ScottFreeCode , something like [mocha-puppeteer](https://github.com/charlieduong94/mocha-puppeteer). But maybe that's out of `mocha` scope.

**Comment by ScottFreeCode** [comment]
Ah -- yeah, I think that's outside the scope of Mocha; we've had a lot of success with Karma, which is an entirely separate tool that can run tests for Mocha (or other test runners!) in a variety of different browsers, and it seems unlikely that there's anything to be gained by building such functionality into Mocha directly when separate projects can use Mocha that way and even compete with (or complement, or build on) each other. (I also don't know enough about Puppeteer to know whether this use of is a huge hack or not -- with Selenium I know you *could* run tests inside the browser using `executeScript`, but it's an indirect approach and has all the overhead of Selenium's user interaction simulation being pulled in and then ignored.) In fact, I'd be interested in whether Puppeteer makes it easier to create a Karma browser runner (Karma supports so many browsers by having a plugin to run each browser) for headless Chrome, which would then benefit not only Mocha but any test runner that Karma supports and would be easy to plug into any existing Karma test setup! But in any case having dedicated tools for each element of the test process that compose, rather than requiring one tool to do it all, is the modular and scalable approach; as long as Mocha doesn't need to do something specific to make this usage feasible, we'll probably just want to continue on and keep an eye on such projects in order to make recommendations.
