### ISSUE TITLE
--bail option does not work for dynamically generated tests.

### ISSUE THREAD

**Issue by rps1007** [mochajs/mocha#2970]
Running the following code 'npm test --bail' will run the test even after first failure
-----------------------------------------------------------------
var test= function() {
  describe('Test Print', function () {
   var x=[1,-1,2,3]
   x.forEach(function(num){
       it('Test1:'+num, function () {
            assert.notEqual(num,-1);
        });
      it('Test2:'+num, function () {
            assert.equal(num,5)
        });
    });
});
}

test();
-----------------------------------------------------------------
Result
  Test Print
    ✓ Test1:1
    ✓ Test2:1
    1) Test1:-1
    ✓ Test2:-1
    ✓ Test1:2
    ✓ Test2:2
    ✓ Test1:3
    ✓ Test2:3

  7 passing (10ms)
  1 failing

**Comment by larstonne** [comment]
Hmm i will have to take a further look i am actually using a testfactory to generate tests

**Comment by ScottFreeCode** [comment]
Hi @rps1007,

It's unlikely that the `--bail` option would treat dynamically generated tests differently, since Mocha doesn't really "know" whether a test was generated dynamically (whether dynamic or not, it's just a call to `it`); nonetheless, I'm taking a look into this to see if there's something else causing a problem with `--bail`.

I tried adding `var assert = require("assert")` and `test()` to the example code you posted and wasn't able to reproduce that output either with or without `--bail`; without `--bail` it got five errors instead of one, and with `--bail` it stopped after the first error as expected. Is it possible there is something else we're not seeing about your tests that could relate to this issue? If we can get a complete example that demonstrates the problem if we copy-paste the example into an empty project (while still being minimal like this!), that would help us track down what's going on.

**Comment by larstonne** [comment]
`    bailtest: function (x) {
        x.forEach(function (num) {
            it('Test1:' + num, function () {
                this.retries = 3;
                assert.notEqual(num, -1);
            });
        });
    }`

this is my util function

`describe('Smoketest: Bail', function(){

    util.bailtest([1,-1,2,3]);

});`

Thats the call. This test is run in docker with bail option. Here is result:

  Smoketest: Bail
    âœ“ Test1:1 (1ms)
    1) Test1:-1


  1 passing (9ms)
  1 failing

  1) Smoketest: Bail Test1:-1:

      AssertionError [ERR_ASSERTION]: -1 != -1
      + expected - actual

      
      at Context.<anonymous> (/util/util.js:86:24)



npm ERR! Test failed.  See above for more details.

This is the part of package.json it gets called from:

  "scripts": {
    "test": "mocha --bail"
  },

**Comment by ScottFreeCode** [comment]
Well, there's a couple things going on here. One is that you should call `this.retries(3)` rather than `this.retries = 3`. Even with that changed, however, this looks like the correct behavior: `this.retries(3)` makes Mocha run the test up to three times trying to get it to pass, but if it fails all three times Mocha will report the final failure -- and `assert.notEqual(<dynamically generated -1 variable>, -1)` will fail all three times. It doesn't report the other failures, but you can run the same set of tests without `--bail` and see that it only reports the failure once then as well, or change your util function to this:
```js
function (x) {
  x.forEach(function (num) {
    var retryCount = 0
    it('Test1:' + num, function () {
      this.retries(3);
      retryCount += 1;
      console.log("test for", num, "attempt", retryCount);
      assert.notEqual(num, -1);
    });
  });
}
```
...and you should see output along these lines:
```txt
> Smoketest: Bail
> test for 1 attempt 1
> :checkmark: Test1:1 (1ms)
> test for -1 attempt 1
> test for -1 attempt 2
> test for -1 attempt 3
> 1) Test1:-1
> 
> 1 passing (9ms)
> 1 failing
```
