### ISSUE TITLE
Describe block with async function behaving weirdly

### ISSUE THREAD

**Issue by shashi-raja** [mochajs/mocha#2975]
Mocha **3.5**
Node **8.4**

```
describe('Test Suite 1', async function(){
  let email = await faker.internet.email();
  it('should print email', function(){
     email.should.not.be.a('string')
   )}
})
```
Running this test should give
```
Test Suite 1
   ✓should print email
```
But its giving
`0 passing`

Also modifying the above code to
```
describe('Test Suite 1', async function(){
  let email;
  it('should print email', async function(){
     email = await faker.internet.email()
     email.should.not.be.a('string')
   )}
})
```
Runs the test but doesn't print the name of describe i.e Test Suite 1
 ` ✓should print email`
Removing the async from **describe** and putting it in **it** works fine
```
 describe('Test Suite 1', function(){
  it('should print email',async  function(){
     let email = await faker.internet.email();
     email.should.not.be.a('string')
   )}
})
```
```
Test Suite 1
   ✓should print email
```

Also .**only** and **.skip** do not work when **async** function is included in the **describe** block

**Comment by ScottFreeCode** [comment]
Async functions are syntactic sugar for returned promise chains, and Mocha's `describe` blocks do not support (as in waiting for resolution of) returned promises. Failing to warn about it is perhaps less helpful than it could be, but the behavior is pretty much expected under the current design.

For cases where the names of the tests or how many tests there are can only be determined asynchronously, there is [the `--delay` option](https://mochajs.org/#delayed-root-suite), although that still requires the entire `describe` to occur after the asynchronous info is obtained (`it` still must be called synchronously inside `describe` before the `describe` returns).

If you don't need the data to define the tests but only to run them, you can use async `before`/`beforeEach` hooks to get it (that would be the obvious way to do these trivial examples), or even async tests with the initial methods to obtain the data written into the start of the test.

If you can come up with a real use case where `--delay`'s limitations are needlessly awkward but it can't just be done with `before`/`beforeEach` since the definition of tests depends on it, then a case could be made for adding promise support (from which async function support would automatically be derived) to `describe`.

**Comment by caphale** [comment]
@ScottFreeCode  , I have similar problem noted above.

Describe('some statement', function(){

before(function(done){

some async function;
done();
});
async.eachSeries(test,function(test,call){
it ('should test---', function(){

    });
})

})

It block does not wait till before is complete. ' it' races around .

Now remove the async function , (dynamically forming tests). Before works as expected.

**Comment by ScottFreeCode** [comment]
Hi @caphale,

I get errors if I copy-paste this code into a new test file and try to run it, so I can't exactly debug what's happening. I don't even know whether by "Now remove the async function..." you mean the asynchronous code in the `before` or the `async.eachSeries` -- although it's more important that *both* might be incorrect, but I cannot necessarily tell how so given my lack of knowledge of where `async.eachSeries` comes from and what code structure has been replaced with "some async function;" in the `before`.

I can take some guesses, but these are just guesses:
- Does the `before` block really look something like this?
  ```js
  before(function(done) {
    thisFunctionHappensToBeAsync()
    // or
    ;(async function() {
      // setup steps here
    })()
    done()
  })
  ```
  If so, either move `done` inside the async function, or change it to this:
  ```js
  before(thisFunctionHappensToBeAsync)
  // or
  before(async function() {
    // setup steps here
  })
  ```
  The slightly longer "why" is that `done` tells Mocha that you've finished executing your asynchronous steps and `before` has completed running; if you call `done` after you've made the function calls that *schedule* the asynchronous setup but before those asynchronous steps actually complete, Mocha cannot know that it has to wait for them to complete (because you're telling Mocha that they already have); instead you'd need to call `done` *in* (at the end of) the asynchronous steps.
- I'm not familiar with `async.eachSeries`, but I assume from the name that the callback is not called synchronously, so those `it`s are presumably being created outside the `describe` suite (since as previously mentioned `it` must be called before `describe` returns and not in their own asynchronous callbacks, whether `describe` is called in an asynchronous callback or not). The following points need to be kept in mind when designing the correct test structure:
  - If you don't need the asynchronous data to determine the number of tests or their names, then call `describe` and `it` synchronously instead and get the asynchronous data in an asynchronous or promise-returning `before` (or even directly in an asynchronous or promise-returning test).
  - If you do need to use asynchronously retrieved data to determine the number or names of `it`s, you must use whatever asynchronous API you have to gather all the data and *in a single, final callback* call `describe` and all the `it`s inside it followed by `run()`, then add the `--delay` option to running Mocha.
* * *
P.S. If you wrap your code in:
\`\`\`js
(code here)
\`\`\`
...GitHub will format it much better.

**Comment by bennypowers** [comment]
I want to fetch test data and use it to partially apply a validation function. doing it in beforeEach would defeat the purpose, since I wouldn't have the data outside the scope of the test

```js
suite('muh data', async () => {
  const DATA = await fetch('data.json').then(jsonify);

  // checks that only path has changed
  // original -> path -> obj -> assertion
  const validatePropChanges = curry((original, path, obj) {/* yadda yadda */});

  const validate = validatePropChanges(DATA);

  test('incrementFoo only increments foo', () => {
    const cloned = clone(DATA);
    incrementFoo(cloned);
    cloned.foo.should.equal(DATA.foo + 1);
    validate('foo', DATA)
  });

```

**Comment by Bamieh** [comment]
@bennypowers

```javascript
const validatePropChanges = curry((original, path, obj) {/* yadda yadda */});

suite('muh data', function() {
   let validate;
   let DATA;
   before(async function() {
     const DATA = await fetch('data.json').then(jsonify);
     validate = validatePropChanges(DATA);
   })


  test('incrementFoo only increments foo', () => {
    const cloned = clone(DATA);
    incrementFoo(cloned);
    cloned.foo.should.equal(DATA.foo + 1);
    validate('foo', DATA)
  });
```

**Comment by outsideris** [comment]
It's not stale because of #3243

**Comment by ofrobots** [comment]
In TypeScript projects, the lack of ability to use async describe functions leads to the follow.

I want to write:
```ts
describe('express middleware', async () => {
  const {logger, mw} = await elb.middleware({level: 'info'});
  // ...
}
```

What I need to write:
```ts
describe('express middleware', () => {
  type ThenArg<T> = T extends Promise<infer U> ? U : T;
  type ElbThenType = ThenArg<ReturnType<typeof elb.middleware>>;
  let logger: ElbThenType['logger'];
  let mw: ElbThenType['mw'];

  before(async () => {
    ({logger, mw} = await elb.middleware({level: 'info'}));
  });
```

It would be quite handy if `describe` were to wait for the promise to resolve if one was returned. Is that possibility, or is there something fundamental that prevents this from ever happening.

**Comment by pronebird** [comment]
Is there any plan to fix this? I need async `describe` to spin off mongo before creating the app and running tests.

**Comment by plroebuck** [comment]
Why not spin up MongoDB in root-level `before()`, or use `--delay` with `this.run()`?

**Comment by pronebird** [comment]
@plroebuck `--delay` could work. That's the scenario I have:

```
describe("Suite", async () => {
  const mongoURI = await spinOffMongoAndReturnConnectionString();
  const configuration = {
    ...readConfigFromEnv(),
    mongoURI
  };
  const expressApp = createTestApp(configuration);

  it('should do magic', async () => {
    const res = await chai.request(expressApp).put('/some/url').send({ ... });
    res.body.should.be.equal(true);
  });
})
```

**Comment by plroebuck** [comment]
Maybe...
```js
let dbconn;

before(async () =>
  dbconn = await spinOffMongoAndReturnConnectionString();
);

describe("Suite", () => {
  let expressApp;

  before(() =>
    const configuration = {
      ...readConfigFromEnvSync(),
     dbconn
    };
    expressApp = createTestAppSync(configuration);
  );

  it('should do magic', async () => {
    const res = await chai.request(expressApp).put('/some/url').send({ ... });
    res.body.should.be.equal(true);
  });
})
```

**Comment by pronebird** [comment]
@plroebuck Thanks. Surely that works except that Flow doesn't know how mocha works so it will likely force me to check if `expressApp` is null in each occurrence. Doh.. :/

**Comment by plroebuck** [comment]
LOL...
```js
  it('should do magic', async () => {
    // $FlowMocha
    const res = await chai.request(expressApp).put('/some/url').send({ ... });
    res.body.should.be.equal(true);
  });
```

".flowconfig"
```
suppress_comment= \\(.\\|\n\\)*\\$FlowMocha
```

**Comment by alex-at-cascade** [comment]
I struggled with this same problem for a while (certain tests mysteriously not running) until I found this issue posted.  I had just assumed `describe` would wait for promises the same way `it` does.  I can work around it, but it would be wonderful if `describe` could just recognize `async` functions and behave accordingly.

**Comment by plroebuck** [comment]
@alex-at-cascade, well at least you'll get a warning from the upcoming release...

**Comment by WORMSS** [comment]
Just to add to the discussion that our company got caught out by the non-async nature of describe when a developer changed from `require` to `import` to match the rest of the system. Sadly this caused no errors, and was only during the addition of `.only()` by myself that the test reported `0 Passed` when I knew there should be 38 that either passed or failed.`

```javascript
describe.only('aqs.utils', async () => {
  await import('./equals');
  await import('./gas');
  await import('./notEquals');
  await import('./startsWith');
  await import('./wordSearch');
});
```

We went back to the original and now works as expected, but I think we would prefer to use `import`

```javascript
describe.only('aqs.utils', () => {
  require('./equals');
  require('./gas');
  require('./notEquals');
  require('./startsWith');
  require('./wordSearch');
});
```

**Comment by ondratra** [comment]
Because I want to prevent my code from having Hadouken indent (http://i.imgur.com/BtjZedW.jpg), I wanted to use this design:

*test.ts*
```
import mySubtest1 from './subtests/component1'

describe('1st level describe', async () => {
    const prerequisites = await serverINeedToRunBeforeTests()

    describe('2nd level describe', mySubtest1(prerequisites))
})
```

*./subtests/component1.ts*
```
export default testComponent1(prerequisites) {
    // test the component
    it('does what it should', () => void)
}
```

In this scenario `before()` can't help me so I am forced to rewrite the code and use `--delay`. Delay is not optimal in such situation because it brings unnecessary waiting when is set delay high while it can start things prematurely when delay is set low. Async here is elegant solution.

@ScottFreeCode Is there any obstacle in implementing async support for describe?

**Comment by plroebuck** [comment]
@ondratra, why can't `before()` work for you?

**"test.ts"**
```
import testComponent1 from './subtests/component1';

describe('1st level describe', () => {
  let prerequisites;

  before(async () => {
    prerequisites = await serverINeedToRunBeforeTests();
  });

  describe('2nd level describe', () => {
    testComponent1(prerequisites);
  });

  after(() => {
    disconnectFromServerINeedToRunBeforeTests();
    prerequisites = undefined;
  });
});
```

**Comment by ondratra** [comment]
@plroebuck Sry I should have added definition of `testComponent1()` for better illustration. When `testComponent1()` is async, the code you wrote won't run any test (properly) and finish with message `0 passing (0ms)`.

**Comment by ondratra** [comment]
@plroebuck Sry I wrote bad definition of `testComponent1()`. It should be async: 
```
export default async function testComponent1(prerequisites) {
    // test the component
    it('does what it should', () => void)
}
```

When `testComponent1()` is async, the code you wrote won't run any test (properly) and finish with message 0 passing (0ms). One of reasons you might want to have `testComponent1()` async is when you want to load another component specific prerequisites inside.

**Comment by ondratra** [comment]
@plroebuck after more thinking and testing I found out your design solves the issue.

**Comment by junaid1840** [comment]
I have found another way to get things done.
May be this could work for someone.
`describe('Parent', () => {
    let array: any = [];
    before(async () => {
        array = await someAsyncDataFetchFunction();
        asyncTests();
    });
    it('Dummy test to run before()',async () => {
        expect(0).to.equal(0); // You can use this test to getting confirm whether data fetch is completed or not.
    });
    function asyncTests() {
        array.forEach((currentValue: any) => {
            describe('Child', async () => {
                it('Test '+ currentValue ,() => {
                    expect(currentValue).to.equal(true);
                })
            })
        });
    }
});`

That's how I achieved the assertion on every element of the array. (Array data is being fetch asynchronously).
Kindly correct me if I'm doing it wrong.

**Comment by WORMSS** [comment]
You will fall into the same problem I was having junaid, those inner 

> ```
>         array.forEach((currentValue: any) => {
>             describe('Child', async () => {
>                 it('Test '+ currentValue ,() => {
>                     expect(currentValue).to.equal(true);
>                 })
>             })
>         });
> ```
Will not be contained within the "child" describe and will actually be outside the scope of the tests. Don't get me wrong, they will run, but they won't be counted towards where you think they will be.

**Comment by danielbodart** [comment]
Is there any plan to fix this in the long term?

**Comment by jcollum** [comment]
Yeah this behavior is a pain, resulted in a lot of weird race conditions for me. 

What worked for me: if you need `async`, do it in your `before` blocks.

**Comment by craigphicks** [comment]
Analysis of design change required to allow async-describe.
----

It is understandable that async-describe doesn't work because there is no explicit reference to a parent `describe` object passed to an `it` object being constructed.  I assume the `it` object constructor accesses a mocha global  current-describe variable maintained **only** in the context of the main fiber (although I am not sure exactly how that is done).

A design change to allow async-describe would require altering interfaces to expilcitly pass the intended parent `describe` object, e.g., 
```
const parentd = mocha.topd()
parentd.describe('description', async function(parentdx){
  ....
  parentdx.it('test', function(pd){ ... })
  ...
}
```
or 
```
const parentd = mocha.topd()
describe('description', parentd, async function(parentdx){
  ....
  it('test', parentd, function(parentdx){ ... })
  ...
  describe('subdescribe', parentd, function(parentdx){ ... })
  ...
}
```
Notice the different spellings for `parentd` and `parentdx` to make clear here that they are not the same object.  They needn't actually be different spellings because their scopes are different.

The mocha back end would then have a describe-tree with it-leaves that it could walk to get the proper reporting order even though the temporal order of starting each describe-node/it-leaf were not the proper reporting order.

**Comment by cinderblock** [comment]
the `before` block does not seem to be working for me.

```ts
describe('my lib', () => {
  const arr: number[] = [];
  before(async () => {
    arr.push(await referenceImplementation());
  });
  descripbe(`should work`, () => {
    if(`like this ${arr[0]}`, () => {
      'test'.should.equal('test');
    });
  });
});
```

Regardless, why is there such resistance to `async`/`await`?

Technically one can do anything without `async`/`await`... but we do it anyway because it's so much nicer. This causes major headaches otherwise.

**Comment by WORMSS** [comment]
I believe they want to keep the "build up the structure of where the tests are" as synchronous as possible.

**Comment by juergba** [comment]
Mocha runs in different cycles, we have a description of those in our docs.

In the "parsing" cycle all `describe` callbacks are excecuted and the test hierarchy (`runner`) is created. Those callbacks are indeed synchronous. None of the tests/hooks will be run at this time. That's why `[${whatever}]` is `undefined`.

Then in the next cycle the `runner` is launched and `whatever` should have a value, since `async/await` does work in hooks.

If you need to run an aynchronous job before `runner` is created, you can eg. use `top-level await` as described in our docs (dynamically generating tests).

**Comment by cinderblock** [comment]
I hadn't see top-level await was available on mocha. That should work for my purposes however TS -> ESM support is still new. Still don't see how it makes sense to prevent this.

**Comment by ahilton-godaddy** [comment]
@juergba just to add a use case for the reason you may with a async describe block. 

I am generating some dynamic tests, and without being able to dynamically describe `it` blocks, it makes dynamic test generation a difficult thing to do, and something people do attempt :D

**Comment by jcollum** [comment]
I thought `it` blocks were async but `describe` blocks were not... Or is
that Jest?

**Comment by cinderblock** [comment]
@jcollum You are correct. I'm wondering why `describe` blocks cannot be made async.

**Comment by Mikkal24** [comment]
> Just to add to the discussion that our company got caught out by the non-async nature of describe when a developer changed from `require` to `import` to match the rest of the system. Sadly this caused no errors, and was only during the addition of `.only()` by myself that the test reported `0 Passed` when I knew there should be 38 that either passed or failed.`
> 
> ```js
> describe.only('aqs.utils', async () => {
>   await import('./equals');
>   await import('./gas');
>   await import('./notEquals');
>   await import('./startsWith');
>   await import('./wordSearch');
> });
> ```
> 
> We went back to the original and now works as expected, but I think we would prefer to use `import`
> 
> ```js
> describe.only('aqs.utils', () => {
>   require('./equals');
>   require('./gas');
>   require('./notEquals');
>   require('./startsWith');
>   require('./wordSearch');
> });
> ```

wanted to add to this by mentioning that [ESM is now the official standard for Node.js](https://nodejs.org/api/esm.html#modules-ecmascript-modules) and require is no longer available within ESM scope. 

I do love splitting up my tests this way and I hope Mocha can support asynchronously importing test files in the future. IMHO this issue should be opened back up.

**Comment by cinderblock** [comment]
That mocha reports "all good" after "0 Passed" (because it thought no tests had been defined) is one of the problems here. It's easy to blindly switch to `import`s and see "all green" on tests, not realizing that tests were not even being run.

@Mikkal24 Have you see the (new in v9.1) [`--fail-zero` option](https://mochajs.org/#-fail-zero)?

**Comment by Mikkal24** [comment]
> That mocha reports "all good" after "0 Passed" (because it thought no tests had been defined) is one of the problems here. It's easy to blindly switch to `import`s and see "all green" on tests, not realizing that tests were not even being run.
> 
> @Mikkal24 Have you see the (new in v9.1) [`--fail-zero` option](https://mochajs.org/#-fail-zero)?

I am aware that that switching to imports results in the tests not executing. I assume this is because the import function returns a promise and `describe` does not support promises which was the purpose of this issue. 

I just wanted to tack on to what @WORMSS said in 2018 because while `import` was a "nice to have" it's now required in the official standard of Node.js since `require` doesn't exist in ESM. 

I can only hope Mocha devs will support this syntax in the future.

```ts
describe("some group", async ()=>{
    await import("myModule.js");
    await import("myOtherModule.js");
})
```

would help a lot with maintaining large code bases. (TBF I've only got like 100 test files, I would be desperate for this if I had 4200 lol)

**Comment by farwayer** [comment]
@juergba it looks like more and more people are falling into this trap. It's a bit dangerous when the testing tool just stops running part of the tests without any errors or warnings. And the lack of support for asynchronous `describe` violates the golden rule of predictable behavior. If async `it` is supported, it's reasonable to assume that async `describe` should also works.

For me, the main reason for using async `describe` is to import ESM modules. And even if there are several stages of test execution, why not wait for async `describe`?

**Comment by ViSaturn** [comment]
Asynchronous describe would be really useful to me in my situation, I have a recursive function that loops through an object and dynamically imports a file (dynamic imports are async) corresponding to the index, creates an `it` if the import works, or creates a pending `it` if the import fails. In mocha I could not get this behavior to work and thought it would look awkward if I had half of the code for my describe.. outside of the describe, I originally just expected that if I returned a Promise, it would allow me to define `it`'s until the promise is resolved, but this is not the case. A `before()` wouldn't work because the definition of the tests depends on the imports which would be placed in the `before()` itself, which would not run before I define a test.

**Comment by krzkaczor** [comment]
@boneskull can we reopen this as it's still not fixed?

**Comment by mcdurdin** [comment]
[juergba](https://github.com/juergba) commented [on Jan 3, 2022](https://github.com/mochajs/mocha/issues/2975#issuecomment-1004176440):
> Mocha runs in different cycles, we have a description of those in our docs.
> 
> In the "parsing" cycle all `describe` callbacks are excecuted and the test hierarchy (`runner`) is created. Those callbacks are indeed synchronous. None of the tests/hooks will be run at this time. That's why `[${whatever}]` is `undefined`.
> 
> Then in the next cycle the `runner` is launched and `whatever` should have a value, since `async/await` does work in hooks.

This is helpful information which I could not find in the documentation. There's no reference to 'parsing' anywhere and the asynchronous discussion does not mention the fact that `describe()` will not accept an async function. So I've opened a PR at https://github.com/mochajs/mocha/pull/5046, hope that is useful.
