### ISSUE TITLE
Disabling linting errors when writing test files?

### ISSUE THREAD

**Issue by pfftdammitchris** [mochajs/mocha#2976]
![capture](https://user-images.githubusercontent.com/20717348/29894633-d7aff95a-8d8a-11e7-9aa5-03d3244e7d2f.PNG)

Those errors are pretty useless and annoying when it comes to writing test files.  "Cannot find name 'describe.'". How would I go about disabling these errors? I tried writing `/* eslint-disable */` at the top and it didn't work. I tried the same thing but replacing the eslint with tslint since im using typescript and it still doesn't work. 

I create a .eslintignore file in the directory and it still doesn't make those fake-errors disappear. 
What is the solution? Thank you

**Comment by ScottFreeCode** [comment]
You can see if [`require`ing Mocha's functions](https://mochajs.org/#require) resolves the linting errors for them (note that the documentation is a little misleading in naming this technique: it's not a separate interface named "require", it's an alternative way of getting the functions from either the BDD or the TDD interface as long as one or the other of those two is chosen).

Beyond that, we don't have any special insight into the trouble configuring the linter: it might be tripping over the transpilation from TS to JS, or it might be that your editor isn't picking up the right linter or the right configuration files, or who knows what... Well, actually, *who* would know is the big question -- the trouble probably comes from your specific setup of Typescript, your editor and ESLint/TSLint, so looking for support related to each of those is more likely to turn up some answers.

**Comment by platinumazure** [comment]
@pfftdammitchris Are you talking about running ESLint while writing tests?

If so, you can do one of the following (in increasing order of "best practice"):

1. Add `/* global describe,it */ (and anything else) somewhere in the file, conventionally done near the top
1. Add `/* eslint-env mocha */` somewhere in the file, conventionally done near the top
1. In your .eslintrc file, enable the mocha environment for tests
    a. If your tests are in a completely separate directory from code, you could create an .eslintrc in that subdirectory
    a. Or you can use [glob pattern configs](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns) for cases where tests are in the same directory as tested code files
1. Require the functions as described above, so that they are actually local to the module rather than global

Hope this helps, feel free to come to [ESLint's chat room](https://gitter.im/eslint/eslint) if you need more help.

**Comment by boneskull** [comment]
@platinumazure thanks
