### ISSUE TITLE
drop support for non-ES5 compliant environments

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2979]
Support for IE7, IE8, and PhantomJS 1.x is an albatross.

By dropping support for these environments, we should:

1.  Reduce code complexity by removing handrolled shims.
2.  Reduce CI failures (hopefully!)
3.  Reduce number of edge cases in tests
4.  Reduce size of build matrix

Unfortunately I have no metrics on how many use Mocha for these environments.  

Please speak up if you are writing *new* tests for these environments with Mocha, and don't want to see support dropped.  I'm willing to entertain a good argument against!

**Comment by bdsomer** [comment]
Why haven't we dropped these already? Testing frameworks are mainly used by developers, and developers don't usually use old browsers anyway...

**Comment by ScottFreeCode** [comment]
> Welcome... to Windows 98. ***Why are you still using Windows 98?! What's wrong with you?***

~Strong Bad

Testing frameworks are mainly used to prove that some other code works, and client-side JavaScript doesn't generally run on developers' browsers, it generally runs on users' browsers. Thus, testing frameworks intended to support client-side JavaScript have the strongest use case of anything for supporting older (or even unambiguously outdated) browsers: the net sum of all other cases for allowing users to not upgrade, as long as there still are any in this day and age. Although there are, fortunately, far fewer now than back in the bad old days when anyone selling stuff online had to support IE6 indefinitely because everyone's grandmas used it!

(And, to be even more fair, there will always be the old versions of Mocha for testing older environments, so the real question is how much need there is for upcoming Mocha features and fixes used for testing the older environments. Pretty narrow scope. The trick is getting responses from people in a scope like that *before* they discover that all new versions of Mocha are breaking their tests...)

**Comment by bdsomer** [comment]
Has the team ever considered using [Babel](https://babeljs.io)?

**Comment by boneskull** [comment]
If Mocha was written in ES2015+ then Babel would be appropriate. Maybe it even will output IE7-compatible code. But the idea is to drop support; not support it via different means.

**Comment by bdsomer** [comment]
@boneskull Awesome, got it.

**Comment by boneskull** [comment]
The reason this has stuck around so long is twofold:

1.  Until the last year or two, PhantomJS 1.x was (more or less) the "only show in town" for headless browsers.
2.  Business requirements mandate compatibility with old browsers.  Developers may not use old browsers themselves, but are told to write code that'll work in IE8.  This is likely not as relevant for public-facing sites as it is for intranets.

As a side note, IE7 compatibility may not have been originally intended; we sort of stumbled onto that.

But!  Today is the dawn of a new era!  Onwards and upwards.  V is for victory, etc.

**Comment by boneskull** [comment]
this is done.
