### ISSUE TITLE
setTimeout() after done() is called (--watch mode)

### ISSUE THREAD

**Issue by gabssnake** [mochajs/mocha#3014]
Hello, thanks for your work on this project.

The following test passes when calling `mocha` from cli, but the assertion throws *after* the test passes when adding the `--watch` flag.

Changing `setTimeout` to `process.nextTick` makes the test always pass in both modes.
Changing the delay on `setTimeout` to lower values (10ms) makes the test pass sometimes in watch mode.

What is the expected behaviour?

```js
var assert = require('assert');

describe('Works consistently in regular cli and watch mode', function() {
  it('ignores setTimeout after done is called', function(done) {
    function myFunc(callback) {
      callback('sync');
      setTimeout(function() { callback('async'); }, 100);
    }

    myFunc(function(data) {
      assert.equal(data, 'sync');
      done();
    });
  });
});
```

Kind regards,

mocha 3.5.3
node 6.11.2
macOS 10.12.6

**Comment by ScottFreeCode** [comment]
Calling `done` multiple times is an error, as the first `done` call is supposed to indicate to Mocha that the test is complete. It's possible for the second `done` call to never execute because Mocha shuts down too quickly before it can, especially if it's the last asynchronous test; `--no-exit` should prevent that, and I'd imagine `--watch` prevents it as a side effect as well. Not so sure about anything being changed by `nextTick` or a shorter timeout -- those should make the error *more* likely to be shown since the second `done` call occurs faster, but I'll play around with this a little and see if I discover anything. We do have issue #2879 for changing the default behavior to not shut down if there's anything still running and instead have `--exit` to get the old default behavior, although it'll have to wait for a semver "major" update.

**Comment by gabssnake** [comment]
Thanks for your answer and input, I agree with your expectations about `nextTick` and shorter `setTimeout`, as well as with your comments on watch vs process exit.

Please see/try the following test case.

With `--no-exit` flag, test passes, it takes 10 secs to exit, no assertion is thrown.

With `--watch` flag, test passes, it takes 10 secs to throw: `AssertionError: 'async3' == 'sync'`. `nextTick` and shorter `setTimeout` never throw.

What am I missing?

```js
describe('', function() {
  it('', function(done) {
    function myFunc(callback) {
      callback('sync');
      process.nextTick(function() { callback('async1'); });
      setTimeout(function() { callback('async2'); }, 0);
      setTimeout(function() { callback('async3'); }, 10000);
    }
    myFunc(function(data) {
      assert.equal(data, 'sync');
      done();
    });
  });
});
```

**Comment by boneskull** [comment]
good question.

**Comment by gabssnake** [comment]
Time travelers: This issue has been resolved since `mocha v4`, released Sep 28, 2017.

The behavior is now consistent (always throws) in normal and watch mode, both with and without the `--exit` flag. Yay for consistency!

Thanks for the good work @boneskull and everyone!
