### ISSUE TITLE
drop Node.js v0.10 and v0.12 support

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3016]
We can no longer run our development environment on node.js v0.10/v0.12 (see request/request#2772) without adding a `npm-shrinkwrap.json` or doing other high-effort/low-reward things to work around this.

furthermore, it's making it more difficult to apply security fixes.  at least one of these Node.js  versions (v0.10) has known vulnerabilities which have gone unpatched (in an official capacity).

we should not continue to supply updates for these environments.

- [x] remove `0.10`, `0.12`, `iojs` & `5` from `.travis-ci.yml` and `appveyor.yml`
- [x] update `engines` field in `package.json`
- [x] necessary security upgrades (this includes `debug` and `growl`)
- [x] upgrade anything else we can get away with (stick to dev deps)

To be clear, Mocha *still runs* in Node.js v0.10 and v0.12; you just can't clone a working copy and run the test suite.

**Comment by boneskull** [comment]
also dump `iojs` because

**Comment by boneskull** [comment]
also Node.js v5 [is no longer maintained](https://github.com/nodejs/Release#release-schedule1), so drop that too.

**Comment by ScottFreeCode** [comment]
This week is the week we will merge as many [semver-major](https://github.com/mochajs/mocha/labels/semver-major) updates as we can?

**Comment by boneskull** [comment]
sure.  I'll try to release EOD Fri to give people the weekend to find whatever we broke.

**Comment by boneskull** [comment]
WIP PR: #3017

**Comment by boneskull** [comment]
@ScottFreeCode please throw stuff into kanban if you want to see it land

**Comment by ScottFreeCode** [comment]
Will do; gotta turn in for the night but can focus on it tomorrow so we have the middle of the week to evaluate stuff.

**Comment by boneskull** [comment]
closed via e39a867

**Comment by ScottFreeCode** [comment]
@boneskull Sorry this is later than I meant to get it, but I put a bunch of issues in a new kanban column "Evaluate for V4" -- the idea here being that we don't have to sort through the Todo or In Progress columns looking for which are semver-major *and* **these don't necessarily need to go in, I'd just like them *considered*.** (Again, apologies that there isn't much time left to consider them -- although some are either trivial or already have PRs, so there's that -- but that's also why I'm not saying any of them necessarily need to go in. Some of them you may have already looked at since they were labelled semver-major, as well.)

**Comment by ScottFreeCode** [comment]
PS. If you need any feedback, opinions or assistance from me on any of them let me know and I'll get on it as fast as I'm able.
