### ISSUE TITLE
How to submit new --exit option when running mocha programmatically

### ISSUE THREAD

**Issue by doberkofler** [mochajs/mocha#3072]
### Prerequisites
* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)

### Description
The Mocha 4 CLI has a new option --exit and was wondering if there is a corresponding option when invoking Mocha programmatically like `const mocha = new Mocha({exit: true});`
I was not able to find anything in the documentation or release notes.

**Comment by ScottFreeCode** [comment]
Hi @doberkofler,

The programmatic API in general doesn't have much documentation outside of the comments in the code.

However, I can tell you that `--exit` is only considered applicable to the CLI, because the CLI manages the process. When using Mocha programmatically, the script or module that uses Mocha is in control of the process and would be responsible for either allowing Node to exit or calling `process.exit`. The related default behavior change is only in the CLI as well.

**Comment by zhouhanseng** [comment]
So, how to use mocha with continuous Integration?

**Comment by rahul-sharma-uipath** [comment]
this is old but for anyone wondering about @zhouhanseng's question - we got around this by using the mocha lifecycle hook `end` and calling process.exit. Example - 

```
var exitCode = 0;

mocha
  .run()
  .on('fail', () => {
    exitCode = 1;
  })
  .on('end', () => process.exit(exitCode));
