### ISSUE TITLE
Tests with Mocha on Sequelize application disconnect after first test

### ISSUE THREAD

**Issue by pirmax** [mochajs/mocha#3079]
I use **Mocha** to test my **CRUD API** application. I have three tests and I have before/after function with callback:

    before((done) => {
        done();
    });
    
    after(function () {
        sequelize.close();
    });

But, when the first test is executed, the **Sequelize** connection is closed. How I can change this to run test and automaticaly close tests?

**Comment by ScottFreeCode** [comment]
Hi @pirmax,

`after` will run when all tests are done for whichever suite it is in. (If you want it to run only when all tests are done, you can move it outside of any suite.)

`afterEach` runs after every test. We recommend `beforeEach` and `afterEach` in order to ensure each test is isolated from the others.

We also recommend setting up external services in `before` or `beforeEach` that will be closed or cleaned up in `after`/`afterEach`. Whatever is run directly inside `describe` or at the top level of a test file gets run immediately before Mocha starts executing any tests; `before` and `beforeEach` are run when Mocha actually begins the tests for a suite (`before`) or before every test (`beforeEach`).

It's hard to say exactly what's happening with your code without seeing more than just the two hooks, however. If you need further assistance we will likely need an example that is minimal but complete -- i.e. we should be able to copy-paste it into a new/empty project and see the behavior in question.
