### ISSUE TITLE
Failed assertion in Describe()

### ISSUE THREAD

**Issue by icywolfy** [mochajs/mocha#3083]
### Prerequisites
* [X] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [X] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [X] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [X] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
Is there any way to have Mocha not throw a stack-trace when an assertion fails in a describe() block?  (as opposed to within it())

We are looking into change behaviour on a product, but we simply get a stack trace, rather than a list of broken tests.   This is because several thousand of our test cases have expect(s) within a describe rather than within an it() // presumably done by peple in error.
Others, are using them in context() and setting up a context, and making assertions that the context is valid, before moving on to it() test cases.

Either way, there's no way to determine the full extent of how much will break, because it simply dumps out a single stack trace, rather than being captured and sent to a reporter.

### Steps to Reproduce
describe('a', () => {
    expect(false).equal(true);
});
**Expected behavior:** [What you expect to happen]
Not throw a stack trace.

Reporter: "Test Case a failed. " (where "a" here is the tree of describes/contexts that we are in)

Nice to Have, but probably not possible: 
 If an assertion is called outside of an it(), to display it in the test results as well.  As it stands, we have no idea how many test cases across our GHE are in this state, all that we know is that they currently pass. 
 
**Actual behavior:** [What actually happens]
Stack trace.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

**Comment by ScottFreeCode** [comment]
Failing assertions outside of tests are unlikely to be "properly" reportable since at that point the reporter hasn't even been initialized (in general the reporter can't be initialized yet, some of them have to know how many tests there are at the report start). And (just in my opinion), given that those are doubly in error (not only is the assertion failing but it shouldn't be made in `describe` to begin with), I'm not sure it's a bad thing that they end up with much more focused "reporting" in the form of a crash rather than formatted test results. Plus, even if they pass they won't be listed as passed tests (Mocha doesn't really have any way to tell apart `describe`s with passing assertions from `describe`s that are being used properly), so something more really needs to be fixed...

Trying to think of the easiest way to correct the issue. Say, a linting rule that would detect these (maybe even fix them by changing `describe` to `it`), whether based on `describe` without any `it`/`describe`/etc inside it or based on `describe` containing your chosen assertion library (or both)... Or a similar code-mod to just make the fix.

Unfortunately I haven't got around to learning how to write either of those (most of my en-masse code updates have been done with `grep` and `sed`, which won't do for finding something like "code block that might have other code blocks nested in it"). If anybody does know how (or knows of an existing one), I'd appreciate any assistance we can get here.

**Comment by boneskull** [comment]
don't put an assertion in a `describe` block, that's not what it's for.
