### ISSUE TITLE
Using context only for the sake of hooks not for title and reporting

### ISSUE THREAD

**Issue by slavafomin** [mochajs/mocha#3107]
Hello!

Thank you for this great framework!

I'm using some contexts (the describe blocks) only in order to specify `before` and `after` hooks to be ran after the test inside of it. But, I do not want these blocks to affect the report structure or to add any additional titles. However, each new context would create a new level in tests hierarchy, which is used for reporting. The problem is that I need to provide two titles for describe block, which is just used as a wrapper for my test, and in the test itself, and I don't have two titles for them. Of course I can just skip the title for context or for the test, but it will look ugly both in code (I will have to pass an empty string) and in test reports.

I think the overall problem is that contexts are serving two different purposes:

1. To organize test hierarchy in order to build test reports.

2. To serve as a "container" for hooks executions.

So, this leads to conflict: on one hand I need to add a context in order to have hooks for my test, on the other hand, I don't want to introduce another structural level in my report.

I see the possible solutions as follows:

1. Allow to specify `before/after` hooks for specific tests w/o using contexts (the test itself serves as a context of some kind).

2. Allow to omit titles for tests or describe blocks, effectively making them ephemeral (i.e. not displaying in reports as a distinct level).

Does this makes sense?

Thank you!

**Comment by ScottFreeCode** [comment]
We have #2741 for at least part of this. Currently in Mocha typically setup and cleanup that isn't meant to be reused for multiple tests\* just gets written into the test -- you have to make sure that cleanup happens even in case of failure (e.g. with `try`-`finally`), and it will report errors in setup or cleanup as failure of the test, and if you want it to be visibly separate in the source you have to just use space and/or comments, but it kinda sorta works. I've floated the idea once or twice that having distinct hook-like steps for better reporting but specific to individual tests instead of implicit via suite-shared `Each` hooks might be the best of both worlds, but there hasn't been a lot of discussion surrounding the API for such a feature, and, to be honest, any addition to Mocha's already complicated logic surrounding hooks is probably not going to be easy to do. It's not necessarily impossible though...

\* Actually, even if it were meant to be reused you could still write it into each test using functions instead of Mocha's hooks, if you prefer either the explicitness of it or the greater level of control you get that way to such an extent that it's worth the tradeoffs.

**Comment by slavafomin** [comment]
Thank you @ScottFreeCode for an elaborative answer. I guess I will try to use the `try ... finally` pattern you've mentioned and will see where it would take me. Also, the #2741 looks like a good solution to the problem I've mentioned. It would be nice to have a `cleanup/after` hook on the test level. However, I have no knowledge of mocha internals, so I can't really comprehend how difficult it is to implement such functionality.

**Comment by boneskull** [comment]
@slavafomin creating a custom reporter is pretty straightforward; there are many examples out there.  start with the `spec` reporter and go from there.

**Comment by slavafomin** [comment]
@boneskull Creating a custom reporter would be an overkill for this specific problem and wouldn't solve it at it's core.

**Comment by boneskull** [comment]
you could omit certain suites from being “reported” anyway. I’m not sure why you need to do what you’re trying to do.
