### ISSUE TITLE
Is it possible to customize `it` method?

### ISSUE THREAD

**Issue by mocheng** [mochajs/mocha#3114]
Since all my test cases have some common procedure, I'd like to customize the `global.it` as below.
```
const originaIt = global.it;

global.it = function(description, fn) {
    originaIt(description, function() {
        // do something before test
        try {
           fn();
           // do something after test
        } finally {
           //do something to clean up 
        }
    });
};
```

I put above code in file `helper.js` and import it from each test files. It turns out that imported files are executed only once, but Mocha re-initialize `it` to be its original function for each file. So, only the first test file has the customized `it`.

I know that `beforeEach` and `afterEach` serves same purpose, but customized `it` is preferred.

So, is there any other way to customize `it` for all test files?

**Comment by ScottFreeCode** [comment]
Off the top of my head I can think of a couple different approaches...
- Name it something other than `it`
- `var it = require("./helper")` and `module.exports = ...` instead of just `require("./helper")` and `it = ...`

Both of these are more explicit about the fact that this isn't the regular `it`. I've heard of Mocha's interface functions being monkey-patched by some testing libraries that build on Mocha, but I've heard about it because the attempt to patch them has caused *other* problems.

> I know that beforeEach and afterEach serves same purpose, but customized it is preferred.

Is there a particular reason it's preferred? I might be able to give more specific advice with a more specific idea of what you're trying to achieve.

**Comment by mocheng** [comment]
@ScottFreeCode My current solution is same as your first suggestion.

My case is kind of writing test helper in Mocha like rxjs spec helper https://github.com/ReactiveX/rxjs/tree/master/spec/helpers. In convention, this test helper doesn't have `beforeEach` like setup.

**Comment by ScottFreeCode** [comment]
Ah, interesting -- https://github.com/ReactiveX/rxjs/blob/master/spec/helpers/testScheduler-ui.ts looks like it's actually defining a custom interface that imitates the BDD interface. That's the ultimate technique I guess -- you should be able to select custom interface packages or files pretty much the same way you select the built-in interfaces. If you really wanted to patch the regular BDD interface instead of defining a totally new one, you could even delegate to the original before performing the customization logic.

The one caveat I would submit when using an interface that looks like Mocha's built-in ones but is customized (regardless of whether it's patched or totally new) is to make sure that any changed expectations won't cause problems. That is, if you go down that route we'd recommend testing:
- Running tests with Mocha's regular interface that depend on the customized behavior and making sure that if that happens (e.g. by accident if someone were to forget to use the customized interface) the resulting behavior is acceptable (e.g. a hard error rather than an incorrect pass).
- Using all the available variations of Mocha's interface (alternate names like `context` and `specify`, all the skipping styles such as `it` with no test body, `xit` and `it.skip`) to be sure that they work the same in the customized one.

**Comment by boneskull** [comment]
+1 to "write your own interface"

**Comment by ORESoftware** [comment]
@mocheng just a warning


`try/catch` is not sufficient - you have to trap `uncaughtExceptions` / `unhandledRejections`

it's non-trivial stuff,  [domains](https://nodejs.org/api/domain.html) sort of work, but they aren't perfect


```js
const originaIt = global.it;

global.it = function(description, fn) {
    originaIt(description, function() {
        // do something before test
        try {
           fn();
           // do something after test
        } finally {
           //do something to clean up 
        }
    });
};
```
