### ISSUE TITLE
Documentation around glob patterns and shell expansion

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3136]
_From @boneskull on July 12, 2015 4:15_

from mochajs/mocha#1115

> Not sure if it is needed, but it may be worth noting that due to shell expansion, glob patterns should be wrapped in double quotes on unix shells.
> 
> ```
> mocha -w -r should "test/**/*.js"
> ```
> 
> Using that would render the --recursive flag useless.

_Copied from original issue: mochajs/old-mochajs-site#8_

**UPDATE** Double quotes for portability--don't want to say single quotes in one place and double quotes in the other, so DOUBLE QUOTES (single quotes fine on *nix if you don't want variable expansion to happen, but let's assume there are no variables in use)

**Comment by akrawchyk** [comment]
A good example of documentation for this is in the [NON-BUGS section of the `find` man page](http://man7.org/linux/man-pages/man1/find.1.html#NON-BUGS).

I'm thinking the documentation for this should be in usage examples which is one of the options proposed by @mrjoelkemp in the original issue https://github.com/mochajs/mocha/issues/1115. This is because I can't find any examples in man pages or otherwise where the command invocation for globs is documented (since this is related to the behavior of shells, not mocha or otherwise).

So, for starters should I beef up the "Getting Started" CLI example? https://github.com/mochajs/mocha/blob/master/docs/index.md#getting-started

**Comment by ematipico** [comment]
Is this issue still valid? I could offer some help

**Comment by akrawchyk** [comment]
@ematipicoI think this will be easy to fix once there is a clear solution. What do you think of my proposal above?

**Comment by boneskull** [comment]
@ematipico @akrawchyk I welcome any PR addressing this, we can discuss.  see updated description though

**Comment by akrawchyk** [comment]
@boneskull PR opened, I'm waffling on the language for this but I took a first stab just to get the ball rolling.
