### ISSUE TITLE
ESnext-ify development scripts

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3146]
Since we no longer support anything below Node.js v4, it follows that we should be able to write our development scripts in whatever ES features **Node.js v4** supports.  To see what we can use, [check the Kangax tables](https://kangax.github.io/compat-table/es6/#node4). 

> In Node.js v4, `let` and `const` work as expected *in strict mode* only*. We should be OK to use it.

This does *not* include most source files and test files, as those would require transpilation that we aren't currently using (setting *that* up can be a separate effort if it makes sense).

Here's the list of what needs to be upgraded:

- [x] `bin/*`
- [x] ~~`index.js`~~ nothing to do
- [x] `scripts/*.js`
- [x] `karma.conf.js`

Furthermore, appropriate `.eslintrc.yaml` files should be added, or existing ones modified.

There are more sources and tests which will never touch a browser, but they aren't marked as such nor organized; we'll leave those.

As a reminder, the oldest environments Mocha supports are Node.js v4 and IE9.

**Comment by Bamieh** [comment]
What do you think about adding babel to the mix in the webpack configs?

We'd support the following (similar to [airbnb's babel configs](https://github.com/airbnb/babel-preset-airbnb)):

all standard syntax that is stage 4 (ES2017) or stage 3, except for the following:

- generators: regenerator-runtime is too heavyweight for our use.
- async/await: regenerator-runtime is too heavyweight for our use, and async-to-promises is not yet complete enough to be safely used.
- SIMD: this is a performance feature, so is pretty pointless to polyfill/transpile.
- lifted template literal restrictions: we do not use tagged template literals, nor implement custom DSLs, otherwise we would enable this.
- We have also enabled object rest/spread, although it is only at stage 2. It will hopefully achieve stage 3 soon.
