### ISSUE TITLE
Unwrap an array of assertion errors

### ISSUE THREAD

**Issue by mojavelinux** [mochajs/mocha#3211]
### Prerequisites

- [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Some test frameworks collect errors and throw them all at once. One example of this is kapok-js. Mocha should detect an array of assertion errors, unwrap them, and report each one in turn. Jest supports this feature, so there is precedent set, which some test frameworks rely on.

### Steps to Reproduce

Example test:

```js
const AssertionError = require('assertion-error')
  
describe('thrown errors', () => {
  it('should unwrap an array of assetion errors', () => {
    const e1 = new AssertionError('fail')
    const e2 = new AssertionError('another fail')
    throw [e1, e2]
  })
})
```

**Expected behavior:** Each assertion error is reported in turn.

**Actual behavior:** Mocha issues the warning: "the array [...] was thrown, throw an Error :)"

### Versions

mocha --version = 5.0.0
node --version = 8.9.4

**Comment by mojavelinux** [comment]
Here's what Jest outputs:

```
 FAIL  ./test-jest.js
  ✕ should unwrap an array of assetion errors (2ms)

  ● should unwrap an array of assetion errors

    Error
      AssertionError: fail,AssertionError: another fail thrown
```

**Comment by mojavelinux** [comment]
Fixing this just seems to involve allowing the the error array to be emitted, then changing the list() function in the base reporter to iterate if test.err is an array. I'd be happy to help.

**Comment by boneskull** [comment]
This will introduce more complexity than is immediately apparent.  We can't just iterate in the base reporters, because other reporters won't know what to do with this data--and some of the output  formats simply don't support more than a single error.  This means Mocha would need to wad up the array into a single error.

Indeed, why not an object with `Error`s as values?  Why not a `Set` of `Error`s?  Why not a `Map` with `Error` objects for keys?  etc.

* * *

Fair warning: opinions ahead.

A single assertion per test is best, but if multiple assertions are necessary, they should only provide a single error.  For instance, Chai allows you to chain assertions, but only throws one error.  

Instead of this, perhaps better to iterate over the `Array` and reduce it to a single `Error`:

```js
throw [new Error('a'), new Error('b')]
  .reduce((errorWad, err) => {
    errorWad.message += `${err.message}\n${err.stack.join('\n')}`;
    return errorWad;
  }, new Error());
```

Even though there may be precedent in Jest, I'm unsure of its necessity.  Would be interested in seeing the docs / implementation and real-world use cases.

**Comment by mojavelinux** [comment]
I strongly disagree. I've since learned that this is not a feature unique to jest. ava also supports tests which throw an array of assertion errors. So there's strong precedent in modern test frameworks.

I also have a real world use case for this. The CLI testing tool Kapok spawns a command and collects assertion errors during its execution. It then throws them after the command has completed. This is an essential feature for CLI and other integration testing since it's not possible (or expensive) to perform fine-grained assertions. They have to be gathered and reported later. Otherwise, it's too tedious and time consuming to get meaningful information back from the test run.

IMO, this is clearly a deficiency of mocha.

**Comment by mojavelinux** [comment]
I'd be open to considering a compound error that reports as a single error for reporters that don't support it, yet provides access to a collection of errors for those that do. But we'd still need to agree on what exception class / interface to use.
