### ISSUE TITLE
Publishing Passed Test Cases Information to report

### ISSUE THREAD

**Issue by YogeeshKapila** [mochajs/mocha#3277]
### Description

Hi, 
I am trying out Mocha for a project of mine, to test a REST API.
Is there any way by which I can capture the **headers and payload and response** information for a passed test case and publish it in my report.

I am using the JUnit reporter.

I searched for issues related to this but couldn't find any leads.

Any help in this regard would be appreciated.
Thanks!

**Comment by Bamieh** [comment]
@YogeeshKapila Hello, The JUnit reporter is not part of core mocha, however I looked into the source code and they do not provide the functionality you are seeking, maybe open an issue asking for such feature or fork the reporter and add your own "properties" submitted to the reporter.

P.S @boneskull 
AFAIK non of our reporters (or the base) provide the ability to append to the cases as well, maybe it is a good idea to implement such a feature or add an event listener to the base reporter in order to allow reporters to implement their customization?

**Comment by boneskull** [comment]
This sounds like a custom reporter to me.  

You can do something like this in your test (**untested**):

```js
describe('my suite', function () {
  it('should make a request, receive a response, etc', function(done) {
    const headers = {'Content-type': 'your mom'};
    const body = '{"some": "json"}';
    request({url: 'http://whatever', headers}, (err, res) => {
      // this is the Context object
      this.myData = {headers, body, res};
      done();
    });
  });
});
```

and then a custom reporter:

```js
function MyReporter (runner) {
  runner.on('pass', test => {
    const myData = test.ctx.myData;
    // do something with myData
  });
};
```

A `Runner` sends the `Test` instance when emitting `pass`, so you have access to whatever was stuffed into it.  I just hope the context (`.ctx`) isn't destroyed before getting to this point.
