### ISSUE TITLE
CI thoughts

### ISSUE THREAD

**Issue by plroebuck** [mochajs/mocha#3378]
### Brainstorming

Work done to use new Travis build steps was a **big** improvement.
Can we go further?

Thoughts concerning speeding up the CI process or improving coverage.

Speed up CI?
* Drop Node-9.x support ASAP - brings nothing not already available in Node-10.
* [Travis] Reorder tests from lowest version to latest (fail faster)
  - Perhaps less help with Node-4 going away, but dev probably using modern version of Node
* [Travis] Run 'coverage' as final build step
* [AppVeyor] Just run tests against latest Node on Windows
  - Since limited to 2 jobs max on free acct, this just crawls...

Improve coverage
* [Travis] We test against Linux - but not macOS?
  - Again (like Windows above) just against latest Node

**Comment by plroebuck** [comment]
[Linting speedup](https://github.com/okonet/lint-staged/) possibility...

**Comment by boneskull** [comment]
Let's drop Node.js 9 when it's EOL'd at end of June.

All of the tests in a stage are run concurrenly, so reordering would involve moving stages around or creating new ones.  Since a stage cannot begin until the previous stage ends, stages are not without a cost.  If we were going to optimize stages further, I'd suggest looking at the historical build data, and figuring out which jobs fail most often, and how quickly they fail.

Personally, I'd value complete coverage on Windows over a fast build time when it comes to AppVeyor.  If we had to, we could also just pay for it.

If/when we add tests for the "watch" functionality, we should absolutely add macOS as a target.  Unlike Windows, since macOS is a POSIX OS, I'm not too terribly worried, running it against current Node.js only is fine.

**Comment by plroebuck** [comment]
Tests (in theory) run concurrently, but watching shows that's not exactly true. As (in my experience) the oldest Node version seemed most likely to break (and last test to get started), my suggestion was only to order them by version in ascending order, rather than descending.

Was only suggesting less Windows due to AppVeyor's postal job completion rate. Newest/oldest would seem adequate (max free concurrent jobs anyway). Do we have builds where we show Windows breakage on only in-between supported  Node versions?

How about we switch to macOS to run the coverage test? Trivial change that adds explicit platform support. And make it be the _last_ test started.

The lint speedup could be very nice. No need to run lint on files that didn't change. 'Course, lint time is dwarfed by job setup, but...
