### ISSUE TITLE
Feature request: Output filter to re-run failed tests

### ISSUE THREAD

**Issue by moander** [mochajs/mocha#3410]
Would it be possible to output a auto generated filter that can be used to re-run only the failed tests?

**Comment by outsideris** [comment]
I dont' think it is mocha's responsiblity.

You can filter it with a`json` report and [jq](https://stedolan.github.io/jq/) like:

```
$ mocha -R json TEST-FILE.js | jq '.failures[] | "mocha TEST-FILE.js --grep \(.fullTitle)"'
```

**Comment by moander** [comment]
I think mocha is responsible for making it easy to run tests (as today) but also to re-run tests.

Thank you for your solution but I still think --arg would be nicer ;)

**Comment by outsideris** [comment]
@moander Otherwise https://github.com/mochajs/mocha/pull/3408 could be helpful.

**Comment by olivierlacan** [comment]
It's common for mature testing frameworks to offer output formatter assistance to: 
- single out failing tests by grouping them all at the bottom of the test run feedback
- re-run exclusively failing tests (by storing last run failures in a temp file), see [RSpec's `--only-failures`](https://relishapp.com/rspec/rspec-core/docs/command-line/only-failures)
- potentially run each failing test one by one instead of all at once (similar to a --fail-fast flag)

So I would challenge your assertion that this is not Mocha's responsibility @outsideris.

The fact that you suggest a single but complex (to the average user) piped command using a dependency that isn't necessarily installed on someone's system (jq) or available in their CI environment makes my point.

If it's so easy to suggest a one-liner answer, why isn't Mocha doing this for its users to offer them a productivity boost?
