### ISSUE TITLE
autoscroll mocha html reporter

### ISSUE THREAD

**Issue by nojvek** [mochajs/mocha#3514]
We use saucelabs which records browser tests in different browsers. The recordings aren't meaningful as it only shows the first few tests, if something goes kaboom in an off-scroll area, it's not easy to know.

Would be nice to set an option to mocha so it automatically scrolls html #mocha (like a cli console) when there is new output.

**Comment by JoshuaKGoldberg** [comment]
This has had exactly three people interact with it -two of whom are maintainers- since it was posted over 5 years ago in 2018. Closing as a low interest feature.

In userland areas such as Sauceland, folks can always inject a script that continuously presses page down, and/or use multiple reporters.
