### ISSUE TITLE
Feature: ability for fork each test in a separate process and join the results.

### ISSUE THREAD

**Issue by burtonator** [mochajs/mocha#3545]
Right now my mocha is locking up due to some setTimeout or other open resource in the code...

and I can't find out why.

I was using mocha-parallel-tests which forks for each test.  But it's buggy and is skipping tests.  

It would be KILLER if mocha could fork on each test, then collect the results so that timeouts and other issues didn't lock up my tests.  

I realize that I should test for them,  but right now that's not my priority. I don't want my test harness to lock up.

**Comment by plroebuck** [comment]
Try [wtfnode](https://github.com/mochajs/mocha/issues/3044#issuecomment-422982548)

**Comment by Xotabu4** [comment]
@plroebuck 
Hi, i did some experiments with new nodejs worker_threads, but unfortunately i have to spin full mocha instance in each worker and pass grep parameter to each worker so it runs only one test. Also there are issues with existing reporters, test outputs. But CPU and RAM consumption is pretty low with workers, and also i can try to .fork nodejs process for better cores utilization, since workers are all running in single process.

https://github.com/Xotabu4/mochajs-multithread-workers

I can greatly improve this, if i could unblock mocha from sequential running tests one by one and just schedule everything, and wait for everything to complete.

Any advices would be helpful!
