### ISSUE TITLE
[Feature Request] Convert to ES Modules

### ISSUE THREAD

**Issue by pdesjardins90** [mochajs/mocha#3585]
With all major browsers now supporting ES modules and node support on its way, I think it would be a great time to migrate this popular lib and help the community move forward.

To be clear, the goal would be to be able to do:

In node: 

```javascript
import { 
  after, 
  afterEach, 
  before, 
  beforeEach, 
  context, 
  describe, 
  it 
} from 'mocha'
```

In browsers:
```javascript 
import { 
  after, 
  afterEach, 
  before, 
  beforeEach, 
  context, 
  describe, 
  it 
} from '/node_modules/mocha/mocha.js'
```

**Comment by outsideris** [comment]
Mocha supports Node.js v6+.
However, node.js supports ES modules since [node 8.5.0](https://nodejs.org/en/blog/release/v8.5.0/) and still [Experimental](https://nodejs.org/api/esm.html). I believe we can't migrate it.

**Comment by pdesjardins90** [comment]
@outsideris  even if the build step outputs an AMD build for backward compat?

**Comment by outsideris** [comment]
@pdesjardins90 mocha is a test framework. It should be transpiled?

**Comment by pdesjardins90** [comment]
Mocha is used in multiple environments that don't support all the same features, i.e. browsers and node. The repo's current strategy regarding that is outputing a single transpiled script file that can be ran into browsers, while using the CommonJS `require()` syntax in its core files. The browser script relies on global variables, which is widely considered a bad practice, but was a necessary evil in browsers until ES modules came out. 

ES modules bring a native, language-based way of managing modules that will be compatible on both environments. You're right about it being currently experimental in node, but even if it lands in the next version, you're probably going to want to support older runtimes for a while, unless you make a breaking change and force all of your users to upgrade to the latest version of node and ES modules, which may be a little too rough for such a popular and trusted library. 

Hence my suggestion to include a backward-compatible version of mocha's CommonJS modules, while updating its source to ES modules.

**Comment by pdesjardins90** [comment]
I'll add that the browser script should still be packaged for the same reasons

**Comment by pdesjardins90** [comment]
@outsideris any chance you'll reconsider?

**Comment by pdesjardins90** [comment]
@boneskull perhaps as top contributor to this repo, you may have a different opinion?

**Comment by boneskull** [comment]
@pdesjardins90 

sure, I'd like to modernize the codebase and use new ES2015+ features.

But as long as we target IE11 (still not an insignificant % of market share), that means we will need to transpile our code to support it.

So that's two things:

1. Configure transpilation (for production and our test suites) which results in both a CJS-based distribution pkg for supported Node.js versions *and* an IE11-compatible, AMD-compatible bundle
1. Refactor the codebase to use new JS features (this can be a gradual process)

It's nontrivial and introduces the potential for a lot of regressions.  I don't know if it's worth it.  Maybe better to wait until IE11 drops off of the radar entirely and Node.js has stable native ES module support so we can avoid the headaches?  

If someone wanted to do the work in 1., assuming it didn't break things, I'd approve it, but the team would still need to consider the added build and test complexity (**maintenance burden**) to be worth it.

**Comment by boneskull** [comment]
This might be a duplicate of something.  If it's not, we could leave it open as a "modernize Mocha's build"-type ticket.

**Comment by boneskull** [comment]
(@outsideris is correct, but there's more to the story than just Node's experimental  ES module support)

**Comment by pdesjardins90** [comment]
Ok thanks for the explanation, I understand your predicament better. I'll do a POC on my end, see how it goes and how it may impact maintenance. I'll open a PR if I come up with anything that would check everyone's boxes.

Thanks again for your input

**Comment by outsideris** [comment]
@pdesjardins90 I couldn't find duplicated issue with this. If re-opening this issue and it is helpful to your work, I can re-open it.

**Comment by pdesjardins90** [comment]
Oh I think I’ll work on my end first and when I have something to show for we could reopen this and reference it in the PR for documentation, I’ll keep you posted!
