### ISSUE TITLE
add Matomo badge to site

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3705]
[Matomo](https://matomo.org) now sponsors Mocha by providing its services to our project for free.  Here's a badge we can add to our site:

![image](https://user-images.githubusercontent.com/924465/52010312-1d77fb80-248a-11e9-95f5-3c093dae2a61.png)

Link to `https://matomo.org` unless we hear otherwise.

**Comment by sunkakar** [comment]
Hi. Can you give me some more context on where the badge needs to be added? 
I would like to work on this issue!

**Comment by boneskull** [comment]
@sunkakar Just near the bottom somewhere.  thanks!

**Comment by vrozin** [comment]
Hi! I am interested in helping with this issue, but I have one point of confusion:
The list of sponsors is coming from [Open Collective](https://opencollective.com/mochajs/sponsor/), which then gets added to README.md and [http://npmjs.com/package/mocha](http://npmjs.com/package/mocha). 
I'm not sure how to approach this since there's no access to website's assets to add the badge.

**Comment by boneskull** [comment]
create a new list at the bottom. separate from OC sponsors

**Comment by vrozin** [comment]
Hello, 
The PR [#3749](https://github.com/mochajs/mocha/pull/3749) has been submitted.
Please tell me if anything is to be changed.
