### ISSUE TITLE
CLI processing of 'mocha.opts' dropping positional arguments

### ISSUE THREAD

**Issue by plroebuck** [mochajs/mocha#3763]
### Description

'mocha.opts' processing seems to handle option arguments correctly, but positional arguments
are not present.

### Steps to Reproduce

See this [gist](https://gist.github.com/mceachen/dcabad5476fea0e0c92dafe4869a0057).
Note right before error occurs that it's using "test/" instead of "dist/**/*.spec.js".

**Expected behavior:** [What you expect to happen]
Expect the code to work like it did in Mocha-5.2.0.

**Actual behavior:** [What actually happens]
`Error: No test files found`

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

- The output of `mocha --version`: **6.0.0**
- The output of `node --version`: **v10.15.1**
- Your operating system
  - name and version: **Ubuntu 18.04.2 (bionic)**
  - architecture (32 or 64-bit):
- Your shell (e.g., bash, zsh, PowerShell, cmd): **bash**

### Additional Information
None

**Comment by halkeye** [comment]
ya! i was going to write up a bug for it and got distracted.

Its absolutely a yargs thing, I think I tracked it down to https://github.com/yargs/yargs-parser/blob/18d0fd582996b3004bc92f2b46b9cd9776550414/index.js#L546 because args._ is always defaulted to [], it'll never pick it up from the file.

So i'm guessing https://github.com/mochajs/mocha/blob/master/lib/cli/options.js#L114-L117 needs to be updated to loop through `configOptions` and merge the _ variable

I'm just not sure if it should be replaced, appended, prepended, etc.

**Comment by boneskull** [comment]
see #3768.
