### ISSUE TITLE
Improve file watching

### ISSUE THREAD

**Issue by geigerzaehler** [mochajs/mocha#3912]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
When using the `--watch` option Mocha reruns tests when files change. This is quite helpful but the current implementation suffers from a couple of problems. I’d be more than glad to implement the required changes.

Current problems

* New files are not picked up (#2176)
* What files to watch can only be controlled by the `extensions` configuration. In particular that makes the following uses impossible:
  * Only watch files in a certain directory (#2702)
  * Watch files without extensions
  * Exclude certain files and directories from watching (#2554)
* It always uses the slow [`fs.watchFile`](https://nodejs.org/dist/latest-v12.x/docs/api/fs.html#fs_fs_watchfile_filename_options_listener) even when `fs.watch` is available.
* It is impossible to watch files in `node_modules` and `.git`

**Describe the solution you'd like**

* Use [`chokidar`](https://github.com/paulmillr/chokidar) to get reliable and fast file watching.
* Add a `watchFiles` (name subject to bikeshedding) configuration option that accepts a list of file paths, directories, and globs to watch.
* Rerun tests when a file matching `watchFiles` is added 
* Add `watchIgnore` (name subject to bikeshedding) that accept a list of globs to exclude from watching. Defaults to `['node_modules', '.git/**']`
* Keep backwards compatibility if none of the new options are specified

**Describe alternatives you've considered**
Using `nodemon` would address all the problems. Since this creates a new process on file changes this approach is to slow, especially when using Babel or TypeScript for on-the-fly compilation. There also has been talk (#1780) of deprecating the `--watch` options and use separate tools to accomplish reruns. However people are relying on watch (https://github.com/mochajs/mocha/issues/1780#issuecomment-373974766).

**Comment by juergba** [comment]
@geigerzaehler yesterday I tried to get into this "watch" topic with #3851. I  realised there should be two lists - a watch list and a test list - and the current solution has to be improved or deprecated otherwise.

I would be very happy to get your help with these improvements. So please go ahead with your implementation! In this repo sometimes it can be very painful to push big changes upto the final merge. I will do my best to support you.

What are your reasons for choosing "chokidar"?

**Comment by geigerzaehler** [comment]
Thanks for the support @juergba!


> I realised there should be two lists - a watch list and a test list - and the current solution has to be improved or deprecated otherwise.

If I understand you correctly my proposal is in line with your observation. (Please correct me if I’m wrong.) I’d be interested in more of your thoughts on this topic.

> What are your reasons for choosing "chokidar"?

* It solves the problems I described above with a nice API
* It is widely used, including large projects like Webpack ([dependents on NPM](https://www.npmjs.com/browse/depended/chokidar))
* It is actively developed
* Code quality seems good and its test suite is quite large (and uses mocha :wink:)

I’m not aware of any alternatives with some major advantage.

**Comment by juergba** [comment]
Yes, we are inline. There must be a way to choose the directories/files being watched. Currently the `cwd` is selected and we have no option to change this.

Just for my understanding: everything you propose could be achieved with Node's FSWatcher, but chokidar has the better/faster one, right?

Probably it's best to extract the watcher into a seperate modul. I'm waiting for the confirmation we can use ES6. Since we are still supporting IE11, we are forced to code in ES5 in most of our modules.

Configuration options: I don't know yet how we will handle this. It could be via CLI, via Mocha's configuration files or both.

Mocha still has some unsolved issues with re-running tests, I hope we will get around this.
I found an older proposition which also uses chokidar [mocha-watch](https://github.com/paulpflug/mocha-watch/blob/master/_mocha.js#L394). Maybe you can have a look at it to get some ideas.

**Comment by geigerzaehler** [comment]
> Just for my understanding: everything you propose could be achieved with Node's FSWatcher, but chokidar has the better/faster one, right?

Yes, `chokidar` can be faster and does not have the quirks node’s filesystem watch API has. It may use the Node API under the hood, though.. On MacOS it uses [`fsevents`](https://www.npmjs.com/package/fsevents) which is generally faster and has fewer issues.

> Probably it's best to extract the watcher into a seperate modul.

👍 

> Mocha still has some unsolved issues with re-running tests, I hope we will get around this.
Could you post links to the issues that I did not yet include in the description here so that I can try to fix them if possible?

**Comment by juergba** [comment]
ES6: should be ok, see our [gitter conversation](https://gitter.im/mochajs/contributors) 
* `.eslintrc.yml`: add the watch module to `overrides`
* `package-scripts.js`: add `--ignore chokidar` to the build script `browserify ...`
* `package.json`: add `chokidar: false` to `browser`

**Comment by juergba** [comment]
re-run issues: have been reported for years, see f.e. #736, #1938
The most actual issue is probably: #2783 

PS: please try to keep this PR as lean as possible. It's far easier to get reviews for smaller PR's than for bigger ones.

**Comment by juergba** [comment]
@geigerzaehler is there anything I can do to go on with this one?
