### ISSUE TITLE
Add option to kill current test on change detected in watch mode.

### ISSUE THREAD

**Issue by icetbr** [mochajs/mocha#4195]
### PROBLEM
Hi, when running in watch mode and a change is detected, a new run is scheduled but the current one still runs to the end. This slows down testing when the rest of the code has expensive calls.

### EXAMPLE
Something I do frequently, lets say I want to modify the following method to include the user email, but I don't know how to extract it.

```js
module.exports = {
  async createUserFromContact(contactId) {
    const result1 = await api.getContact(contactId);
    const user = { name: result1.data.username }; // how do I get the email?
    const result2 = await api.createUser(user);
    return result2;
  }
}
```
I put a breakpoint in `const user = ...`, run the test for that code and inspect `result1` to learn how to extract the user email.

Then I modify the code and save the file.

### DESIRED BEHAVIOR
I want the execution to immediately stop and the test to be run again.

### ALTERNATIVES
I can do that when using nodemon.

Thanks

**Comment by juergba** [comment]
Mocha does not spawn a child-process for each test re-run as _Nodemon_ does.
Therefore we can't just massacre the child-process - ignoring any side-effects - and start from zero with a new child-process.

Therefore we are not planning to implement your feature request.

Anyway we have to re-think our `watch` implementation in the middle run, since ESModules can't be watched with our current `watch` feature.
