### ISSUE TITLE
Better TypeScript integration

### ISSUE THREAD

**Issue by craigtaub** [mochajs/mocha#4351]
We have had reports that the 2 mechanisms for using TypeScript

1. via `tsnode`
2. compile code then run tests 

Are both not ideal and rather slow. Can we look at improving this?

**Comment by Munter** [comment]
The slowness come from the typescript compiler. So I don't see how we could add anything on top of that to improve the compilers speed. I think the best we could do is having a mode where we skip unchanged files. That comes with its own set of problems with dependency graph tracing, which we already know we're not super good at from the current implementation of watch mode.

I think there are bigger wins to get if someone could find a good way to have typescript do less work when running with `tsnode/register`. Then we could document that configuration

**Comment by boneskull** [comment]
Yes, maybe the real problem is skipping unchanged files.

**Comment by boneskull** [comment]
The specific ask from @bajtos was:

>  First-class support for TypeScript: compile from TS to JS at runtime, apply source maps to stack traces, understand and apply source maps when parsing code coverage data in watch mode.

@bajtos or @raymondfeng, can you explain again how LB is doing this currently?  Have you experimented with `mocha --enable-source-maps` or `NODE_V8_COVERAGE=1`?

**Comment by boneskull** [comment]
(as I understand you compile up-front then run tests on the compiled output, and are not using `ts-node` because I assume it's slower?)

**Comment by raymondfeng** [comment]
@boneskull Yes, we run `tsc` to transpile and generate source map files up-front. 

Here is what we have to enable source map support:

```
"require": ["source-map-support/register"],
```

Does mocha already support `--enable-source-maps`?

**Comment by boneskull** [comment]
it should if your node version does. mocha passes known node flags thru to node. (“known” is reported by node itself; we don’t have to keep a list)

**Comment by boneskull** [comment]
is ts-node too slow then? trying to get at the real problem

**Comment by raymondfeng** [comment]
> it should if your node version does. mocha passes known node flags thru to node. (“known” is reported by node itself; we don’t have to keep a list)

The `--enable-source-maps` option is NOT available in Node 10, which is the minimum version we require.

**Comment by raymondfeng** [comment]
> is ts-node too slow then? trying to get at the real problem

We're avoiding ts-node for a few reasons:
- Less magic for JS developers
- Allow our modules to be used by JS
- Performance concerns
- Subtle bugs we encountered with ts-node in the past

**Comment by bajtos** [comment]
When I think about my experience with mocha in https://github.com/strongloop/loopback-next (a large-ish monorepo written mostly in TypeScript), the biggest pain point is slow feedback in [red-green-refactor cycle](https://www.codecademy.com/articles/tdd-red-green-refactor). 

1. I start by writing a failing test, this typically involves changing a single test file.
2. Then I write an implementation to make the new test pass. Most of the times, this changes few lines of code in a single "production" file, but sometimes can touch more than one file.
3. Now I want to run the new test to see it pass, but also run all existing tests that may be affected by the change. 

Current status: to see the output of a newly added test, I run an incremental build via `tsc -b` and then re-run the entire test suite. The first step is reasonably quick and can be further improved by TypeScript's watch mode (`tsc -b -w`). The second step is slow (our test suite takes more than a minute to complete in parallel mode). Sometimes I work around it by running only tests from a single package, but this has problems too.

To see the effect of the new implementation, I repeat the same steps. However:
- When changing code in a library-like package shared by other packages in the monorepo, it's not enough to run the test suite in the changed package only, I need to verify downstream dependents too.
- Sometimes the implementation requires changes in upstream dependencies (within the monorepo). Fortunatelly, `tsc -b` is smart enough to rebuild those changed projects. However, it's more tricky to figure out what subset of tests is sufficient to verify the changes.

Setting aside code-coverage watch mode discussed in #4350, my biggest wish for `mocha` is to support TypeScript-aware watch mode, to get the following experience:

1. I start mocha and/or TypeScript compiler in watch mode
2. After saving the test file with my new test, code is automatically recompiled and the test file is executed.
3. After saving the implementation files, code is automatically recompiled and (somewhat) relevant test files are executed.

I see two implementation options:

1. Run two processes (`tsc -b -w` and `mocha -w`). I did not test this myself, because I think it's not possible for Mocha to know when the compilation has finished, so I expect Mocha 
to re-run the test suite several times during the compilation, as it sees changes coming from the TypeScript compiler.
2. Another option (and I think this will offer a better UX) is to leverage something like `ts-node` to allow Mocha to process TypeScript files on the fly. I don't know how is this going to work though:
- Will `ts-node` honor TypeScript Project References and rebuild downstream dependents?
- Our packages are configured with `main` pointing to `dist/index.js` created by the compiler, will `ts-node` fix Node.js `require` resolution to understand that it should load `src/index.ts` instead?
- How about the watch mode - will Mocha correctly detect when to re-compile & re-run the test suite? 

I was briefly experimenting with Jest a year or two ago, I found the developer experience provided by https://github.com/kulshekhar/ts-jest so great that I was strongly considering to migrate our project from Mocha to Jest. Can Mocha perhaps draw some inspiration from that plugin?
