### ISSUE TITLE
How to use addFile in browser with npm package of mocha

### ISSUE THREAD

**Issue by zyf0330** [mochajs/mocha#4406]
Hello, I am using karma and karma-mocha to test in browser. I need to use `addFile` to execute some code before test code. And what happened is, `addFile` and `loadFiles` use `path.resolve` and `path` module is a empty object. Extual mocha file which is executed is mocha.js at root path in npm package. So except use mocha.js built for browser or import webpack to handle, is there any other way to solve it? 
I just haven't find any doc about how to build code to run in browser with mocha npm package. It seems that `browser-entry.js` still use `path.resolve` in `loadFiles`

**Comment by juergba** [comment]
I don't really understand your question. We ourselves are using _karma_ and _karma-mocha_ in our CI-tests. Have a look at our implementation in order to understand how to load your test files.

Our _mocha/mocha.js_ built is for use in browser.
`addFile`, `loadFiles`, `path.resolve` and `path` can't be used within a browser.

> I just haven't find any doc about how to build code to run in browser with mocha npm package.

If you prefer to not use our built _mocha/mocha.js_ for your browser, we are using _rollup_ for this purpose (before _browserify_).

**Comment by zyf0330** [comment]
I want to use `files` option to load setup script.

**Comment by M00TSDNS** [comment]
There is a way to do this.

*   Import `mocha/mocha` in runner script.
*   After, import all your scripts using `await Promise.all` or just list all your `import`s.
*   Then roll it all up using webpack.
