### ISSUE TITLE
Auto describe filename

### ISSUE THREAD

**Issue by sla100** [mochajs/mocha#4482]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
I'm always frustrated when still add the same code on any script:

```js
describe(__filename, () => {
   ...
});

or

describe(import.meta.url, () => {
   ...
});

```

**Describe the solution you'd like**
Configuration property `describeScript` or `describeModule`.

**Comment by boneskull** [comment]
This can be done with a custom reporter.  You can print this by listening for the `EVENT_SUITE_BEGIN` event once per file, when the current suite's parent is the root suite.  

```js
// my-reporter.js
// (untested)
const Mocha = require('mocha');
const {Spec} = Mocha.reporters;
const {constants} = Mocha.Runner;

class MyReporter extends Spec {
  constructor(...args) {
     super(...args);
     runner.on(constants.EVENT_SUITE_BEGIN, suite => {
       if (suite.parent?.root) {
         console.log(suite.file);
       }
     });
  }
}
```

This will require some more fiddling if you happen to have multiple top-level `describe` blocks per file--e.g., remember which filenames have already been printed and don't print them twice.  if a file does _not_ have a `describe` in it, you can do the same for tests by listening on `EVENT_TEST_BEGIN` (since the `Test` object will also have a `file` prop).
