### ISSUE TITLE
Exclude inactive sponsors and backers

### ISSUE THREAD

**Issue by outsideris** [mochajs/mocha#4595]
We can discuss whether  we exclude inactive sponsors and backers from our mochajs.org. 
Of course, we thank both past and current sponsors and backers. But we can't show all accumulated sponsors and backers because it is too long list.

Below are @juergba 's comment from #4570 and I think `last donation more than one year ago` is good base line.

> I had a quick look at opencollective's API. The information lastTransactionAt seems to be available. We should list active sponsors/backers only and exclude the older ones (last donation more than one year ago).

> With the URL https://opencollective.com/mochajs/members/all.json we can export our contributor data in JSON format.
The JSON file also includes a property lastTransactionAt to distinguish active from inactive sponsors/backers.
IMO we should exclude inactive contributors.

**Comment by juergba** [comment]
+1 for limiting our listings to active sponsors/backers.
Above mentioned JSON file unfortunately doesn't contain the `category` property we need for our spam filter.

**Comment by juergba** [comment]
@znarf We select our backers/sponsors in [supporters.js](https://github.com/mochajs/mocha/blob/master/docs/_data/supporters.js), you have contributed to this code in the past as well (category).
Maybe you can give us a hint where to add a filter, eg. sponsors/backers who haven't contributed since one year will be considered inactive.

Which date field can we use to filter active backers/sponsors?
- `Order.updatedAt`: is this the date of the last transaction?
- or do we have to check for `Transaction.createdAt` or `updatedAt`?

I'm new with the OpenCollective's API and any help would be appreciated. Thanks.

**Comment by juergba** [comment]
@outsideris I pushed a filter with `status: ACTIVE` to the `mochajs.org` branch. The listing is much smaller now!
Can you have a look, please?

I still wonder:
- why USD5 contributions appear in the sponsors section?
- why do we exclude VPN contributions from listing? I think we should list them.

**Comment by juergba** [comment]
> why USD5 contributions appear in the sponsors section?

Done. Actually we have only one active sponsor left! 😔

**Comment by juergba** [comment]
Btw account `codepilotai` with the unsupported image type has `status===CANCELLED` and won't be selected anymore.

**Comment by outsideris** [comment]
Sorry for the late response. 
It's a surprise we have only one sponsor.

Anyway, LGTM.
