### ISSUE TITLE
 async code throw uncaught error after async test is stopped

### ISSUE THREAD

**Issue by iqianxing** [mochajs/mocha#4651]
### Prerequisites

> > async test throw an uncaught error when test is timeout.
> > my test code like below:
> > ```
> > var assert = require('chai').assert;
> > describe("# async test", function () {
> >   this.timeout(2000);
> > 
> >   it("async error", function (done) {
> >     var errorMessage = "some error"
> >     setTimeout(function () {
> >       assert.notOk(errorMessage)
> >       done();
> >     }, 5000)
> >   })
> > })
> > ```

### Description
 async code throw uncaught error after async test is stopped

### Steps to Reproduce
1. copy the test code into a test file;
2. run ```npx mocha```
**Expected behavior:** 
test is failed;
**Actual behavior:** [What actually happens]
test is failed and throw an uncaught error

**Reproduces how often:** 100%

### Versions
8.4.0
### Additional Information

> > i run my test , an uncaught error display on my console like below:
> > ![image](https://user-images.githubusercontent.com/2938263/121025336-a2e8e480-c7d7-11eb-8a6a-522cd83757e6.png)
> > error detail:
> > ```
> > mocha\lib\runner.js:962
> >     throw err;
> > ```
> >   
> > ![image](https://user-images.githubusercontent.com/2938263/121025735-0f63e380-c7d8-11eb-87d7-47808510e8f3.png)
> 
> async code is still running after async test task is stopped.

**Comment by juergba** [comment]
@iqianxing this uncaught error is intended behaviour.

There is no way to map this pending async task to any test (yes, in this special case, because there is only one test). It's not a good practice to swallow uncaught errors and to continue as if nothing has happened.

You can use the `--exit` option to ignore any pending async task after tests have finished, but `--exit` is not considered to be a nice option. Depending on it is normally a sure sign that you should review your tests.
