### ISSUE TITLE
ESM Import is cached when re-using the process when using mocha programmatically

### ISSUE THREAD

**Issue by smcenlly** [mochajs/mocha#4655]
Hey guys - congrats on releasing v9! 🎉

Our product ([Wallaby](https://wallabyjs.com)) uses mocha programmatically and by default reuses the node process between test runs. In the latest version of mocha (`v9`) subsequent changes to a test file are not executing after the first test run. It appears that the import only happens on the first test run which means that on subsequent calls, the context functions (`it`, `describe`, etc.) are not re-executed and test execution bails.

We are not sure if this problem is specific to how Wallaby is calling mocha but we would not have thought so. In the past, we have had to add a cache breaker in the past for other parts of Wallaby and Quokka that natively support ESM. Specifically, [this line of code](https://github.com/mochajs/mocha/blob/master/lib/esm-utils.js#L7) is causing the problem:

```javascript
  // https://github.com/mochajs/mocha/blob/master/lib/esm-utils.js#L7
  return await import(url.pathToFileURL(file));
```

For now, we have patched this ourselves by adding a cache breaker as we have in other parts of Wallaby (same technique as [described in this blog post](https://ar.al/2021/02/22/cache-busting-in-node.js-dynamic-esm-imports/#cache-invalidation-in-esm-with-dynamic-imports)). So the code becomes:

```javascript
  return await import(url.pathToFileURL(file) + "?update=" + Date.now());
```

**Comment by smcenlly** [comment]
After following the technique described in the blog post, we had a problem with the change we suggested. The query string needs to be added after the `pathToFileUrl`. Have updated the original issue description so that it is now correct.

**Comment by juergba** [comment]
@smcenlly thank you.

Mocha is supporting Node's native ESM support since v7.1.0. The ESM loader uses its one cache, different to `require.cache` of CJS files. Node doesn't offer any API to clear the ESM cache, and afaik they will probably never do.
For that same reason we don't support `watch` mode with ESM test files, yet. We have no solution to clear the cache either, and we probably will have to spawn a new process for each `watch` re-run.

> In the latest version of mocha (v9) [...]

There shouldn't be any changes refering to ESM cache from v8.4.0 to v9.0.0. Is there any different behavior?

**Comment by juergba** [comment]
> There shouldn't be any changes refering to ESM cache from v8.4.0 to v9.0.0. Is there any different behavior?

I'm going to close this issue within the next few days.
