### ISSUE TITLE
Standard font is glitching in the reporter

### ISSUE THREAD

**Issue by owenallenaz** [mochajs/mocha#4694]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

When I run `mocha@8.4.0` the reporter formats the text correctly, but when I run `mocha@9.0.2` or any of the `9.x.x` line, the text output isn't formatted correctly regarding the sizing and spacing of the tests.

* 8.4.0 - https://www.screencast.com/t/mIfO519e78 - Checkmarks in the right size, no spaces between the different tests.
* 9.x.x - https://www.screencast.com/t/P2RBeinqJXrz - Notice the check marks are being cut-off in a weird way.

This behavior is happening when I use the `node:14.17.3` or `node:14.17.3-buster-slim` docker containers.

### Versions

- Windows 10, running a linux vagrant Ubuntu, running Node docker container.
- global mocha - none
- local mocha - 9.0.2
- OS - Debian Buster 10 or Debian Stretch 9
- /bin/bash or /bin/sh both exhibit the problem

**Comment by JoshuaKGoldberg** [comment]
I believe this is a Windows-specific bug with emojis. Mocha 9 switched to the thicker `✔` emoji rather than the old `✓`. Running these in the VS Code terminal on macOS 14:

<img width="584" alt="Screenshot of running a passing mocha test with npx mocha@8, then mocha@9. 8 has the thin ✓ emoji while 9 has the thicker ✔." src="https://github.com/mochajs/mocha/assets/3335181/f3845f24-a2f3-4b8a-b51d-107aa29f96a8">

Please let me know if I'm wrong here - and if so, which terminal app(s) you're using.
