### ISSUE TITLE
Add extension to bin files

### ISSUE THREAD

**Issue by lachrist** [mochajs/mocha#4720]
Hi mocha team!

Using the [`--experimental-loader`](https://nodejs.org/api/cli.html#cli_experimental_loader_module) node flag with mocha bin will cause it to crash because it has no extension.

**Example:**

```sh
NODE_OPTIONS="--experimental-loader=./lib/loader.mjs" npx mocha
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for .../mocha/bin/mocha
```

**Explanation:**

More specifically, the `--experimental-loader` flag will cause node to pick the esm loader to load `bin/mocha` and it does not like file without extensions (unlike the cjs loader).

**Solution:**

Add ".js" extension to `bin/mocha` which would still allow to create a symbolic link at `.bin/mocha` without file extension.

**Comment by juergba** [comment]
@lachrist duplicate of #4645

Since `--experimental-loader` is still experimental and under redesign, we are not planning to add this extension to Mocha's binary for now. As a workaround you can move `--experimental-loader=./lib/loader.mjs` from NODE_OPTIONS to Mocha's config file `.mocharc.js`. Then Mocha will start a child-process with the entry point _lib/cli/cli.js_.

**Comment by lachrist** [comment]
Sorry for the duplicate!
