### ISSUE TITLE
Spec path starting with a dot breaks exclude globs

### ISSUE THREAD

**Issue by the-spyke** [mochajs/mocha#4785]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Steps to Reproduce

Having `.mocharc.json` file:

```json
{
  "exclude": [
    "node_modules/**"
  ]
}
```

And running Mocha like this: `npx mocha './**/*.spec.ts'`

**Expected behavior:** should run tests from all files **excluding** `node_modules`

**Actual behavior:** 

Fails inside a `spec` file of a dependency inside `node_modules` which means `exclude` doesn't work:

```sh
$ npx mocha './**/*.spec.ts'
/Users/user/project/node_modules/runtypes/src/asynccontract.spec.ts:1
import { AsyncContract, Number } from '.';
^^^^^^
```

And runs as it should if I remove `./` from the path like so:

```sh
$ npx mocha '**/*.spec.ts'
```

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 9.1.3
- The output of `node --version`: 16.13.0
- Your operating system
  - name and version: macOS 11.6
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): bash
- Your browser and version (if running browser tests): node
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): ts-node@9.1.1

**Comment by juergba** [comment]
@the-spyke

I did some testing:
- **ok:** `npx mocha '**/*.spec.ts'` and `"exclude": ["node_modules/**"]`
- **not ok:** `npx mocha './**/*.spec.ts'` and `"exclude": ["node_modules/**"]`
- **not ok:** `npx mocha '**/*.spec.ts'` and `"exclude": ["./node_modules/**"]`
- **ok:** `npx mocha './**/*.spec.ts'` and `"exclude": ["./node_modules/**"]`

Mocha first processes the globs (both spec and exclude) and then resolves the path of resulting files.
Since the string `./node_modules/runtypes/src/asynccontract.spec.ts` doesn't match the pattern `node_modules/**`, the exclusion doesn't work. On the other hand when defining the globs consistently, either both with `./` or both without, then the exclusion works.

Imo we shouldn't fiddle around with user's globs and my proposition is to leave things as is.

Anyway it's better to not put your tests in the root folder, and add a separate `test` folder for this purpose.

**Comment by the-spyke** [comment]
@juergba Giving you some context: 

* `exclude` is defined in the config, but `npx mocha 'path'` is called by devs when they want to test a single file. Not super convenient to have such behavior.
* Tests aren't located in the root. It's opposite. We have like 15 root dirs with code and it's easier to exclude few, than pass all those to mocha on run.

**Comment by juergba** [comment]
There is an open [issue](https://github.com/isaacs/minimatch/issues/30) on Minimatch, dated back in 2014.

Your ideas are welcome.
As a work-around you can set: `"exclude": ["node_modules/**", "./node_modules/**"]`

**Comment by JoshuaKGoldberg** [comment]
https://github.com/isaacs/minimatch/issues/30#issuecomment-1040599045 indicates this isn't a bug in minimatch:

> `**` does not match `.` unless `{dot:true}` is set, and even if it is set, it does not ever match `.` or `..` as path portions.
> 
> Paths starting with `./` and `../` _never_ match a pattern that doesn't start explicitly with `./` or `../`, even if `{dot:true}` is set.
> 
> This is by design, and matches the behavior of bash 4.3+.
