### ISSUE TITLE
Mocha v7.0.2 supports ESM, but not v9.1.3

### ISSUE THREAD

**Issue by Dom-Mac** [mochajs/mocha#4806]
Mocha version v7.0.2 works out of the box with ESM by using a node script as
`mocha  -r esm './test/*.test.js'`
Mocha versions after the 7.0.2, for example the 9.1.3 version, results in the following error:
`SyntaxError: Cannot use import statement outside a module`

node version: v16.13.1
MacOS

**Comment by juergba** [comment]
Mocha supports Node's native ESM since [v7.1.0](https://github.com/mochajs/mocha/releases/tag/v7.1.0), so for almost two years now. See also [docs](https://mochajs.org/#nodejs-native-esm-support).

The package **esm** hasn't been maintained for almost three years, is abandonded and isn't supported by Mocha anymore.
