### ISSUE TITLE
Please join to us #standwithukraine

### ISSUE THREAD

**Issue by id-dan** [mochajs/mocha#4864]
Please support Ukraine, more infos here: https://github.com/vshymanskyy/StandWithUkraine

**Comment by id-dan** [comment]
@juergba Pls have a look on it

**Comment by juergba** [comment]
@id-dan I will have a look, I'm in doubt because of your own behaviour in other repos, see https://github.com/postmanlabs/newman/issues/2951#issue-1192634949.

> What the fucking is "off-topic", killing families, is it off-topic? [...]
If it is not on the topic, then you are no different from the Nazi-Russian

Respecting other people's opinions without insulting them is one of the most basic rules of a democratic civilization.

**Comment by id-dan** [comment]
@juergba I agree with you

it is very difficult to control emotions when peaceful people and innocent children are killed. Someone treats it lightly, and writes "it is off-topic"

**Comment by juergba** [comment]
@id-dan I'm against any political message in our package/docs/readme.

I propose to donate some of our OpenCollective funds (USD 10'000) to support The Ukrainian Red Cross, see https://opencollective.com/support-ukraine.
@mochajs/core thoughts?

**Comment by juergba** [comment]
ok, donation done.

**Comment by id-dan** [comment]
@juergba thank you a lot.
