### ISSUE TITLE
./node_modules/mocha/bin/mocha: not found, mocha bin is now in ./node_modules/mocha/bin/_mocha

### ISSUE THREAD

**Issue by alberto56** [mochajs/mocha#4880]
Starting a few days ago, running:

    npm install mocha 

Seems to install the mocha binary in ./node_modules/mocha/bin/_mocha

Previously it was in ./node_modules/mocha/bin/mocha

I could not find any reason for this. Is this by design?

**Comment by juergba** [comment]
Before Mocha v10.0.0 we had `bin/_mocha` and `bin/mocha` executables.
With mocha@10.0.0 we have  `bin/_mocha` and `bin/mocha.js`, so we have added an extension to one of the files. We have listed this topic as breaking change in our changelog with links explaining the reasons.

**Comment by tombrouwer** [comment]
Hi Alberto,

Je issue viel mij op. Misschien een vreemde vraag, maar waarom gebruik je niet `node_modules/.bin/mocha`?

**Comment by alberto56** [comment]
For reference, the changelog is in https://github.com/mochajs/mocha/pull/4863, thanks for the response.

@tombrouwer I did not know about `node_modules/.bin/mocha`!

I will close this issue, thanks for the reply.

**Comment by chris-miner** [comment]
> I noticed your issue. Maybe a strange question, but why don't you use `node_modules/.bin/mocha`?

Or how about `npx mocha`

**Comment by ssbarnea** [comment]
There is something weird about this because looking at `node_modules/.bin/mocha` I do see that this is the only file that does not have exec bits on it.

That is a symlink pointing to `../mocha/bin/mocha.js` which is also missing the exec bits, even if it does have a shebang line.

AFAIK, any file that has a shebang must have the exec bits set on it. Not sure why mocha in particular does not have these.
