### ISSUE TITLE
Context built-in properties cause problems

### ISSUE THREAD

**Issue by domenic** [mochajs/mocha#503]
A test more or less like this one broke when upgrading to Mocha 1.3, due to 8e5cc0a2abeacd0088a79350211d183629c5a8d1 introducing a `test` property into the context of all tests that is used if found:

```js
describe("blah", function () {
    beforeEach(function () {
        this.test = function () { };
    });
    
    it("should not break", function () {
        this.test().should.not.throw();
    });
});
```

I previously had the same problem with the name `runnable`, which took a lot of head-scratching to understand. I guess now it's renamed to `_runnable`.

In general there is a namespace collision here, between using `this` as a storage place for things to test (as an alternative to the closure), and Mocha's use of it as a place to put utility functions. It'd be great if Mocha's stuff could be namespaced, perhaps? Something like `this.mocha.runnable`, `this.mocha.test`, etc.? Or (double)-underscored? `this.__runnable`, `this.__test`?

**Comment by danielstjules** [comment]
I noticed Domenic worked on this a bit in https://github.com/domenic/mocha/commit/877e850a6c3ff3cc7f595636781dddfa6a5a96ce

A few other properties have been added since this issue was created as well: `skip`, `slow` and `enableTimeouts`. Unfortunately, cleaning this up and moving these functions to a `mocha` property would be a backwards incompatible change to the API, so it's not something I'm assuming would be considered for the current major release.

I'm gonna close this for now. But if there's renewed interest, I think it could be directed towards a 3.x release. Something for a which a branch seems to exist, but I'm not sure what its state is.
