### ISSUE TITLE
move less important reporters in to npm-land

### ISSUE THREAD

**Issue by tj** [mochajs/mocha#509]
I think we should move CI-specific reporters into npm-land, "teamcity", "xunit" can simply be "teamcity-reporter" etc in npm and add to https://github.com/visionmedia/mocha/wiki#interfaces--reporters

**Comment by ngeor** [comment]
Seems like xunit format is the least common denominator, supported in various build servers (jenkins, Bamboo, TeamCity). I wouldn't take xunit reporter out because it will give the impression mocha doesn't have built-in support for CI, which is not the case.

I would suggest closing this ticket as "won't fix" and say that any new reporters would have to go to their own repo (unless the community thinks they're core).
