### ISSUE TITLE
try domains in a branch

### ISSUE THREAD

**Issue by tj** [mochajs/mocha#513]
this will fuck over client-side support nicely but yeah

**Comment by TimothyGu** [comment]
@jonathanong said:

> @evantahler said:
>
>> @jonathanong said:
>>
>>> domains are deprecated :D
>>
>> Whoa! That's news to me. Google and http://blog.nodejs.org/ doesn't turn anything up... have a link?
>
> it was a conference. well he said, "i want to deprecate domains", so that's basically deprecating it

OK, this is exceptionally lame.

3. Domains are still not deprecated according to official docs.
   - Oral deprecation is not visible enough on the Internet.
4. People still use domains.
5. People still use Mocha.js.
6. People still throw exceptions synchronously.
7. People still throw exceptions synchronously in domains in Mocha.js.
8. This bug is closed.
