### ISSUE TITLE
🚀 Feature: Allow to set timeout on before/after/beforeEach/afterEach in declaration

### ISSUE THREAD

**Issue by perrin4869** [mochajs/mocha#5202]
### Feature Request Checklist

- [X] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/main/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md)
- [X] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [ ] I want to provide a PR to resolve this

### Overview

`it` returns a `TestFunction` that has a `timeout` method. This is useful for setting timeouts in slow tests, without needing to define the test code inside a `function() {}` block.
An analogous feature would be useful for the `before/beforeEach/after/afterEach` hooks. The current workaround would be:

```javascript
before(function() {
  this.timeout(3000);
});
```

### Suggested Solution

`before/beforeEach/after/afterEach` could return a `HookFunction`, analogous to `TestFunction`, which has a `timeout` method. The code above could be rewritten:

```javascript
before(() => {}).timeout(3000);
```

### Alternatives

None

**Comment by JoshuaKGoldberg** [comment]
👍 Agreed, I'm surprised they didn't have this already! This took me a bit to parse through as someone who doesn't use those APIs much. Putting a summary here for clarity...

There are two ways to describe a timeout:

* `this.timeout(...);`: allowed for _hooks_ (`before(...)`, etc.) as well as _tests_ (`it(...)`, etc.)
* test.timeout(...): only allowed for _tests_

Assuming I'm understanding correctly, this issue is asking to allow `hook.timeout(...)`. Doing so would mirror the `test.timeout(...)` already allowed.

**Comment by perrin4869** [comment]
@JoshuaKGoldberg thanks for summarizing it more clearly than the original post 🙂

ok, I just looked into the codebase, and I think this will be very simple to implement, but I am not sure about potential implications. I will send a PR shortly
