### ISSUE TITLE
Cross test pollution through the runnable context

### ISSUE THREAD

**Issue by JamesMaroney** [mochajs/mocha#587]
When building specs, we tend to build up our code under test and attach it to the running context. Sadly, we've noticed that this context is shared across test runs. Here's a minimal failing spec that shows the issue:

``` javascript
var assert= require('assert');
describe('Context Pollution', function(){
    it('First Pass, setting property on context', function(){
      this.pollution = true;
    });

    it('Second Pass, property should not be set', function(){
      assert.equal(undefined, this.pollution);
    });
});
```

As a stop-gap fix, I added an event handler to the 'test' event which cleans out the test context (keeping your internal keys). I'll put up a pull request with this just in case you like that approach.

**Comment by corybill** [comment]
What is the status on this?  I personally consider it to be a major defect.  I completely agree that the context should be reset between tests.  This is a dangerous precedent and allows accidental successes to happen too easily.  Each and every variable in a test should be specifically defined for a given test.  I should never have information from some other test just because I didn't manually reset the entire 'this' context.
