### ISSUE TITLE
Using multiple greps

### ISSUE THREAD

**Issue by jockster** [mochajs/mocha#649]
I tried using multiple greps to run specific suites. It appears that the two greps I used (`-g @helpers -g date`) resulted in that suites featuring either of the greps were run instead of suites that featured both, which I expected.

Is this functionality already there and I am doing something wrong?
If not, I would like to propose this as a future enhancement.

**Comment by danielstjules** [comment]
It seems like the behavior @tj had in mind has been supported for a while:

```javascript
$ cat example.js
it('foo', function(){});
it('bar', function(){});
it('foobar', function(){});

$ ./bin/mocha --grep foo example.js

  ․․

  2 passing (3ms)

$ ./bin/mocha --grep 'foo|bar'  example.js

  ․․․

  3 passing (3ms)

```

However, reading the original post by @jockster suggested that they wanted intersection of regexps, rather than union. While there's no flag available for this, you can manually do it. For example, strings containing both foo and bar:

``` javascript
$ ./bin/mocha --grep 'foo.*bar|bar.*foo'  example.js

  ․

  1 passing (3ms)
```
