### ISSUE TITLE
bug: mocha causing EADDRINUSE when spawning a child process in a directory

### ISSUE THREAD

**Issue by andrewrk** [mochajs/mocha#769]
See https://gist.github.com/superjoe30/5140725 for a simple broken test case.

**Comment by jlchereau** [comment]
+1 Same issue

**Comment by dasilvacontin** [comment]
@jlchereau could you provide a simple breaking test?

**Comment by andrewrk** [comment]
my gist url changed: https://gist.github.com/andrewrk/5140725

**Comment by jlchereau** [comment]
Not sorted yet, but I now think the issue is with Webstorm, not mocha.

**Comment by dasilvacontin** [comment]
@andrerk, by default, mocha executes all files under `test/**` in order to build up the suits and the tests.

In your case it means that the server is being started two times:
* when mocha executes `server.js` to build up suits/tests,
* and with the `spawn` in `test.js`.

Since the two servers try to listen at the same port, you get the EADDRINUSE.

**Comment by dasilvacontin** [comment]
In general, if you get EADDRINUSE, it's probably because you are starting multiple servers, or not correctly closing previous ones before starting new ones.

**Comment by jbnicolai** [comment]
Exactly. The fault lies not with mocha here.

**Comment by zwhitchcox** [comment]
Except the fault does lie with mocha, because even if you catch the error, mocha still fails the testf
