### ISSUE TITLE
browserify breaks at require('./lib-cov/mocha')

### ISSUE THREAD

**Issue by darvin** [mochajs/mocha#880]
`mocha/index.js`:

```
module.exports = process.env.COV
  ? require('./lib-cov/mocha')
  : require('./lib/mocha');
```

```
Error: module "./lib-cov/mocha" not found from "/Volumes/work/Projects/yaas/node_modules/mocha/index.js"
```

**Comment by ksikka** [comment]
I'm still unable to browserify a file that require's mocha. Error:
> Error: Cannot find module './lib-cov/mocha' from '/Users/ksikka/test_mochify/node_modules/mocha'

Anyone else in the same boat?

Tried it with node 0.10, 0.12, the latest browserify in npm (11.2.0), the latest mocha in npm (2.3.3).

**Comment by markmenox** [comment]
Same here with node 4
even if i have:
"browser": {
    "debug": "./lib/browser/debug.js",
    "events": "./lib/browser/events.js",
    "tty": "./lib/browser/tty.js",
    "mocha": "./mocha.js"
  },

in package.json of mocha module

**Comment by ksikka** [comment]
@tj reopen?

**Comment by markmenox** [comment]
Yes it should be defenitively. Right now it is broken with browserify and the only solution i have for the moment is to keep mocha library (with all my js files that use it), out of browserify process

**Comment by boneskull** [comment]
I'm reopening this, but tentatively.  

Maybe [mochify](https://npmjs.com/package/mochify) will help you guys.

**Comment by boneskull** [comment]
don't need whatever ancient coverage stuff is baked in.  we should use something else.

**Comment by SonofNun15** [comment]
Webpack has the same issue, by the way. Why is mocha conditionally requiring a file that does not exist? Is this file generated under some conditions? What triggers this file to be generated?

**Comment by kuraga** [comment]
Yes, why?

**Comment by kuraga** [comment]
Should be `"browser": "./support/browser-entry"`, no?

**Comment by Sigfried** [comment]
Same issue here with webpack.

**Comment by tswaters** [comment]
> Why is mocha conditionally requiring a file that does not exist? Is this file generated under some conditions? What triggers this file to be generated?

@SonofNun15 It's all in the makefile.  when running `test-cov` it uses the jscoverage tool to instrument the code into `lib-cov` - then mocha runs with the COV environment variable set to report out coverage for the instrumented code.... The initial discussion is in #5 and d4666c2 is the initial commit.

@boneskull I see you added PR PLEASE -- what's the scope of a PR you'd accept?  To switch coverage to something less obtrusive -- or get `require('mocha')` under browserify working?

I think this can be fixed by [ignoring](https://github.com/defunctzombie/package-browser-field-spec#ignore-a-module) lib-cov/mocha, i.e. adding  `"./lib-cov/mocha": false` to the browser field in package.json

**Comment by AlastairTaft** [comment]
Came here to offer my 2 cents for a webpack workaround

```
resolve: {
  alias: {
    stylus$: 'stylus/lib/stylus',
  },
}
```
